<a href="https://colab.research.google.com/github/Penguinbeanie/Capstone-Project/blob/dev_branch/Capstone_Project_Data_Generation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Loading Model

In [ ]:
!pip install -q google-generativeai

In [ ]:
import google.generativeai as genai
from IPython.display import display, Markdown
import json
import os


GOOGLE_API_KEY = "AIzaSyBoGjGywMUV9-4GcrN1F2FQ0EE92c6uYCY"

# configure the key for calling GenAI model
genai.configure(api_key=GOOGLE_API_KEY)

# load model
model = genai.GenerativeModel("gemini-1.5-flash")

# Sorting Original Questionnaire Questions by Question Type

In [ ]:
import json
import requests
import os

output_dir = "question_types"
if not os.path.exists(output_dir):
    os.makedirs(output_dir)

input_files = [
    "https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/main/original_questionnaire/original_files/questionnaire1.json",
    "https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/main/original_questionnaire/original_files/questionnaire2.json",
    "https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/main/original_questionnaire/original_files/questionnaire3.json",
    "https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/main/original_questionnaire/original_files/questionnaire4.json",
    "https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/main/original_questionnaire/original_files/questionnaire5.json"
]

# Dictionary to hold questions grouped by type
question_types = {}

# Iterate through each file
for file_url in input_files:
    response = requests.get(file_url)
    data = response.json()
    for entry in data:
        q_type = entry['type']
        if q_type not in question_types:
            question_types[q_type] = []
        question_types[q_type].append(entry)

# Save each question type to separate JSON files
output_files = []
for q_type, questions in question_types.items():
    filename = os.path.join(output_dir, f"{q_type}.json")
    with open(filename, 'w') as f:
        json.dump(questions, f, indent=4)
    output_files.append(filename)

print(f"Files have been created in the '{output_dir}' directory.")

Files have been created in the 'question_types' directory.

# JSON To String For Context

In [ ]:
# Load files

import json
import requests

file_path_date = 'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/main/original_questionnaire/type_seperated/DATE.json'
file_path_multi = 'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/main/original_questionnaire/type_seperated/MULTI_SELECT.json'
file_path_number = 'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/main/original_questionnaire/type_seperated/NUMBER.json'
file_path_single = 'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/main/original_questionnaire/type_seperated/SINGLE_SELECT.json'
file_path_text = 'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/main/original_questionnaire/type_seperated/TEXT.json'

# Function to load JSON from URL
def load_json_from_url(url):
    response = requests.get(url)
    response.raise_for_status()
    return response.json()

# Load JSON data from URLs
try:
    json_data_date = load_json_from_url(file_path_date)
    json_data_multi = load_json_from_url(file_path_multi)
    json_data_number = load_json_from_url(file_path_number)
    json_data_single = load_json_from_url(file_path_single)
    json_data_text = load_json_from_url(file_path_text)

    # Convert JSON data to strings (if needed)
    json_string_date = json.dumps(json_data_date, indent=4)
    json_string_multi = json.dumps(json_data_multi, indent=4)
    json_string_number = json.dumps(json_data_number, indent=4)
    json_string_single = json.dumps(json_data_single, indent=4)
    json_string_text = json.dumps(json_data_text, indent=4)

except requests.exceptions.RequestException as e:
    print(f"Error loading JSON files: {e}")

# Running the Model

In [ ]:
# prompt

multiVar = 10
singleVar = 10
numberVar = 50
textVar = 50
dateVar = 50

prompt_multi = f"""
                Using the context below as a template, create {multiVar} more JSON objects. The output should include only the keys "type",
                "question", and "options". Ensure the "type" is always "MULTI-SELECT". The "options" array should contain multiple unique objects,
                each with the "option" key and a meaningful value representing an available choice. No IDs should be included.
                Generate multiple unique examples of questions that make sense in context for the type "MULTI-SELECT".
                Output only valid JSON, with proper line spacing and indentation, without any additional formatting or code block delimiters.

                Topic: Questionnnaire for evaluation. Diverse.

                Context:
                {json_string_multi}
                """

prompt_single = f"""
                Using the context below as a template, create {singleVar} more JSON objects. The output should include only the keys "type",
                "question", and "options". Ensure the "type" is always "SINGLE-SELECT". The "options" array should contain multiple unique objects,
                each with the "option" key and a meaningful value representing an available choice. No IDs should be included.
                Generate multiple unique examples of questions that make sense in context for the type "SINGLE-SELECT".
                Output only valid JSON, with proper line spacing and indentation, without any additional formatting or code block delimiters.

                Topic: Questionnnaire for evaluation. Communications.

                Context:
                {json_string_single}
                """

prompt_text = f"""
                Using the context below as a template, create {textVar} more JSON objects. The output should include only the keys "type",
                "question", and "options". Ensure the "type" is always "TEXT", the "options" array always contains exactly one object with
                the "option" set to "Text", and no IDs are included. Generate multiple unique examples of questions that make sense in context
                for the type "TEXT". They should be open ended. Output only valid JSON, with proper line spacing and indentation, without any additional formatting or code block delimiters.

                Topic: Questionnnaire for evaluation. Communications. (General topic in the field of communications, not directly the word communications)

                Context:
                {json_string_text}
                """

prompt_number = f"""
                Using the context below as a template, create {numberVar} more JSON objects. The output should include only the keys "type",
                "question", and "options". Ensure the "type" is always "NUMBER", the "options" array always contains exactly one object with
                the "option" set to the category the question best, and no IDs are included. Generate multiple unique examples of questions that make sense in context
                for the type "NUMBER". Output only valid JSON, with proper line spacing and indentation, without any additional formatting or code block delimiters.

                Topic: Questionnnaire for evaluation. Convention/Fair.

                Context:
                {json_string_number}
                """

prompt_date = f"""
                Using the context below as a template, create {dateVar} more JSON objects. The output should include only the keys "type",
                "question", and "options". Ensure the "type" is always "DATE", the "options" array always contains exactly one object with
                the "option" set to "Date", and no IDs are included. Generate multiple unique examples of questions that make sense in context
                for the type "DATE". Make sure the question specifically ask for a date. Add "Provide a date." at the end of each question.
                Output only valid JSON, with proper line spacing and indentation, without any additional formatting or code block delimiters.

                Topic: Questionnnaire for evaluation. Healthcare.

                Context:
                {json_string_date}
                """


# responses
responses = {
    #"prompt_multi": "Questionnaire_Multi_Artificial.json",
    #"prompt_single": "Questionnaire_Single_Artificial.json",
    #"prompt_date": "Questionnaire_Date_Artificial.json",
    #"prompt_number": "Questionnaire_Number_Artificial.json",
    "prompt_text": "Questionnaire_Text_Artificial.json"
}

for response_name, response_file in responses.items():
    prompt = globals()[response_name]  # Get the prompt string
    response = model.generate_content(prompt)  # Get model's response

    try:
        response_data = json.loads(response.text)  # Parse the response text as JSON
    except json.JSONDecodeError as e:
        print(f"Error decoding JSON for {response_name}: {e}")
        continue

    # Write the parsed JSON to a file
    with open(response_file, "w") as json_file:
        json.dump(response_data, json_file, indent=4)

    print(f"JSON file '{response_file}' has been created")

JSON file 'Questionnaire_Text_Artificial.json' has been created

# JSON to Dataframe

### MULTI

In [ ]:
import json
import pandas as pd
import requests

#Load the JSON data
questions = [
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/main/artificial_questionnaire/MULTI/Questionnaire_Multi_Artificial_Diverse.json',
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/main/artificial_questionnaire/MULTI/Questionnaire_Multi_Artificial_HeavyIndustry.json',
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/main/artificial_questionnaire/MULTI/Questionnaire_Multi_Artificial_Sales.json',
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/main/artificial_questionnaire/MULTI/Questionnaire_Multi_Artificial_SoftwareDev.json'
]

dfs = []

for question in questions:
    response = requests.get(question)
    data = response.json()

    #Create a DataFrame from the JSON data
    df_temp = pd.DataFrame(data)
    df_temp['options'] = df_temp['options'].apply(lambda x: [item['option'] for item in x])
    dfs.append(df_temp)

df_MULTI = pd.concat(dfs, ignore_index=True)

df_for_csv = df_MULTI.copy()
df_for_csv['options'] = df_for_csv['options'].apply(lambda x: '; '.join(x))
df_for_csv.to_csv('MULTI_combined.csv', index=False)

df_MULTI

,type,question,options
0,MULTI_SELECT,Which social media platforms do you use for ma...,"[Facebook, Instagram, Twitter, LinkedIn, TikTo..."
1,MULTI-SELECT,What types of marketing content do you find mo...,"[Blog posts, Videos, Infographics, Case studie..."
2,MULTI-SELECT,What are your primary goals for this marketing...,"[Increase brand awareness, Generate leads, Dri..."
3,MULTI-SELECT,What are your preferred methods of customer co...,"[Email, Phone, Chat, Social media, In-person m..."
4,MULTI-SELECT,What challenges are you facing in your current...,"[Lack of budget, Lack of time, Lack of resourc..."
...,...,...,...
186,MULTI-SELECT,What types of software development tools have ...,"[Integrated Development Environments (IDEs), S..."
187,MULTI-SELECT,What types of communication protocols are you ...,"[HTTP, HTTPS, TCP/IP, UDP, REST, GraphQL]"
188,MULTI-SELECT,What types of design patterns have you impleme...,"[Creational patterns, Structural patterns, Beh..."
189,MULTI-SELECT,What are your preferred methods for maintainin...,"[Code reviews, Static analysis, Unit testing, ..."
190,MULTI-SELECT,What types of software development life cycle ...,"[Waterfall, Agile, Iterative, Spiral, V-model]"

###SINGLE

In [ ]:
import json
import pandas as pd
import requests

#Load the JSON data

questions = [
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/main/artificial_questionnaire/SINGLE/Questionnaire_Single_Artificial_ArtIndustry.json',
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/main/artificial_questionnaire/SINGLE/Questionnaire_Single_Artificial_Communications.json',
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/main/artificial_questionnaire/SINGLE/Questionnaire_Single_Artificial_Diverse.json',
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/main/artificial_questionnaire/SINGLE/Questionnaire_Single_Artificial_SoftwareDev.json'
]

dfs = []

for question in questions:
    response = requests.get(question)
    data = response.json()

    #Create a DataFrame from the JSON data

    df_temp = pd.DataFrame(data)
    df_temp['options'] = df_temp['options'].apply(lambda x: [item['option'] for item in x])
    dfs.append(df_temp)

df_SINGLE = pd.concat(dfs, ignore_index=True)

df_for_csv = df_SINGLE.copy()
df_for_csv['options'] = df_for_csv['options'].apply(lambda x: '; '.join(x))
df_for_csv.to_csv('SINGLE_combined.csv', index=False)

df_SINGLE

,type,question,options
0,SINGLE-SELECT,What is your preferred medium for artistic exp...,"[Painting, Sculpture, Digital Art, Photography..."
1,SINGLE-SELECT,What style of art are you most drawn to?,"[Abstract, Realism, Surrealism, Impressionism,..."
2,SINGLE-SELECT,What is your primary role in the art and desig...,"[Artist, Designer, Art Director, Graphic Desig..."
3,SINGLE-SELECT,What software do you primarily use for your work?,"[Adobe Photoshop, Adobe Illustrator, Adobe InD..."
4,SINGLE-SELECT,What is your preferred color palette?,"[Warm Colors, Cool Colors, Monochromatic, Anal..."
...,...,...,...
145,SINGLE-SELECT,What is your experience with data streaming te...,"[Beginner, Intermediate, Advanced]"
146,SINGLE-SELECT,What is your experience with big data technolo...,"[Beginner, Intermediate, Advanced]"
147,SINGLE-SELECT,What is your experience with artificial intell...,"[Beginner, Intermediate, Advanced]"
148,SINGLE-SELECT,What is your experience with blockchain techno...,"[Beginner, Intermediate, Advanced]"
149,SINGLE-SELECT,What is your experience with cybersecurity bes...,"[Beginner, Intermediate, Advanced]"

### NUMBER

In [ ]:
import json
import pandas as pd
import requests

#Load the JSON data

questions = [
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/dev_branch/artificial_questionnaire/NUMBER/Questionnaire_Number_Artificial_BusinessAndJob.json',
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/dev_branch/artificial_questionnaire/NUMBER/Questionnaire_Number_Artificial_HeavyIndustries.json',
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/dev_branch/artificial_questionnaire/NUMBER/Questionnaire_Number_Artificial_Diverse.json',
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/dev_branch/artificial_questionnaire/NUMBER/Questionnaire_Number_Artificial_Customer.json'
]

dfs = []

for question in questions:
    response = requests.get(question)
    data = response.json()

    #Create a DataFrame from the JSON data

    df_temp = pd.DataFrame(data)
    df_temp['options'] = df_temp['options'].apply(lambda x: [item['option'] for item in x])
    dfs.append(df_temp)
global df_NUMBER
df_NUMBER = pd.concat(dfs, ignore_index=True)

df_for_csv = df_NUMBER.copy()
df_for_csv['options'] = df_for_csv['options'].apply(lambda x: '; '.join(x))
df_for_csv.to_csv('NUMBER_combined.csv', index=False)

df_NUMBER

,type,question,options
0,NUMBER,What is your employee ID number?,[employee ID]
1,NUMBER,What is the project budget in dollars?,[budget]
2,NUMBER,How many employees are in the department?,[employee count]
3,NUMBER,What is the annual revenue target?,[revenue]
4,NUMBER,What is the client account number?,[account number]
...,...,...,...
180,NUMBER,What is your pant size?,[pant size]
181,NUMBER,How many times have you traveled internationally?,[international travels]
182,NUMBER,How many credit cards do you have?,[credit card count]
183,NUMBER,What is your estimated net worth?,[net worth]
184,NUMBER,How many years of education do you have?,[years of education]

### DATE

In [ ]:
import json
import pandas as pd
import requests

#Load the JSON data

questions = [
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/dev_branch/artificial_questionnaire/DATE/Questionnaire_Date_Artificial_Customer.json',
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/dev_branch/artificial_questionnaire/DATE/Questionnaire_Date_Artificial_HeavyIndustries.json',
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/dev_branch/artificial_questionnaire/DATE/Questionnaire_Date_Artificial_Technology.json',
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/dev_branch/artificial_questionnaire/DATE/Questionnaire_Date_Artificial_Healthcare.json'
]

dfs = []

for question in questions:
    response = requests.get(question)
    data = response.json()

    #Create a DataFrame from the JSON data

    df_temp = pd.DataFrame(data)
    df_temp['options'] = df_temp['options'].apply(lambda x: [item['option'] for item in x])
    dfs.append(df_temp)

df_DATE = pd.concat(dfs, ignore_index=True)

df_for_csv = df_DATE.copy()
df_for_csv['options'] = df_for_csv['options'].apply(lambda x: '; '.join(x))
df_for_csv.to_csv('DATE_combined.csv', index=False)

df_DATE

     type                                           question options
0    DATE        What is your date of birth? Provide a date.  [Date]
1    DATE  When did you purchase our product? Provide a d...  [Date]
2    DATE     What date did the issue begin? Provide a date.  [Date]
3    DATE     When is your next appointment? Provide a date.  [Date]
4    DATE         What is the delivery date? Provide a date.  [Date]
..    ...                                                ...     ...
183  DATE  When did you last consume alcohol? Provide a d...  [Date]
184  DATE  When was your last physical therapy appointmen...  [Date]
185  DATE  When did you last have a significant injury? P...  [Date]
186  DATE  When did you start experiencing shortness of b...  [Date]
187  DATE  When did you last see a mental health professi...  [Date]

[188 rows x 3 columns]

### TEXT

In [ ]:
import json
import pandas as pd
import requests

#Load the JSON data

questions = [
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/dev_branch/artificial_questionnaire/TEXT/Questionnaire_Text_Artificial_Communications.json',
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/dev_branch/artificial_questionnaire/TEXT/Questionnaire_Text_Artificial_HeavyIndustries.json',
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/dev_branch/artificial_questionnaire/TEXT/Questionnaire_Text_Artificial_CustomerSupport.json',
    'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/dev_branch/artificial_questionnaire/TEXT/Questionnaire_Text_Artificial_Convention.json'
]

dfs = []

for question in questions:
    response = requests.get(question)
    data = response.json()

    #Create a DataFrame from the JSON data

    df_temp = pd.DataFrame(data)
    df_temp['options'] = df_temp['options'].apply(lambda x: [item['option'] for item in x])
    dfs.append(df_temp)

df_TEXT = pd.concat(dfs, ignore_index=True)

df_for_csv = df_TEXT.copy()
df_for_csv['options'] = df_for_csv['options'].apply(lambda x: '; '.join(x))
df_for_csv.to_csv('TEXT_combined.csv', index=False)

df_TEXT

     type                                           question options
0    TEXT                          Describe your experience.  [Text]
1    TEXT                       What were the key takeaways?  [Text]
2    TEXT                             Explain your approach.  [Text]
3    TEXT                         Summarize the main points.  [Text]
4    TEXT                 What challenges did you encounter?  [Text]
..    ...                                                ...     ...
173  TEXT  Describe any areas where the convention fell s...  [Text]
174  TEXT  What aspects of the convention fostered a sens...  [Text]
175  TEXT  How effectively did the convention balance com...  [Text]
176  TEXT  What were the strengths and weaknesses of the ...  [Text]
177  TEXT  What is your feedback on the overall design an...  [Text]

[178 rows x 3 columns]

# Answer Generation

### MULTI

In [ ]:
import time
from google.api_core import exceptions

df_MULTI_with_answers = df_MULTI.iloc[100:190].copy()

# Generate a single compact prompt for all variations
def generate_minimal_prompt(row):
    return f"""Question: {row['question']}
            Options: {', '.join(row['options'])}

            Provide 5 different responses to this multiple choice question. Each response should select from the given options. Chose a different
            cobination of options (or single option) for each response. Each answer (V, C, Q, E, A) is to be given by a seperate person.
            Each label (V_Sel, C_Sel, Q_Sel, E_Sel, A_Sel) should contain the options corresponding to the response.
            Format exactly as follows:
            V: [verbose response, not exceeding 3 sentences]
            V_Sel: [options corresponding to the response V]
            C: [concise response]
            C_Sel: [options corresponding to the response C]
            Q: [colloquial response, no 'honestly']
            Q_Sel: [options corresponding to the response Q]
            E: [explanatory response, not exceeding 3 sentences]
            E_Sel: [options corresponding to the response E]
            A: [mildly annoyed response, no 'ugh']
            A_Sel: [options corresponding to the response A]"""

# Define the prefixes for each response type
prefixes = {
    'verbose': 'V:',
    'verbose_Gemini_label': 'V_Sel: ',
    'concise': 'C:',
    'concise_Gemini_label': 'C_Sel: ',
    'colloquial': 'Q:',
    'colloquial_Gemini_label': 'Q_Sel: ',
    'explanatory': 'E:',
    'explanatory_Gemini_label': 'E_Sel: ',
    'annoyed': 'A:',
    'annoyed_Gemini_label': 'A_Sel: '
}

# Parse the response text into separate variations
def parse_responses(text):
    answers = {}
    lines = text.split('\n')

    # Extract each response type
    for key, prefix in prefixes.items():
        try:
            # Find the line starting with this prefix
            response_line = next((line for line in lines if line.strip().startswith(prefix)), '')
            # Remove the prefix and trim
            response = response_line.replace(prefix, '', 1).strip()
            answers[f"answer_{key}"] = response if response else f"Error: No {key} response found"
        except Exception as e:
            answers[f"answer_{key}"] = f"Error parsing {key} response: {str(e)}"

    return answers

# Process a single row with retries
def process_row(row):
    prompt = generate_minimal_prompt(row)
    for attempt in range(3):
        try:
            response = model.generate_content(prompt)
            answers = parse_responses(response.text)
            time.sleep(3)
            return answers
        except exceptions.TooManyRequests:
            if attempt < 2:
                time.sleep(2 ** attempt)
            else:
                return {f"answer_{key}": "Error: Rate limit exceeded."
                       for key in prefixes}
        except Exception as e:
            print(f"Generated text was:\n{response.text}\n")
            print(f"Error: {str(e)}")
            return {f"answer_{key}": f"Error: {str(e)}"
                  for key in prefixes}

# Process the dataframe
answer_columns = df_MULTI_with_answers.apply(process_row, axis=1)

# Add columns to dataframe
for key in prefixes:
    df_MULTI_with_answers[f"answer_{key}"] = answer_columns.apply(lambda x: x[f"answer_{key}"])

# Save to CSV
df_for_csv_MULTI_answer = df_MULTI_with_answers.copy()
df_for_csv_MULTI_answer['options'] = df_for_csv_MULTI_answer['options'].apply(lambda x: '; '.join(x))
df_for_csv_MULTI_answer.to_csv('MULTI_answer_combined.csv', index=False, sep='>')

df_MULTI_with_answers

,type,question,options,answer_verbose,answer_verbose_Gemini_label,answer_concise,answer_concise_Gemini_label,answer_colloquial,answer_colloquial_Gemini_label,answer_explanatory,answer_explanatory_Gemini_label,answer_annoyed,answer_annoyed_Gemini_label
100,MULTI-SELECT,What are your current marketing and sales tech...,"[CRM (Salesforce, HubSpot, etc.), Marketing au...","We leverage a robust suite of technologies, in...","CRM (Salesforce, HubSpot, etc.), Marketing aut...","Salesforce, Google Analytics, and Mailchimp.","CRM (Salesforce, HubSpot, etc.), Analytics pla...","We use Salesforce, yeah? And some social medi...","CRM (Salesforce, HubSpot, etc.), Social media ...",Our sales team relies heavily on Salesforce fo...,"CRM (Salesforce, HubSpot, etc.), Marketing aut...","We're using Salesforce, but the reporting is a...","CRM (Salesforce, HubSpot, etc.), Social media ..."
101,MULTI-SELECT,What are your sales team's key performance ind...,"[Revenue generated, Number of deals closed, Av...",Our sales team's key performance indicators ar...,"Revenue generated, Number of deals closed, Ave...","Revenue, deals closed, and average deal size.","Revenue generated, Number of deals closed, Ave...",We totally look at how much dough we're bringi...,"Revenue generated, Number of deals closed, Ave...","To effectively measure sales performance, we u...","Revenue generated, Number of deals closed, Ave...","It's a combination of factors, obviously. We ...","Revenue generated, Number of deals closed, Cus..."
102,MULTI-SELECT,What are your company's key differentiators in...,"[Superior product quality, Lower prices, Excel...",Our company distinguishes itself through a com...,"Superior product quality, Excellent customer s...",Superior product quality and lower prices.,"Superior product quality, Lower prices","We totally rock at customer service, and our s...","Excellent customer service, Strong brand reput...",Our key differentiator is our innovative techn...,"Innovative technology, Strong brand reputation","It's a combination of things, really. Our bra...","Strong brand reputation, Superior product quality"
103,MULTI-SELECT,What are your top three priorities for improvi...,"[Improving lead generation, Increasing convers...","To boost sales, we need more qualified leads. ...","Improving lead generation, Increasing conversi...","Lead generation, conversion rates, and sales c...","Improving lead generation, Increasing conversi...","Gotta get more leads, man. Then, gotta close ...","Improving lead generation, Increasing conversi...",Our current sales process suffers from a lack ...,"Improving lead generation, Increasing conversi...","It's pretty obvious, isn't it? We need better ...","Improving lead generation, Increasing conversi..."
104,MULTI-SELECT,What types of content do you find most effecti...,"[Blog posts, Case studies, White papers, Webin...","For lead generation, I find a combination of c...","Case studies, Webinars, Ebooks, Blog posts",Case studies and webinars are most effective.,"Case studies, Webinars","Yo, gotta go with ebooks and infographics, the...","Ebooks, Infographics, Blog posts","While all options have merit, I've found that ...","White papers, Case studies","It depends on the audience, but if I had to pi...",Webinars
...,...,...,...,...,...,...,...,...,...,...,...,...,...
185,MULTI-SELECT,What are your preferred methods for code refac...,"[Extract Method, Rename Method, Move Method, E...",My preferred refactoring methods often involve...,"Extract Method, Rename Method, Move Method",Extract Method and Rename Method are my go-tos.,"Extract Method, Rename Method",I usually start by pulling out chunks of code ...,"Extract Method, Rename Method","For improved code clarity and maintainability,...","Extract Method, Rename Method","It depends on the problem, but often it's just...","Extract Method, Extract Class"
186,MULTI-SELECT,What types of software development tools have ...,"[Integrated Development Environments (IDEs), S...",I've extensively used Integrated Development E...,"IDEs, Source code management tools, Build tool...","IDEs, source control, and testing frameworks a...","IDEs, Source code management tools, Testing fr...","Yeah, I've messed around with IDEs, Git's pre...","IDEs, Source code management tools, Testing fr...",My software development experience includes th...,"IDEs, Source code management tools","I've worked with IDEs, of course. And build to...","IDEs, Build tools"
187,MULTI-SELECT,What types of communication protocols are you ...,"[HTTP, HTTPS, TCP/IP, UDP, REST, GraphQL]",I'm familiar with several communication protoc...,"HTTP, HTTPS, TCP/IP, REST, GraphQL","HTTP, HTTPS, TCP/IP, UDP, REST.","HTTP, HTTPS, TCP/IP, UDP, REST","I know about HTTP and HTTPS – they're like, th...","HTTP, HTTPS, TCP/IP, REST, GraphQL","My knowledge encompasses HTTP and HTTPS, used ...","HTTP, HTTPS, TCP/IP, UDP, REST, GraphQL","I'm aware of HTTP, HTTPS, and TCP/IP. Those a...","HTTP, HTTPS, TCP/IP, REST, UDP"
188,MULTI-SELECT,What types of design patterns have you impleme...,"[Creational patterns, Structural patterns, Beh...","In my projects, I've utilized a variety of des...","Creational patterns, Structural patterns, Beha...",Creational and behavioral patterns.,"Creational patterns, Behavioral patterns","Yeah, I've messed around with creational ones,...","Creational patterns, Structural patterns",My experience encompasses the implementation o...,"Creational patterns, Structural patterns","I've used all three, what else would you expect?","Creational patterns, Structural patterns, Beha..."
189,MULTI-SELECT,What are your preferred methods for maintainin...,"[Code reviews, Static analysis, Unit testing, ...",Code reviews are essential for catching logic ...,"Code reviews, Static analysis, Unit testing",Thorough unit testing and code reviews are key.,"Unit testing, Code reviews","Gotta have code reviews, man! And unit tests ...","Code reviews, Unit testing",Effective code quality maintenance relies on a...,"Code reviews, Static analysis, Unit testing, C...","It's a combination of things, obviously. Code...","Code reviews, Unit testing, Code style guidelines"

In [ ]:

df_MULTI_with_answers_total = df_MULTI_with_answers.copy()

# Save the complete dataset to a single CSV file
df_MULTI_with_answers_total.to_csv('MULTI_answer_combined_total.csv', index=False, sep='>')

import pandas as pd

# Convert options to strings before melting
df_MULTI_with_answers_total['options'] = df_MULTI_with_answers_total['options'].astype(str)

# Melt the dataframe to combine all answer columns into one column
df_long = df_MULTI_with_answers_total.melt(
    id_vars=["type", "question", "options"],
    var_name="answer_type",
    value_name="answer_value"
)

In [ ]:
import pandas as pd

# Step 1: Melt the dataframe to combine all answer columns into one column
df_long = df_MULTI_with_answers_total.melt(
    id_vars=["type", "question", "options"],
    var_name="answer_type",
    value_name="answer_value"
)

# Step 2: Create a new column for the answer type (e.g., verbose, concise, etc.)
df_long["answer_category"] = df_long["answer_type"].str.extract(r"answer_(\w+)")

# Step 3: Separate rows into answers and their labels
answers = df_long[~df_long["answer_type"].str.endswith("_Gemini_label")].copy()
labels = df_long[df_long["answer_type"].str.endswith("_Gemini_label")].copy()

# Step 4: Add a matching key column to facilitate merging
answers["label_type"] = answers["answer_type"] + "_Gemini_label"

# Step 5: Merge answers with their corresponding labels
df_reshaped = pd.merge(
    answers,
    labels,
    left_on=["type", "question", "options", "label_type"],
    right_on=["type", "question", "options", "answer_type"],
    suffixes=("", "_label")
)

# Step 6: Rename columns and keep the desired ones
df_reshaped = df_reshaped.rename(
    columns={"answer_value": "answer", "answer_value_label": "answer_label_GEMINI"}
)[["type", "question", "options", "answer", "answer_label_GEMINI", "answer_category"]]

# Step 7: Sort the data if needed
df_reshaped_MULTI = df_reshaped.sort_values(by=["type", "question"]).reset_index(drop=True)

# Display the final dataframe
df_reshaped_MULTI.to_csv('MULTI_answer_combined_total_reshaped.csv', index=False, sep='>')
df_reshaped_MULTI

,type,question,options,answer,answer_label_GEMINI,answer_category
0,MULTI-SELECT,What algorithms are you familiar with?,"['Sorting algorithms', 'Searching algorithms',...","I'm familiar with a wide range of algorithms, ...","[Sorting algorithms, Searching algorithms, Gra...",verbose
1,MULTI-SELECT,What algorithms are you familiar with?,"['Sorting algorithms', 'Searching algorithms',...","Sorting, searching, and graph algorithms.","[Sorting algorithms, Searching algorithms, Gra...",concise
2,MULTI-SELECT,What algorithms are you familiar with?,"['Sorting algorithms', 'Searching algorithms',...","Yeah, I know a bunch! Like, sorting stuff, fi...","[Sorting algorithms, Searching algorithms, Gra...",colloquial
3,MULTI-SELECT,What algorithms are you familiar with?,"['Sorting algorithms', 'Searching algorithms',...",My algorithmic knowledge encompasses fundament...,"[Sorting algorithms, Searching algorithms, Gra...",explanatory
4,MULTI-SELECT,What algorithms are you familiar with?,"['Sorting algorithms', 'Searching algorithms',...","I know sorting, searching, dynamic programming...","[Sorting algorithms, Searching algorithms, Dyn...",annoyed
...,...,...,...,...,...,...
445,MULTI_SELECT,What are your preferred methods for tracking s...,"['Sales dashboards', 'Sales reports', 'Sales m...",I find that regularly reviewing sales dashboar...,"Sales dashboards, Sales reports, One-on-one co...",verbose
446,MULTI_SELECT,What are your preferred methods for tracking s...,"['Sales dashboards', 'Sales reports', 'Sales m...",Sales dashboards and reports are key.,"Sales dashboards, Sales reports",concise
447,MULTI_SELECT,What are your preferred methods for tracking s...,"['Sales dashboards', 'Sales reports', 'Sales m...","Dashboards are great for a quick look, but I r...","Sales dashboards, Sales reports, Sales meetings",colloquial
448,MULTI_SELECT,What are your preferred methods for tracking s...,"['Sales dashboards', 'Sales reports', 'Sales m...","To effectively track sales performance, I rely...","Sales dashboards, Sales reports, Sales meetings",explanatory
449,MULTI_SELECT,What are your preferred methods for tracking s...,"['Sales dashboards', 'Sales reports', 'Sales m...",I need more than just meetings to track sales;...,"Sales reports, Sales dashboards, Team performa...",annoyed

### SINGLE

In [ ]:
import time
from google.api_core import exceptions

df_SINGLE_with_answers = df_SINGLE.iloc[101:150].copy()

def generate_minimal_prompt(row):
    return f"""Question: {row['question']}
            Options: {', '.join(row['options'])}
            Provide 5 different responses to this single choice question. Each response should select from the given options. Chose a different
            option for each response (if enough options exist for all 5 responses, otherwise repeat options after having already used all of them).
            Each answer (V, C, Q, E, A) is to be given by a seperate person.
            Each label (V_Sel, C_Sel, Q_Sel, E_Sel, A_Sel) should contain the option corresponding to the response. Format exactly as follows:
            V: [verbose response, not exceeding 3 sentences]
            V_Sel: [option corresponding to the response V]
            C: [concise response]
            C_Sel: [option corresponding to the response C]
            Q: [colloquial response, no 'honestly']
            Q_Sel: [option corresponding to the response Q]
            E: [explanatory response, not exceeding 3 sentences]
            E_Sel: [option corresponding to the response E]
            A: [mildly annoyed response, no 'ugh']
            A_Sel: [option corresponding to the response A]"""

# Define the prefixes for each response type
prefixes = {
    'verbose': 'V:',
    'verbose_Gemini_label': 'V_Sel: ',
    'concise': 'C:',
    'concise_Gemini_label': 'C_Sel: ',
    'colloquial': 'Q:',
    'colloquial_Gemini_label': 'Q_Sel: ',
    'explanatory': 'E:',
    'explanatory_Gemini_label': 'E_Sel: ',
    'annoyed': 'A:',
    'annoyed_Gemini_label': 'A_Sel: '
}

def parse_responses(text):
    answers = {}
    lines = text.split('\n')
    for key, prefix in prefixes.items():
        try:
            for line in lines:
                if line.startswith(prefix):
                    line = line.removeprefix(prefix)
                    answers[f"answer_{key}"] = line if line else f"Error: No {key} response found"
        except Exception as e:
                answers[f"answer_{key}"] = f"Error parsing {key} response: {str(e)}"

    return answers

def process_row(row):
    prompt = generate_minimal_prompt(row)
    for attempt in range(3):
        try:
            response = model.generate_content(prompt)
            answers = parse_responses(response.text)
            time.sleep(3)
            return answers
        except exceptions.TooManyRequests:
            if attempt < 2:
                time.sleep(2 ** attempt)
            else:
                return {f"answer_{key}": "Error: Rate limit exceeded."
                       for key in prefixes}
        except Exception as e:
            print(f"Generated text was:\n{response.text}\n")
            print(f"Error: {str(e)}")
            return {f"answer_{key}": f"Error: {str(e)}"
                  for key in prefixes}

answer_columns = df_SINGLE_with_answers.apply(process_row, axis=1)

# Add columns to dataframe
for key in prefixes:
    df_SINGLE_with_answers[f"answer_{key}"] = answer_columns.apply(lambda x: x[f"answer_{key}"])

df_for_csv_SINGLE_answer = df_SINGLE_with_answers.copy()
df_for_csv_SINGLE_answer['options'] = df_for_csv_SINGLE_answer['options'].apply(lambda x: '; '.join(x))
df_for_csv_SINGLE_answer.to_csv('SINGLE_answer_combined.csv', index=False, sep='>')

df_SINGLE_with_answers

,type,question,options,answer_verbose,answer_verbose_Gemini_label,answer_concise,answer_concise_Gemini_label,answer_colloquial,answer_colloquial_Gemini_label,answer_explanatory,answer_explanatory_Gemini_label,answer_annoyed,answer_annoyed_Gemini_label
101,SINGLE-SELECT,What is your primary source of leads?,"[Inbound Marketing, Outbound Sales, Referrals,...",Our primary source of leads comes from inboun...,Inbound Marketing,Referrals.,Referrals,"Partnerships, dude. That's where it's at.",Partnerships,Our outbound sales team is our main lead gene...,Outbound Sales,It's clearly inbound marketing. We've inves...,Inbound Marketing
102,SINGLE-SELECT,What is your company's mission?,"[Profit Maximization, Social Impact, Environme...",Our company strives to create a positive impa...,Social Impact,Customer satisfaction is our top priority.,Customer Satisfaction,It's all about makin' sure our customers are...,Customer Satisfaction,Our mission is to protect and improve the env...,Environmental Sustainability,The question should be obvious. It's about ...,Profit Maximization
103,SINGLE-SELECT,What is your company culture?,"[Formal, Informal, Hybrid]",We maintain a professional atmosphere with cl...,Hybrid,Formal.,Formal,"It's pretty chill, not too uptight.",Informal,Our company culture is a hybrid approach. We...,Hybrid,"It depends on who you ask, but I'd say it lea...",Informal
104,SINGLE-SELECT,What is your preferred integration method?,"[API, CSV Import/Export, Other]","For seamless and real-time data exchange, an...",API,API.,API,"Gotta go with CSV import/export, it's just e...",CSV Import/Export,"While several methods exist, I find CSV impo...",CSV Import/Export,"Fine, if I have to choose, I suppose API is ...",API
105,SINGLE-SELECT,What is your current level of digital transfor...,"[Beginner, Intermediate, Advanced]",We're still in the early stages of adopting n...,Beginner,Beginner.,Beginner,"We're just dipping our toes in the water, ma...",Beginner,Our digital transformation is currently at a ...,Beginner,We're just starting out with this. It's a s...,Beginner
106,SINGLE-SELECT,What are your top three priorities for this year?,"[Revenue Growth, Cost Reduction, Customer Acqu...",Our top priority is boosting revenue growth ...,Revenue Growth,Cost Reduction is key.,Cost Reduction,"Gotta get more customers, that's the name of ...",Customer Acquisition,Product development is paramount. A successfu...,Product Development,"If I had to pick just one, it would be reven...",Revenue Growth
107,SINGLE-SELECT,What is your biggest challenge in your current...,"[Lack of Resources, Lack of Time, Lack of Supp...",My biggest challenge is the lack of resources...,Lack of Resources,Lack of time.,Lack of Time,"It's gotta be the lack of support, man. Nev...",Lack of Support,My primary challenge is the lack of support f...,Lack of Support,The constant pressure to deliver with insuff...,Lack of Resources
108,SINGLE-SELECT,What is your team size?,"[1-5, 6-10, 11-20, 20+]","We're a small but mighty team! Currently, th...",1-5,1-5.,1-5,"Just a handful of us, you know?",1-5,My team consists of between eleven and twent...,11-20,The team size? It's between six and ten peo...,6-10
109,SINGLE-SELECT,What is your company's main focus?,"[B2B, B2C, Both]",Our company primarily focuses on business-to-...,B2B,B2B.,B2B,We're all about the business-to-business thin...,B2B,"Our main focus is a balanced approach, servin...",Both,It's B2C. Is that clear enough?,B2C
110,SINGLE-SELECT,How would you rate your experience with our cu...,"[Excellent, Good, Fair, Poor]",The customer support representative was incre...,Excellent,Good service.,Good,"It was alright, I guess. Could've been better...",Fair,"My problem was resolved, though it took a bit...",Good,"It wasn't the worst experience, but it certai...",Poor
111,SINGLE-SELECT,What is your preferred programming language?,"[Python, Java, JavaScript, C++, C#]",I find Python to be my preferred language fo...,Python,Java.,Java,"Gotta go with JavaScript, it's everywhere, m...",JavaScript,C++ is my preferred language because of its p...,C++,"I suppose C# will do, if I *must* choose one.",C#
112,SINGLE-SELECT,What is your experience level with software de...,"[Beginner, Intermediate, Advanced, Expert]","I'm still learning the ropes, but I'm activel...",Beginner,Beginner.,Beginner,"I'm kinda new to this whole coding thing, you...",Beginner,I possess a foundational understanding of sof...,Intermediate,"I've done some coding, but I wouldn't consid...",Intermediate
113,SINGLE-SELECT,What type of software development are you inte...,"[Web Development, Mobile Development, Game Dev...",I'm fascinated by the challenges of creating ...,Web Development,Mobile Development.,Mobile Development,"Game dev, dude. Making games is way cooler t...",Game Development,I find embedded systems programming to be par...,Embedded Systems,Data science. It's what I'm currently focuse...,Data Science
114,SINGLE-SELECT,What is your preferred development environment?,"[Visual Studio, IntelliJ IDEA, Eclipse, VS Cod...",I find Visual Studio to be the most robust an...,Visual Studio,IntelliJ IDEA.,IntelliJ IDEA,"VS Code's pretty sweet, man. Lots of extens...",VS Code,Eclipse provides a powerful and flexible plat...,Eclipse,"Sublime Text is fine, I suppose. It's light...",Sublime Text
115,SINGLE-SELECT,What version control system do you use?,"[Git, SVN, Mercurial]",We primarily utilize Git for version control ...,Git,Git.,Git,"We use Git, yeah? It's pretty standard.",Git,Our team has chosen to use Mercurial for vers...,Mercurial,It's SVN. Next question.,SVN
116,SINGLE-SELECT,What database system are you familiar with?,"[MySQL, PostgreSQL, MongoDB, Oracle, SQL Server]",I have experience working with MySQL database...,MySQL,PostgreSQL.,PostgreSQL,"MongoDB's pretty cool, I've messed around wit...",MongoDB,I'm proficient in Oracle Database. My expert...,Oracle,I know SQL Server. It's what we used at my ...,SQL Server
117,SINGLE-SELECT,What methodology do you follow for software de...,"[Agile, Waterfall, Scrum, Kanban]","We utilize an Agile methodology, emphasizing ...",Agile,Waterfall.,Waterfall,"We're all about Scrum, man. Short sprints, d...",Scrum,Our software development process adheres to ...,Kanban,It's Agile. Next question?,Agile
118,SINGLE-SELECT,What is your preferred testing framework?,"[JUnit, pytest, NUnit, Mocha, Jest]","For comprehensive Java projects, JUnit's matu...",JUnit,pytest.,pytest,"I really like Jest, it's super easy to use, ...",Jest,"NUnit's features, such as parameterized test...",NUnit,"Mocha is fine, I guess, if you're stuck in t...",Mocha
119,SINGLE-SELECT,What type of project are you working on?,"[Web Application, Mobile Application, Desktop ...",I'm currently developing a web application de...,Web Application,Building a mobile app.,Mobile Application,"I'm makin' a game, dude. It's gonna be epic!",Game,My project is a desktop application focused o...,Desktop Application,"It's a library, fine. Are we done now?",Library
120,SINGLE-SELECT,What is your team size?,"[1-5, 6-10, 11-20, 21-50, More than 50]","We're a small but mighty team! Currently, we...",1-5,1-5,1-5,"Just a handful of us, like, five people tops.",1-5,"Our team consists of 12 individuals, encompas...",11-20,It's between 21 and 50. Why do you need to ...,21-50
121,SINGLE-SELECT,What is your role in the team?,"[Frontend Developer, Backend Developer, Fullst...",I'm the frontend developer on this team. My ...,Frontend Developer,Backend Developer.,Backend Developer,"I'm the full-stack guy, so I do a bit of ever...",Fullstack Developer,"As the data scientist on the project, I focus...",Data Scientist,"I manage the project. It's a lot of work, le...",Project Manager
122,SINGLE-SELECT,What cloud platform do you use?,"[AWS, Azure, Google Cloud]",We primarily leverage Amazon Web Services for...,AWS,AWS.,AWS,"We're all about Google Cloud, dude. It's th...",Google Cloud,Our organization utilizes Google Cloud Platfo...,Google Cloud,"The question is Azure. Next time, be more s...",Azure
123,SINGLE-SELECT,What is your preferred IDE for mobile developm...,"[Android Studio, Xcode, React Native, Flutter]",I find Android Studio to be the most robust a...,Android Studio,Xcode.,Xcode,"React Native's pretty sweet, it's all I use,...",React Native,Flutter provides a fantastic developer experi...,Flutter,"I suppose if I *had* to choose, it would be ...",Android Studio
124,SINGLE-SELECT,Are you familiar with DevOps practices?,"[Yes, No]","Yes, I am familiar with DevOps practices. My...",Yes,Yes,Yes,"Yeah, I know about that DevOps stuff.",Yes,"Yes, I have a working understanding of DevOps...",Yes,"Yes, of course I am. Is that all you wanted ...",Yes
125,SINGLE-SELECT,What is your experience with Agile methodologies?,"[Beginner, Intermediate, Advanced]",I've recently started learning about Agile me...,Beginner,Beginner.,Beginner,"Yeah, I'm just getting started with the Agil...",Beginner,I possess a foundational understanding of Agi...,Intermediate,I have significant experience with Agile. T...,Advanced
126,SINGLE-SELECT,What is your preferred code editor for front-e...,"[VS Code, Sublime Text, Atom, WebStorm]",I find VS Code to be the most versatile and f...,VS Code,WebStorm.,WebStorm,"I'm all about Sublime Text, it's super snapp...",Sublime Text,Atom is my preferred editor because of its op...,Atom,"I suppose VS Code is alright, I guess. It's...",VS Code
127,SINGLE-SELECT,What is your preferred framework for backend d...,"[Spring Boot, Node.js, Django, Ruby on Rails, ...",Spring Boot offers a robust and mature ecosys...,Spring Boot,"Django. Clean, efficient, and Pythonic.",Django,"Node.js is pretty sweet, man. Fast and scal...",Node.js,I prefer .NET for its strong typing and exce...,.NET,"Ruby on Rails. It gets the job done, I supp...",Ruby on Rails
128,SINGLE-SELECT,What is your experience with design patterns?,"[Beginner, Intermediate, Advanced]",I've recently started learning about design p...,Beginner,Beginner.,Beginner,I'm just dipping my toes in the design patte...,Beginner,My experience with design patterns is current...,Intermediate,"I've worked with them quite a bit, so I'm pre...",Advanced
129,SINGLE-SELECT,What type of testing do you prefer?,"[Unit Testing, Integration Testing, End-to-End...",I find unit testing most preferable. It allo...,Unit Testing,End-to-End testing.,End-to-End Testing,"I'm all about UI testing, gotta make sure it...",UI Testing,Integration testing is my preferred method be...,Integration Testing,"Fine, I suppose unit testing is the least ba...",Unit Testing
130,SINGLE-SELECT,What is your preferred approach to software ar...,"[Microservices, Monolithic, Layered]","For a project of this scale and complexity, a...",Microservices,Layered architecture.,Layered,"Dude, microservices are the way to go, espec...",Microservices,A monolithic architecture is suitable for sma...,Monolithic,It depends entirely on the project requireme...,Layered
131,SINGLE-SELECT,What is your experience with containerization ...,"[Beginner, Intermediate, Advanced]",I've just started learning about Docker and c...,Beginner,Beginner.,Beginner,"I've messed around with Docker a bit, you kn...",Beginner,My experience with containerization technolog...,Intermediate,"I've used Docker and Kubernetes, so I'm not ...",Intermediate
132,SINGLE-SELECT,What is your experience with CI/CD pipelines?,"[Beginner, Intermediate, Advanced]",I've recently started learning about CI/CD pi...,Beginner,Beginner.,Beginner,I'm just dipping my toes into the CI/CD worl...,Beginner,My experience with CI/CD pipelines is current...,Intermediate,"I've worked with CI/CD, but it's not my area ...",Intermediate
133,SINGLE-SELECT,What is your preferred approach to project man...,"[Agile, Waterfall, Hybrid]",I find Agile's iterative approach best suits...,Agile,Waterfall. Structured and predictable.,Waterfall,"Gotta go with Agile, man. Keeps things movi...",Agile,A hybrid approach often works best. We use W...,Hybrid,"It depends on the project, but if I had to c...",Agile
134,SINGLE-SELECT,What is your preferred communication tool?,"[Slack, Microsoft Teams, Email, Jira]",I find Slack to be the most efficient communi...,Slack,Microsoft Teams.,Microsoft Teams,"Email's alright, I guess, but it's a bit slow...",Microsoft Teams,I prefer email for formal communication and ...,Email,This is a ridiculous question. Jira is clea...,Email
135,SINGLE-SELECT,What is your preferred collaboration tool?,"[GitHub, GitLab, Bitbucket]",I find GitHub's extensive community support a...,GitHub,Bitbucket.,Bitbucket,"GitLab's kinda cool, especially the CI/CD stu...",GitLab,I prefer GitLab because it offers a complete...,GitLab,"I suppose GitHub is alright, I've just used ...",GitHub
136,SINGLE-SELECT,What is your preferred method for code review?,"[Pull Requests, Code walkthroughs, Pair progra...",I find pull requests to be the most efficient...,Pull Requests,Pair programming.,Pair programming,"Code walkthroughs are the way to go, man. G...",Code walkthroughs,I prefer code walkthroughs because they facil...,Code walkthroughs,Pull requests are the least disruptive to my...,Pull Requests
137,SINGLE-SELECT,What is your experience with RESTful APIs?,"[Beginner, Intermediate, Advanced]",I've worked with RESTful APIs on a few projec...,Beginner,Beginner.,Beginner,"I've messed around with a few APIs, pretty ...",Beginner,My experience with RESTful APIs is foundation...,Intermediate,I've done some intermediate level work with R...,Intermediate
138,SINGLE-SELECT,What is your experience with GraphQL APIs?,"[Beginner, Intermediate, Advanced]","I've worked with GraphQL in a few projects, p...",Intermediate,Beginner.,Beginner,"I've messed around with GraphQL a bit, you k...",Beginner,My experience with GraphQL APIs is limited to...,Beginner,I've only just started using GraphQL. It's ...,Beginner
139,SINGLE-SELECT,What is your experience with microservices arc...,"[Beginner, Intermediate, Advanced]",I've recently started exploring microservices...,Beginner,Beginner.,Beginner,I'm kinda new to the whole microservices thi...,Beginner,I possess a foundational understanding of mic...,Intermediate,I've worked with microservices extensively. ...,Advanced
140,SINGLE-SELECT,What is your experience with serverless comput...,"[Beginner, Intermediate, Advanced]",I've just started exploring serverless archit...,Beginner,Beginner.,Beginner,I'm pretty new to this whole serverless thing...,Beginner,My experience with serverless computing is cu...,Beginner,I've only just begun to work with serverless ...,Beginner
141,SINGLE-SELECT,What is your experience with event-driven arch...,"[Beginner, Intermediate, Advanced]",I've recently started learning about event-dr...,Beginner,Beginner.,Beginner,"Yeah, I've just dipped my toes in with event...",Beginner,I possess a foundational understanding of eve...,Intermediate,I have a solid grasp of event-driven archite...,Advanced
142,SINGLE-SELECT,What is your experience with message queues?,"[Beginner, Intermediate, Advanced]",I've just started learning about message queu...,Beginner,Beginner.,Beginner,I'm kinda new to this whole message queue th...,Beginner,My experience with message queues is limited ...,Intermediate,"I've worked with message queues before, but i...",Intermediate
143,SINGLE-SELECT,What is your experience with caching mechanisms?,"[Beginner, Intermediate, Advanced]",I've just started learning about caching mech...,Beginner,Beginner.,Beginner,"Caching? Yeah, I've heard of it, but I'm s...",Beginner,My experience with caching mechanisms is inte...,Intermediate,I've worked extensively with caching; it's a...,Advanced
144,SINGLE-SELECT,What is your experience with NoSQL databases?,"[Beginner, Intermediate, Advanced]",I've just started learning about NoSQL databa...,Beginner,Beginner.,Beginner,"I've messed around with a bit of MongoDB, so ...",Beginner,My experience with NoSQL databases is limited...,Intermediate,I've worked extensively with various NoSQL da...,Advanced
145,SINGLE-SELECT,What is your experience with data streaming te...,"[Beginner, Intermediate, Advanced]",I've recently started exploring data streamin...,Beginner,Beginner.,Beginner,I'm kinda new to the whole data streaming th...,Beginner,My experience with data streaming technologie...,Intermediate,I have extensive experience with various data...,Advanced
146,SINGLE-SELECT,What is your experience with big data technolo...,"[Beginner, Intermediate, Advanced]",I've recently started learning about big data...,Beginner,Beginner.,Beginner,I'm just dipping my toes into the big data p...,Beginner,My experience with big data technologies is c...,Intermediate,I have some familiarity with the fundamentals...,Intermediate
147,SINGLE-SELECT,What is your experience with artificial intell...,"[Beginner, Intermediate, Advanced]",I've just started learning about AI and machi...,Beginner,Beginner.,Beginner,"I'm just dipping my toes in the AI/ML water,...",Beginner,My experience with AI and machine learning is...,Intermediate,"I've worked with some AI and ML, but I wouldn...",Intermediate
148,SINGLE-SELECT,What is your experience with blockchain techno...,"[Beginner, Intermediate, Advanced]",I've just started learning about blockchain t...,Beginner,Beginner.,Beginner,I'm pretty new to this whole blockchain thin...,Beginner,My experience with blockchain is limited to t...,Intermediate,"I have a basic grasp of the fundamentals, but...",Intermediate
149,SINGLE-SELECT,What is your experience with cybersecurity bes...,"[Beginner, Intermediate, Advanced]",I'm still learning about cybersecurity best p...,Beginner,Beginner.,Beginner,I'm kinda new to this whole cybersecurity thi...,Beginner,My experience with cybersecurity best practic...,Intermediate,I have a pretty good grasp of cybersecurity ...,Advanced

In [ ]:

df_SINGLE_with_answers_total = df_SINGLE_with_answers.copy()

# Save the complete dataset to a single CSV file
df_SINGLE_with_answers_total.to_csv('SINGLE_answer_combined_total.csv', index=False, sep='>')

import pandas as pd

# Convert options to strings before melting
df_SINGLE_with_answers_total['options'] = df_SINGLE_with_answers_total['options'].astype(str)

 Melt the dataframe to combine all answer columns into one column
df_long = df_SINGLE_with_answers_total.melt(
    id_vars=["type", "question", "options"],
    var_name="answer_type",
    value_name="answer_value"
)

In [ ]:
import pandas as pd

# Step 1: Melt the dataframe to combine all answer columns into one column
df_long = df_SINGLE_with_answers_total.melt(
    id_vars=["type", "question", "options"],
    var_name="answer_type",
    value_name="answer_value"
)

# Step 2: Create a new column for the answer type (e.g., verbose, concise, etc.)
df_long["answer_category"] = df_long["answer_type"].str.extract(r"answer_(\w+)")

# Step 3: Separate rows into answers and their labels
answers = df_long[~df_long["answer_type"].str.endswith("_Gemini_label")].copy()
labels = df_long[df_long["answer_type"].str.endswith("_Gemini_label")].copy()

# Step 4: Add a matching key column to facilitate merging
answers["label_type"] = answers["answer_type"] + "_Gemini_label"

# Step 5: Merge answers with their corresponding labels
df_reshaped = pd.merge(
    answers,
    labels,
    left_on=["type", "question", "options", "label_type"],
    right_on=["type", "question", "options", "answer_type"],
    suffixes=("", "_label")
)

# Step 6: Rename columns and keep the desired ones
df_reshaped = df_reshaped.rename(
    columns={"answer_value": "answer", "answer_value_label": "answer_label_GEMINI"}
)[["type", "question", "options", "answer", "answer_label_GEMINI", "answer_category"]]

# Step 7: Sort the data if needed
df_reshaped_SINGLE = df_reshaped.sort_values(by=["type", "question"]).reset_index(drop=True)

# Display the final dataframe
df_reshaped_SINGLE.to_csv('SINGLE_answer_combined_total_reshaped.csv', index=False, sep='>')
df_reshaped_SINGLE

,type,question,options,answer,answer_label_GEMINI,answer_category
0,SINGLE-SELECT,Are you familiar with DevOps practices?,"['Yes', 'No']","Yes, I am familiar with DevOps practices. My...",Yes,verbose
1,SINGLE-SELECT,Are you familiar with DevOps practices?,"['Yes', 'No']",Yes,Yes,concise
2,SINGLE-SELECT,Are you familiar with DevOps practices?,"['Yes', 'No']","Yeah, I know about that DevOps stuff.",Yes,colloquial
3,SINGLE-SELECT,Are you familiar with DevOps practices?,"['Yes', 'No']","Yes, I have a working understanding of DevOps...",Yes,explanatory
4,SINGLE-SELECT,Are you familiar with DevOps practices?,"['Yes', 'No']","Yes, of course I am. Is that all you wanted ...",Yes,annoyed
...,...,...,...,...,...,...
240,SINGLE-SELECT,What version control system do you use?,"['Git', 'SVN', 'Mercurial']",We primarily utilize Git for version control ...,Git,verbose
241,SINGLE-SELECT,What version control system do you use?,"['Git', 'SVN', 'Mercurial']",Git.,Git,concise
242,SINGLE-SELECT,What version control system do you use?,"['Git', 'SVN', 'Mercurial']","We use Git, yeah? It's pretty standard.",Git,colloquial
243,SINGLE-SELECT,What version control system do you use?,"['Git', 'SVN', 'Mercurial']",Our team has chosen to use Mercurial for vers...,Mercurial,explanatory
244,SINGLE-SELECT,What version control system do you use?,"['Git', 'SVN', 'Mercurial']",It's SVN. Next question.,SVN,annoyed

### NUMBER

In [ ]:
import time
from google.api_core import exceptions

df_NUMBER_with_answers = df_NUMBER.copy()

def generate_minimal_prompt(row):
    return f"""Question: {row['question']}
            Options: {row['options']}
            Provide 5 different responses to this single choice question, which asks for a number. The question provides a single option defining the type of number to be chosen.
            Each response should adhere to the given type but provide a unique answer. Some answers should be written as numbers, some such that the numbers are spelled out.
            Each answer (V, C, Q, E, A) is to be given by a separate person.
            Each label (V_Sel, C_Sel, Q_Sel, E_Sel, A_Sel) should contain just the number (with correct units) corresponding to the response. Format exactly as follows:
            V: [verbose response, not exceeding 3 sentences]
            V_Sel: [number corresponding to the response V]
            C: [concise response]
            C_Sel: [number corresponding to the response C]
            Q: [colloquial response, no 'honestly']
            Q_Sel: [number corresponding to the response Q]
            E: [explanatory response, not exceeding 3 sentences]
            E_Sel: [number corresponding to the response E]
            A: [mildly annoyed response, no 'ugh']
            A_Sel: [number corresponding to the response A]"""

# Define the prefixes for each response type
prefixes = {
    'verbose': 'V:',
    'verbose_Gemini_label': 'V_Sel:',
    'concise': 'C:',
    'concise_Gemini_label': 'C_Sel:',
    'colloquial': 'Q:',
    'colloquial_Gemini_label': 'Q_Sel:',
    'explanatory': 'E:',
    'explanatory_Gemini_label': 'E_Sel:',
    'annoyed': 'A:',
    'annoyed_Gemini_label': 'A_Sel:'
}

def parse_responses(text):
    answers = {}
    lines = text.split('\n')

    # Initialize all expected keys with default values
    for key in prefixes.keys():
        answers[f"answer_{key}"] = "No response"

    # Try to find each response type in the text
    for key, prefix in prefixes.items():
        try:
            matching_lines = [line.strip() for line in lines if line.strip().startswith(prefix)]
            if matching_lines:
                # Remove prefix and clean up the response
                response = matching_lines[0].replace(prefix, '', 1).strip()
                answers[f"answer_{key}"] = response
        except Exception as e:
            print(f"Error parsing {key}: {str(e)}")
            # Keep the default "No response" value

    return answers

def process_row(row):
    prompt = generate_minimal_prompt(row)
    max_retries = 3

    for attempt in range(max_retries):
        try:
            response = model.generate_content(prompt)
            answers = parse_responses(response.text)
            time.sleep(3)  # Rate limiting
            return answers
        except exceptions.TooManyRequests:
            if attempt < max_retries - 1:
                time.sleep(2 ** attempt)  # Exponential backoff
            else:
                return {f"answer_{key}": "Rate limit exceeded" for key in prefixes.keys()}
        except Exception as e:
            print(f"Error processing row: {str(e)}")
            return {f"answer_{key}": f"Error: {str(e)}" for key in prefixes.keys()}

# Process the dataframe
answer_columns = df_NUMBER_with_answers.apply(process_row, axis=1)

# Add columns to dataframe
for key in prefixes.keys():
    df_NUMBER_with_answers[f"answer_{key}"] = answer_columns.apply(lambda x: x.get(f"answer_{key}", "No response"))

# Save to CSV
df_for_csv_NUMBER_answer = df_NUMBER_with_answers.copy()
df_for_csv_NUMBER_answer['options'] = df_for_csv_NUMBER_answer['options'].apply(lambda x: '; '.join(x) if isinstance(x, list) else str(x))
df_for_csv_NUMBER_answer.to_csv('NUMBER_answer_combined.csv', index=False, sep='>')

df_NUMBER_with_answers

,type,question,options,answer_verbose,answer_verbose_Gemini_label,answer_concise,answer_concise_Gemini_label,answer_colloquial,answer_colloquial_Gemini_label,answer_explanatory,answer_explanatory_Gemini_label,answer_annoyed,answer_annoyed_Gemini_label
0,NUMBER,What is your employee ID number?,[employee ID],"My employee ID number is three million, four h...",3456789,1234567,1234567,"It's like, 8765432, you know? That's my emplo...",8765432,My employee identification number is 9876543. ...,9876543,My employee ID is 5012345. I already told you...,5012345
1,NUMBER,What is the project budget in dollars?,[budget],"The project budget is a substantial sum, total...","$1,250,000","$500,000","$500,000","The budget? It's about three hundred grand, I...","$300,000","The allocated budget for this project is $750,...","$750,000",The budget is two million dollars. I've alrea...,"$2,000,000"
2,NUMBER,How many employees are in the department?,[employee count],There are thirty-seven employees currently wor...,37 employees,12,12 employees,"There's like, twenty-five people, give or take...",25 employees,The department's employee count is currently a...,50 employees,The number of employees is eighty-two. I've a...,82 employees
3,NUMBER,What is the annual revenue target?,[revenue],"Based on our projections and market analysis, ...","$1,000,000","$5,500,000","$5,500,000","We're shooting for five million bucks, that's ...","$5,000,000",The annual revenue target has been set at thre...,"$3,500,000",The target is two million dollars. Is there a...,"$2,000,000"
4,NUMBER,What is the client account number?,[account number],"The client's account number, as requested, is ...",3142005,1234567890,1234567890,"It's 987654321, dude. That's their account nu...",987654321,The account number you requested is 555-1212. ...,5551212,The account number is 24680. I've already tol...,24680
...,...,...,...,...,...,...,...,...,...,...,...,...,...
180,NUMBER,What is your pant size?,[pant size],"My pant size is thirty-two. It's a bit snug, ...",32,34,34,"I'm wearin' a 30, but they're a little tight.",30,My current pant size is 36. This is based on r...,36,It's 28. Why do you need to know?,28
181,NUMBER,How many times have you traveled internationally?,[international travels],I've had the pleasure of traveling internation...,5 international travels,Three.,3 international travels,"Like, maybe seven times? Could be more, I los...",7 international travels,I have undertaken four international trips. Th...,4 international travels,Two. Is that what you needed to know?,2 international travels
182,NUMBER,How many credit cards do you have?,[credit card count],I currently have three credit cards. Two are ...,3 credit cards,Two.,2 credit cards,"Just the two, mate.",2 credit cards,I maintain a total of five credit cards for va...,5 credit cards,"One, and that's enough for me, thanks.",1 credit card
183,NUMBER,What is your estimated net worth?,[net worth],My estimated net worth is a complex calculatio...,$0,"$1,234,567","$1,234,567","Like, zero, man. Nada. Zilch.",$0,"As a large language model, I don't possess ass...",$0,That's a rather personal question. My net wor...,"$1,000,000"
184,NUMBER,How many years of education do you have?,[years of education],I have completed sixteen years of formal educa...,16 years,12,12 years,"Twelve years, man. That's high school and a b...",12 years,I have a total of eighteen years of education....,18 years,Seventeen. Is that what you really need to know?,17 years

In [ ]:
import pandas as pd

# Convert options to strings before melting
df_NUMBER_with_answers['options'] = df_NUMBER_with_answers['options'].astype(str)

# Step 1: Melt the dataframe to combine all answer columns into one column
df_long = df_NUMBER_with_answers.melt(
    id_vars=["type", "question", "options"],
    var_name="answer_type",
    value_name="answer_value"
)


# Step 2: Create a new column for the answer type (e.g., verbose, concise, etc.)
df_long["answer_category"] = df_long["answer_type"].str.extract(r"answer_(\w+)")

# Step 3: Separate rows into answers and their labels
answers = df_long[~df_long["answer_type"].str.endswith("_Gemini_label")].copy()
labels = df_long[df_long["answer_type"].str.endswith("_Gemini_label")].copy()

# Step 4: Add a matching key column to facilitate merging
answers["label_type"] = answers["answer_type"] + "_Gemini_label"

# Step 5: Merge answers with their corresponding labels
df_reshaped = pd.merge(
    answers,
    labels,
    left_on=["type", "question", "options", "label_type"],
    right_on=["type", "question", "options", "answer_type"],
    suffixes=("", "_label")
)

# Step 6: Rename columns
df_reshaped = df_reshaped.rename(
    columns={"answer_value": "answer", "answer_value_label": "answer_label_GEMINI"}
)[["type", "question", "options", "answer", "answer_label_GEMINI", "answer_category"]]

# Step 7: Sort the data if needed
df_reshaped_NUMBER = df_reshaped.sort_values(by=["type", "question"]).reset_index(drop=True)

# Display the final dataframe
df_reshaped_NUMBER.to_csv('NUMBER_answer_combined_total_reshaped.csv', index=False, sep='>')
df_reshaped_NUMBER

,type,question,options,answer,answer_label_GEMINI,answer_category
0,NUMBER,How many attendees are expected at the confere...,['attendee count'],We anticipate a significant turnout at the con...,500 attendees,verbose
1,NUMBER,How many attendees are expected at the confere...,['attendee count'],1200,1200 attendees,concise
2,NUMBER,How many attendees are expected at the confere...,['attendee count'],I'm guessing around two thousand people will b...,2000 attendees,colloquial
3,NUMBER,How many attendees are expected at the confere...,['attendee count'],The expected attendee count is based on a comb...,750 attendees,explanatory
4,NUMBER,How many attendees are expected at the confere...,['attendee count'],The number of expected attendees is three hund...,300 attendees,annoyed
...,...,...,...,...,...,...
930,NUMBER,What year was the company founded?,['year'],The company's founding year is documented in o...,1987,verbose
931,NUMBER,What year was the company founded?,['year'],1995,1995,concise
932,NUMBER,What year was the company founded?,['year'],"It started up way back in nineteen ninety-two,...",1992,colloquial
933,NUMBER,What year was the company founded?,['year'],The company's inception date can be found in o...,2003,explanatory
934,NUMBER,What year was the company founded?,['year'],The year the company was founded? It's 2011. ...,2011,annoyed

### DATE

In [ ]:
import time
from google.api_core import exceptions

df_DATE_with_answers = df_DATE.copy()

def generate_minimal_prompt(row):
    return f"""Question: {row['question']}
            Options: {row['options']}
            Provide 5 different responses to this single choice question, which asks for a date. The question provides one option defining the type to be chosen.
            Each response should adhere to the given type but provide a unique answer. Some answers should be written as numbers, some such that the numbers are spelled out. Use different date formats.
            Assume question takers are from Europe.
            Each answer (V, C, Q, E, A) is to be given by a separate person.
            Each label (V_Sel, C_Sel, Q_Sel, E_Sel, A_Sel) should contain just the date corresponding to the response. Use this date format: dd-mm-yyyy and nothing else for the label.
            Format exactly as follows:
            V: [verbose response, not exceeding 3 sentences]
            V_Sel: [date corresponding to the response V]
            C: [concise response]
            C_Sel: [date corresponding to the response C]
            Q: [colloquial response, no 'honestly']
            Q_Sel: [date corresponding to the response Q]
            E: [explanatory response, not exceeding 3 sentences]
            E_Sel: [date corresponding to the response E]
            A: [mildly annoyed response, no 'ugh']
            A_Sel: [date corresponding to the response A]"""

# Define the prefixes for each response type
prefixes = {
    'verbose': 'V:',
    'verbose_Gemini_label': 'V_Sel: ',
    'concise': 'C:',
    'concise_Gemini_label': 'C_Sel: ',
    'colloquial': 'Q:',
    'colloquial_Gemini_label': 'Q_Sel: ',
    'explanatory': 'E:',
    'explanatory_Gemini_label': 'E_Sel: ',
    'annoyed': 'A:',
    'annoyed_Gemini_label': 'A_Sel: '
}

def parse_responses(text):
    answers = {}
    lines = text.split('\n')
    for key, prefix in prefixes.items():
        try:
            for line in lines:
                if line.startswith(prefix):
                    line = line.removeprefix(prefix)
                    answers[f"answer_{key}"] = line if line else f"Error: No {key} response found"
        except Exception as e:
                answers[f"answer_{key}"] = f"Error parsing {key} response: {str(e)}"

    return answers

def process_row(row):
    prompt = generate_minimal_prompt(row)
    for attempt in range(3):
        try:
            response = model.generate_content(prompt)
            answers = parse_responses(response.text)
            time.sleep(3)
            return answers
        except exceptions.TooManyRequests:
            if attempt < 2:
                time.sleep(2 ** attempt)
            else:
                return {f"answer_{key}": "Error: Rate limit exceeded."
                       for key in prefixes}
        except Exception as e:
            print(f"Generated text was:\n{response.text}\n")
            print(f"Error: {str(e)}")
            return {f"answer_{key}": f"Error: {str(e)}"
                  for key in prefixes}

answer_columns = df_DATE_with_answers.apply(process_row, axis=1)

for key in prefixes:
    df_DATE_with_answers[f"answer_{key}"] = answer_columns.apply(lambda x: x[f"answer_{key}"])

df_for_csv_DATE_answer = df_DATE_with_answers.copy()
df_for_csv_DATE_answer['options'] = df_for_csv_DATE_answer['options'].apply(lambda x: '; '.join(x))
df_for_csv_DATE_answer.to_csv('DATE_answer_combined.csv', index=False, sep='>')

df_DATE_with_answers

,type,question,options,answer_verbose,answer_verbose_Gemini_label,answer_concise,answer_concise_Gemini_label,answer_colloquial,answer_colloquial_Gemini_label,answer_explanatory,answer_explanatory_Gemini_label,answer_annoyed,answer_annoyed_Gemini_label
0,DATE,What is your date of birth? Provide a date.,[Date],My birthday is on the twenty-fifth of October...,25-10-1987,14/03/1992,14-03-1992,"It's the sixth of June, nineteen ninety-five...",06-06-1995,"My date of birth is the 1st of January, 2001....",01-01-2001,"It's the twelfth of August, two thousand and...",12-08-2004
1,DATE,When did you purchase our product? Provide a d...,[Date],I purchased your product on the twenty-fifth ...,25-08-2022,14/03/2023,14-03-2023,"Got it sometime in April last year, mate. C...",15-04-2022,My purchase was made on the tenth of January ...,10-01-2021,It was 02/11/2020. I have the receipt some...,02-11-2020
2,DATE,What date did the issue begin? Provide a date.,[Date],The problem started on the twenty-fifth of Ma...,25-03-2023,01/04/2024,01-04-2024,"It all kicked off on the tenth of June, last...",10-06-2022,The issue commenced on 15 August 2021. This ...,15-08-2021,"The date was the fifteenth of November, two ...",15-11-2022
3,DATE,When is your next appointment? Provide a date.,[Date],My next appointment is scheduled for the twen...,27-10-2024,14/03/2025,14-03-2025,"Next appt? See ya 22nd December, twenty-twe...",22-12-2023,"My next appointment is on the fifth of June, ...",05-06-2025,"It's on the first of January, next year. Is ...",01-01-2024
4,DATE,What is the delivery date? Provide a date.,[Date],The package will arrive on the twenty-fifth o...,25-10-2024,12/03/2025,12-03-2025,"It'll be here on the seventh of next month, ...",07-11-2024,"Delivery is scheduled for the 18th of June, 2...",18-06-2023,The delivery date is 01-01-2025. Is there a...,01-01-2025
...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,DATE,When did you last consume alcohol? Provide a d...,[Date],I last had an alcoholic beverage on the twent...,27-10-2022,14/03/2023,14-03-2023,"Ages ago, mate. Think it was sometime in Ap...",15-04-2023,My last alcoholic consumption was on the 31s...,31-12-2022,"I've already told you - it was July twelfth,...",12-07-2023
184,DATE,When was your last physical therapy appointmen...,[Date],My last physical therapy appointment was on t...,27-10-2022,14/03/2023,14-03-2023,"Last physio? Oh, it was ages ago, mate. Th...",05-06-2023,My last physical therapy appointment was on t...,01-01-2024,It was two weeks ago. August twenty-first. ...,21-08-2024
185,DATE,When did you last have a significant injury? P...,[Date],My last significant injury was a nasty ankle ...,15-07-2022,24/10/2021,24-10-2021,"Oh, man, that time I fell off my bike? Smash...",18-08-2020,I fractured my collarbone in a cycling accide...,29-05-2019,"It was back in two thousand and fifteen, on...",12-11-2015
186,DATE,When did you start experiencing shortness of b...,[Date],I first noticed I was having trouble catching...,05-07-2023,24/10/2022,24-10-2022,"Oh, it started, like, around Christmas time...",20-12-2022,The shortness of breath began progressively w...,21-03-2023,It was the twenty-seventh of August. I reme...,27-08-2023
187,DATE,When did you last see a mental health professi...,[Date],"It was quite some time ago, I believe my last...",15-08-2022,27/10/2021,27-10-2021,"Ages ago, mate. Think it was sometime in Ap...",12-04-2020,I saw a psychiatrist for a check-up. The date...,23-03-2023,I last saw someone in September of twenty-tw...,29-09-2021

In [ ]:
import pandas as pd

# Convert options to strings before melting
df_DATE_with_answers['options'] = df_DATE_with_answers['options'].astype(str)

# Step 1: Melt the dataframe to combine all answer columns into one column
df_long = df_DATE_with_answers.melt(
    id_vars=["type", "question", "options"],
    var_name="answer_type",
    value_name="answer_value"
)


# Step 2: Create a new column for the answer type (e.g., verbose, concise, etc.)
df_long["answer_category"] = df_long["answer_type"].str.extract(r"answer_(\w+)")

# Step 3: Separate rows into answers and their labels
answers = df_long[~df_long["answer_type"].str.endswith("_Gemini_label")].copy()
labels = df_long[df_long["answer_type"].str.endswith("_Gemini_label")].copy()

# Step 4: Add a matching key column to facilitate merging
answers["label_type"] = answers["answer_type"] + "_Gemini_label"

# Step 5: Merge answers with their corresponding labels
df_reshaped = pd.merge(
    answers,
    labels,
    left_on=["type", "question", "options", "label_type"],
    right_on=["type", "question", "options", "answer_type"],
    suffixes=("", "_label")
)

# Step 6: Rename columns
df_reshaped = df_reshaped.rename(
    columns={"answer_value": "answer", "answer_value_label": "answer_label_GEMINI"}
)[["type", "question", "options", "answer", "answer_label_GEMINI", "answer_category"]]

# Step 7: Sort the data if needed
df_reshaped_DATE = df_reshaped.sort_values(by=["type", "question"]).reset_index(drop=True)

# Display the final dataframe
df_reshaped_DATE.to_csv('DATE_answer_combined_total_reshaped.csv', index=False, sep='>')
df_reshaped_DATE

,type,question,options,answer,answer_label_GEMINI,answer_category
0,DATE,On what date did the project officially commen...,['Date'],The project officially began on the twenty-th...,23-03-2022,verbose
1,DATE,On what date did the project officially commen...,['Date'],01/01/2023,01-01-2023,concise
2,DATE,On what date did the project officially commen...,['Date'],"It kicked off on the fifteenth of August, tw...",15-08-2024,colloquial
3,DATE,On what date did the project officially commen...,['Date'],"The official start date of the project, as re...",12-06-2021,explanatory
4,DATE,On what date did the project officially commen...,['Date'],"The project started on September tenth, two t...",10-09-2020,annoyed
...,...,...,...,...,...,...
955,DATE,When will the product be ready for pickup? Pro...,['Date'],Your product will be ready for collection on ...,25-10-2024,verbose
956,DATE,When will the product be ready for pickup? Pro...,['Date'],27/12/2023,27-12-2023,concise
957,DATE,When will the product be ready for pickup? Pro...,['Date'],It'll be ready to pick up on the 14th of Feb...,14-02-2024,colloquial
958,DATE,When will the product be ready for pickup? Pro...,['Date'],The product will be available for pickup on M...,08-03-2025,explanatory
959,DATE,When will the product be ready for pickup? Pro...,['Date'],It's ready for pickup on the fifth of Januar...,05-01-2024,annoyed

### TEXT

In [ ]:
import time
from google.api_core import exceptions

df_TEXT_with_answers = df_TEXT.copy()

def generate_minimal_prompt(row):
    return f"""Question: {row['question']}
            Options: {row['options']}
            Provide 5 different responses to this single choice question, which asks for a text. The question provides a single option defining the type of answer to be chosen.
            Each response should adhere to the given type but provide a unique answer. The questions are open ended, therefore your answer should replicate a human's answer to such a question.
            Each answer (V, C, Q, E, A) is to be given by a separate person.
            Each label (V_Sel, C_Sel, Q_Sel, E_Sel, A_Sel) should contain the shortest possible topic summary.
            Format exactly as follows:
            V: [verbose response, not exceeding 3 sentences]
            V_Sel: [summary corresponding to the response V]
            C: [concise response]
            C_Sel: [summary corresponding to the response C]
            Q: [colloquial response, no 'honestly']
            Q_Sel: [summary corresponding to the response Q]
            E: [explanatory response, not exceeding 3 sentences]
            E_Sel: [summary corresponding to the response E]
            A: [mildly annoyed response, no 'ugh']
            A_Sel: [summary corresponding to the response A]"""

# Define the prefixes for each response type
prefixes = {
    'verbose': 'V:',
    'verbose_Gemini_label': 'V_Sel:',
    'concise': 'C:',
    'concise_Gemini_label': 'C_Sel:',
    'colloquial': 'Q:',
    'colloquial_Gemini_label': 'Q_Sel:',
    'explanatory': 'E:',
    'explanatory_Gemini_label': 'E_Sel:',
    'annoyed': 'A:',
    'annoyed_Gemini_label': 'A_Sel:'
}

def parse_responses(text):
    answers = {}
    lines = text.split('\n')

    # Initialize all expected keys with default values
    for key in prefixes.keys():
        answers[f"answer_{key}"] = "No response"

    # Try to find each response type in the text
    for key, prefix in prefixes.items():
        try:
            # Find lines that start with the exact prefix
            matching_lines = [line.strip() for line in lines if line.strip().startswith(prefix)]
            if matching_lines:
                response = matching_lines[0].replace(prefix, '', 1).strip()
                answers[f"answer_{key}"] = response
        except Exception as e:
            print(f"Error parsing {key}: {str(e)}")


    return answers

def process_row(row):
    prompt = generate_minimal_prompt(row)
    max_retries = 3

    for attempt in range(max_retries):
        try:
            response = model.generate_content(prompt)
            answers = parse_responses(response.text)
            time.sleep(3)  # Rate limiting
            return answers
        except exceptions.TooManyRequests:
            if attempt < max_retries - 1:
                time.sleep(2 ** attempt)  # Exponential backoff
            else:
                return {f"answer_{key}": "Rate limit exceeded" for key in prefixes.keys()}
        except Exception as e:
            print(f"Error processing row: {str(e)}")
            print(f"Generated text was:\n{response.text}\n")
            return {f"answer_{key}": f"Error: {str(e)}" for key in prefixes.keys()}

# Process the dataframe
answer_columns = df_TEXT_with_answers.apply(process_row, axis=1)

# Add columns to dataframe with error handling
for key in prefixes.keys():
    df_TEXT_with_answers[f"answer_{key}"] = answer_columns.apply(
        lambda x: x.get(f"answer_{key}", "No response") if isinstance(x, dict) else "Error in processing"
    )

# Save to CSV
df_for_csv_TEXT_answer = df_TEXT_with_answers.copy()
df_for_csv_TEXT_answer['options'] = df_for_csv_TEXT_answer['options'].apply(
    lambda x: '; '.join(x) if isinstance(x, list) else str(x)
)
df_for_csv_TEXT_answer.to_csv('TEXT_answer_combined.csv', index=False, sep='>')

df_TEXT_with_answers

,type,question,options,answer_verbose,answer_verbose_Gemini_label,answer_concise,answer_concise_Gemini_label,answer_colloquial,answer_colloquial_Gemini_label,answer_explanatory,answer_explanatory_Gemini_label,answer_annoyed,answer_annoyed_Gemini_label
0,TEXT,Describe your experience.,[Text],My experience has been a multifaceted journey ...,Life journey of growth and challenges,A lot of ups and downs.,Mixed experiences,"It's been a wild ride, man! Lots of stuff hap...",Varied and exciting life,My experience is characterized by a continuous...,Continuous learning and adaptation,That's a pretty broad question. What kind of ...,Needs more specific question
1,TEXT,What were the key takeaways?,[Text],The key takeaways were the significant impact ...,"Climate change, sustainable agriculture, renew...","Climate change, sustainability, renewable energy.",Key environmental issues,"So, basically, climate change is a big deal, w...",Environmental urgency & technological advancem...,The presentation primarily focused on three ke...,"Environmental, economic & social impacts","The main points were climate change, the need ...",Obvious environmental themes
2,TEXT,Explain your approach.,[Text],My approach was to systematically consider eac...,Systematic problem-solving,Logical and methodical breakdown of the problem.,Methodical approach,"I just kinda figured it out, ya know? Tried a...",Trial and error,I began by defining the problem and its constr...,Problem definition & solution evaluation,"Well, I had to think about it for a bit, and i...",Considered several options
3,TEXT,Summarize the main points.,[Text],The main points were the increasing cost of li...,"Cost of living, impact on businesses, governme...","Rising costs, struggling businesses, governmen...",Economic hardship and government reaction,"Okay, so like, prices are up, small shops are ...",Economic problems and government attempts at s...,The summary centers on three key areas: the sh...,"Economic hardship, business impact, government...","The main points are obvious: inflation, strugg...","Inflation, business struggles, inadequate gove..."
4,TEXT,What challenges did you encounter?,[Text],The biggest challenge was definitely integrati...,API integration difficulties,Insufficient documentation and buggy API.,Doc & API issues,"Man, the whole thing was a nightmare. Getting...",Data integration problems,We faced several hurdles during development. P...,Software incompatibility,It was frustrating. The lack of clear specifi...,Poor specifications
...,...,...,...,...,...,...,...,...,...,...,...,...,...
173,TEXT,Describe any areas where the convention fell s...,[Text],The networking opportunities were significantl...,Poor networking & attendance,Lack of promised speakers and underwhelming ne...,Poor speakers & networking,"Man, the whole thing was a bit of a letdown. ...",Disappointing speakers & bad food,The convention fell short in several key areas...,Overcrowded workshops & inadequate venue,The promised keynote speakers were a major dis...,Poor speakers & technical issues
174,TEXT,What aspects of the convention fostered a sens...,[Text],"The convention's diverse programming, featurin...",Diverse programming & accessibility,Accessible facilities and diverse representation.,Accessibility & diversity,"So, like, they had stuff for everyone, ya know...",Inclusive atmosphere & varied events,The convention actively sought to create an in...,Accessibility & diverse representation,"Well, they *tried*, I guess. The accessibilit...","Adequate accessibility & diversity, but room f..."
175,TEXT,How effectively did the convention balance com...,[Text],The convention demonstrated a moderate ability...,"Moderate success, some compromises, unresolved...",Partially successful.,Partial success,"Eh, it was okay, I guess. Some things got sor...","Mixed results, some success, some failure",The convention's effectiveness in balancing co...,"Mixed results, concessions made, room for impr...",It was a struggle to say the least. They clea...,"Poor prioritization, uneven outcomes."
176,TEXT,What were the strengths and weaknesses of the ...,[Text],The convention's communication strategy effect...,"Social media success, on-site failures","Strong social media presence, weak on-site inf...",Social media vs. on-site,"They were all over social media, which was coo...","Good social, bad in-person",Their pre-convention publicity campaign was a ...,"Pre-event strong, event weak","The social media campaign was fine, I guess. B...","Poor organization, good social media"
177,TEXT,What is your feedback on the overall design an...,[Text],The convention's layout was generally well-org...,"Good layout, but scheduling issues","Excellent layout, well-organized.",Positive layout,"It was alright, pretty easy to get around, but...","Easy navigation, but small rooms",The spatial arrangement of the convention cent...,"Efficient layout, some congestion","The floor plan was confusing in places, and fi...","Confusing layout, hard to navigate"

In [ ]:
import pandas as pd

# Convert options to strings before melting
df_TEXT_with_answers['options'] = df_TEXT_with_answers['options'].astype(str)

# Step 1: Melt the dataframe to combine all answer columns into one column
df_long = df_TEXT_with_answers.melt(
    id_vars=["type", "question", "options"],
    var_name="answer_type",
    value_name="answer_value"
)


# Step 2: Create a new column for the answer type (e.g., verbose, concise, etc.)
df_long["answer_category"] = df_long["answer_type"].str.extract(r"answer_(\w+)")

# Step 3: Separate rows into answers and their labels
answers = df_long[~df_long["answer_type"].str.endswith("_Gemini_label")].copy()
labels = df_long[df_long["answer_type"].str.endswith("_Gemini_label")].copy()

# Step 4: Add a matching key column to facilitate merging
answers["label_type"] = answers["answer_type"] + "_Gemini_label"

# Step 5: Merge answers with their corresponding labels
df_reshaped = pd.merge(
    answers,
    labels,
    left_on=["type", "question", "options", "label_type"],
    right_on=["type", "question", "options", "answer_type"],
    suffixes=("", "_label")
)

# Step 6: Rename columns
df_reshaped = df_reshaped.rename(
    columns={"answer_value": "answer", "answer_value_label": "answer_label_GEMINI"}
)[["type", "question", "options", "answer", "answer_label_GEMINI", "answer_category"]]

# Step 7: Sort the data if needed
df_reshaped_TEXT = df_reshaped.sort_values(by=["type", "question"]).reset_index(drop=True)

# Display the final dataframe
df_reshaped_TEXT.to_csv('TEXT_answer_combined_total_reshaped.csv', index=False, sep='>')
df_reshaped_TEXT

,type,question,options,answer,answer_label_GEMINI,answer_category
0,TEXT,Describe any areas where cost savings could be...,['Text'],Significant cost savings could be achieved by ...,"Supplier renegotiation, energy efficiency, pro...",verbose
1,TEXT,Describe any areas where cost savings could be...,['Text'],"Reduce supplier costs, improve energy efficien...",Cost reduction strategies,concise
2,TEXT,Describe any areas where cost savings could be...,['Text'],"Dude, we could totally save a ton of cash by h...",Haggling & energy saving,colloquial
3,TEXT,Describe any areas where cost savings could be...,['Text'],Cost savings can be realized through a multi-p...,Contract audit & automation,explanatory
4,TEXT,Describe any areas where cost savings could be...,['Text'],"Well, it's pretty obvious, isn't it? We need ...",Spending review & expense reduction,annoyed
...,...,...,...,...,...,...
895,TEXT,Would you recommend our support to others? Why...,['Text'],"Yes, I would absolutely recommend your support...","Positive experience, highly recommends",verbose
896,TEXT,Would you recommend our support to others? Why...,['Text'],Yes. Excellent support.,Concise positive recommendation,concise
897,TEXT,Would you recommend our support to others? Why...,['Text'],"Yeah, for sure! They were super helpful and so...",Casual positive feedback,colloquial
898,TEXT,Would you recommend our support to others? Why...,['Text'],I would recommend your support based on my pos...,Positive experience due to knowledge and effic...,explanatory
899,TEXT,Would you recommend our support to others? Why...,['Text'],"Yes, but only because they finally fixed it af...",Reluctant recommendation due to initial diffic...,annoyed

# Merge all CSV Files

In [ ]:
import glob

# list all csv files only
csv_files = ['TEXT_answer_combined_total_reshaped.csv', 'DATE_answer_combined_total_reshaped.csv', 'NUMBER_answer_combined_total_reshaped.csv', 'SINGLE_answer_combined_total_reshaped.csv', 'MULTI_answer_combined_total_reshaped.csv']

import pandas as pd

# Create an empty list to store each DataFrame
dfs = []

# Read each CSV file and append to the list
for file in csv_files:
    df = pd.read_csv(file, sep='>')
    dfs.append(df)

# Concatenate all DataFrames
merged_df = pd.concat(dfs, ignore_index=True)

# Save the merged DataFrame to a new CSV
merged_df.to_csv('all_answers_combined_reshaped.csv', index=False, sep='>')

In [ ]:
df_all = pd.read_csv('all_answers_combined_reshaped.csv', sep='>')
df_all

,type,question,options,answer,answer_label_GEMINI,answer_category
0,TEXT,Describe any areas where cost savings could be...,['Text'],Significant cost savings could be achieved by ...,"Supplier renegotiation, energy efficiency, pro...",verbose
1,TEXT,Describe any areas where cost savings could be...,['Text'],"Reduce supplier costs, improve energy efficien...",Cost reduction strategies,concise
2,TEXT,Describe any areas where cost savings could be...,['Text'],"Dude, we could totally save a ton of cash by h...",Haggling & energy saving,colloquial
3,TEXT,Describe any areas where cost savings could be...,['Text'],Cost savings can be realized through a multi-p...,Contract audit & automation,explanatory
4,TEXT,Describe any areas where cost savings could be...,['Text'],"Well, it's pretty obvious, isn't it? We need ...",Spending review & expense reduction,annoyed
...,...,...,...,...,...,...
3485,MULTI_SELECT,What are your preferred methods for tracking s...,"['Sales dashboards', 'Sales reports', 'Sales m...",I find that regularly reviewing sales dashboar...,"Sales dashboards, Sales reports, One-on-one co...",verbose
3486,MULTI_SELECT,What are your preferred methods for tracking s...,"['Sales dashboards', 'Sales reports', 'Sales m...",Sales dashboards and reports are key.,"Sales dashboards, Sales reports",concise
3487,MULTI_SELECT,What are your preferred methods for tracking s...,"['Sales dashboards', 'Sales reports', 'Sales m...","Dashboards are great for a quick look, but I r...","Sales dashboards, Sales reports, Sales meetings",colloquial
3488,MULTI_SELECT,What are your preferred methods for tracking s...,"['Sales dashboards', 'Sales reports', 'Sales m...","To effectively track sales performance, I rely...","Sales dashboards, Sales reports, Sales meetings",explanatory
3489,MULTI_SELECT,What are your preferred methods for tracking s...,"['Sales dashboards', 'Sales reports', 'Sales m...",I need more than just meetings to track sales;...,"Sales reports, Sales dashboards, Team performa...",annoyed

In [ ]:
df_all['options'] = df_all['options'].str.replace(r"\['|'\]", "", regex=True)

In [ ]:
df_all.to_csv('all_answers_combined_reshaped.csv', index=False, sep='>')

# Clean Up CSV

In [ ]:
# Remove all rows containing quotation marks

import csv
import requests

def clean_csv_from_github(url, output_file):
    """
    Reads a CSV file from a GitHub raw URL, removes rows containing quotation marks,
    and saves the cleaned data to a new CSV file.

    Parameters:
        url (str): The GitHub raw URL of the CSV file.
        output_file (str): The file path to save the cleaned CSV.
    """
    try:
        # Fetch the CSV content from the GitHub raw URL
        response = requests.get(url)
        response.raise_for_status()

        # Decode the content and split into lines
        csv_content = response.text
        csv_lines = csv_content.splitlines()

        # Read the CSV into memory
        reader = csv.reader(csv_lines, delimiter='>')
        cleaned_rows = []

        for row in reader:
            # Remove rows containing quotation marks
            if not any('"' in field for field in row):
                corrected_row = [field.replace('MULTI_SELECT', 'MULTI-SELECT').replace('SINGLE_SELECT', 'SINGLE-SELECT') for field in row]
                cleaned_rows.append(corrected_row)



        # Write the cleaned rows to a new CSV file
        with open(output_file, 'w', encoding='utf-8', newline='') as outfile:
            writer = csv.writer(outfile, delimiter='>')
            writer.writerows(cleaned_rows)

        print(f"Cleaned CSV saved to {output_file}")

    except requests.exceptions.RequestException as e:
        print(f"Error fetching the CSV file: {e}")
    except Exception as e:
        print(f"An error occurred: {e}")

url = 'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/dev_branch/artificial_answers/all_answers_combined_reshaped.csv'
output_file = 'cleaned_all_answers_combined_reshaped_type_adjusted.csv'
clean_csv_from_github(url, output_file)

Cleaned CSV saved to cleaned_all_answers_combined_reshaped_type_adjusted.csv

# Adding Additional Labels

### MULTI AND SINGLE

In [3]:
# Install required packages
!pip install transformers
!pip install torch
!pip install datasets
!pip install evaluate
!pip install sentencepiece

# Now import the required libraries
import pandas as pd
from transformers import pipeline
from sklearn.model_selection import train_test_split
import torch
import numpy as np
from datasets import Dataset
import evaluate

# Initialize the zero-shot classification pipeline
classifier = pipeline("zero-shot-classification", model="facebook/bart-large-mnli")


def load_csv_method1(url):
    df = pd.read_csv(url, sep='>', names=['type', 'question', 'options', 'answer', 'answer_label_GEMINI', 'answer_category'], converters={'options': lambda x: x.split(';')})
    return df

url = 'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/dev_branch/artificial_answers/cleaned_all_answers_combined_reshaped_type_adjusted.csv'
df_full = load_csv_method1(url)

df_MULTI_full = df_full[df_full['type'] == 'MULTI-SELECT']
df_MULTI = df_MULTI_full.copy()

df_SINGLE_full = df_full[df_full['type'] == 'SINGLE-SELECT']
df_SINGLE = df_SINGLE_full.copy()

print(df_MULTI)

# Process MULTI-SELECT in batches with exception handling
def classify_multi(df):
    answers = df["answer"].tolist()
    options = df["options"].tolist()

    results = []
    for answer, option in zip(answers, options):
        try:
            result = classifier(answer, candidate_labels=option, multi_label=True)
            # Filter labels with scores > 0.5
            filtered = [label for label, score in zip(result["labels"], result["scores"]) if score > 0.5]
        except Exception as e:
            print(f"Error classifying row with answer='{answer}' and options='{option}': {e}")
            filtered = []  # Return an empty list for rows with errors
        results.append(filtered)

    return results


# Process SINGLE-SELECT in batches with exception handling
def classify_single(df):
    answers = df["answer"].tolist()
    options = df["options"].tolist()

    results = []
    for answer, option in zip(answers, options):
        try:
            result = classifier(answer, candidate_labels=option, multi_label=False)
            selected_label = result["labels"][0]
        except Exception as e:
            print(f"Error classifying row with answer='{answer}' and options='{option}': {e}")
            selected_label = None  # Return None for rows with errors
        results.append(selected_label)

    return results

# Apply the classification to each row

df_MULTI["answer_label_BART_large_mnli"] = classify_multi(df_MULTI)
df_SINGLE["answer_label_BART_large_mnli"] = classify_single(df_SINGLE)

# Display the DataFrame
print(df_MULTI)
print(df_SINGLE)

# drop all rows where type == MULTI-SELECT
df_full = df_full.drop(df_full[df_full['type'] == 'MULTI-SELECT'].index)
df_full = df_full.drop(df_full[df_full['type'] == 'SINGLE-SELECT'].index)

# append df_MULTI and df_SINGLE to df_full
df_full = pd.concat([df_full, df_MULTI, df_SINGLE])
df_full = df_full.sort_index()

df_full.to_csv('all_answers_combined_reshaped_with_BART_large_mnli_MULTI_SINGLE_labels.csv', index=False, sep='>')

Requirement already satisfied: transformers in /usr/local/lib/python3.11/dist-packages (4.47.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from transformers) (3.17.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.27.1)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.11/dist-packages (from transformers) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.11/dist-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in /usr/local/lib/python3.11/dist-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in /usr/local/lib/python3.11/dist-packages (from transformers) (0.5.2)
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.11/dist-packages (from transformers) (4.67.1)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (2024.9.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests->transformers) (2024.12.14)
Requirement already satisfied: torch in /usr/local/lib/python3.11/dist-packages (2.5.1+cu121)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from torch) (3.17.0)
Requirement already satisfied: typing-extensions>=4.8.0 in /usr/local/lib/python3.11/dist-packages (from torch) (4.12.2)
Requirement already satisfied: networkx in /usr/local/lib/python3.11/dist-packages (from torch) (3.4.2)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.5)
Requirement already satisfied: fsspec in /usr/local/lib/python3.11/dist-packages (from torch) (2024.9.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch) (12.1.105)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70 in /usr/local/lib/python3.11/dist-packages (from torch) (9.1.0.70)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1 in /usr/local/lib/python3.11/dist-packages (from torch) (12.1.3.1)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54 in /usr/local/lib/python3.11/dist-packages (from torch) (11.0.2.54)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106 in /usr/local/lib/python3.11/dist-packages (from torch) (10.3.2.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107 in /usr/local/lib/python3.11/dist-packages (from torch) (11.4.5.107)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106 in /usr/local/lib/python3.11/dist-packages (from torch) (12.1.0.106)
Requirement already satisfied: nvidia-nccl-cu12==2.21.5 in /usr/local/lib/python3.11/dist-packages (from torch) (2.21.5)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105 in /usr/local/lib/python3.11/dist-packages (from torch) (12.1.105)
Requirement already satisfied: triton==3.1.0 in /usr/local/lib/python3.11/dist-packages (from torch) (3.1.0)
Requirement already satisfied: sympy==1.13.1 in /usr/local/lib/python3.11/dist-packages (from torch) (1.13.1)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /usr/local/lib/python3.11/dist-packages (from nvidia-cusolver-cu12==11.4.5.107->torch) (12.8.61)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.11/dist-packages (from sympy==1.13.1->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.11/dist-packages (from jinja2->torch) (3.0.2)
Requirement already satisfied: datasets in /usr/local/lib/python3.11/dist-packages (3.2.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets) (3.17.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (1.26.4)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (17.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from datasets) (2.2.2)
Requirement already satisfied: requests>=2.32.2 in /usr/local/lib/python3.11/dist-packages (from datasets) (2.32.3)
Requirement already satisfied: tqdm>=4.66.3 in /usr/local/lib/python3.11/dist-packages (from datasets) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.9.0,>=2023.1.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets) (2024.9.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets) (3.11.11)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.11/dist-packages (from datasets) (0.27.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from datasets) (24.2)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets) (6.0.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.23.0->datasets) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.32.2->datasets) (2024.12.14)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->datasets) (2025.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.17.0)
Requirement already satisfied: evaluate in /usr/local/lib/python3.11/dist-packages (0.4.3)
Requirement already satisfied: datasets>=2.0.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (3.2.0)
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.11/dist-packages (from evaluate) (1.26.4)
Requirement already satisfied: dill in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.3.8)
Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.2.2)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (2.32.3)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.11/dist-packages (from evaluate) (4.67.1)
Requirement already satisfied: xxhash in /usr/local/lib/python3.11/dist-packages (from evaluate) (3.5.0)
Requirement already satisfied: multiprocess in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.70.16)
Requirement already satisfied: fsspec>=2021.05.0 in /usr/local/lib/python3.11/dist-packages (from fsspec[http]>=2021.05.0->evaluate) (2024.9.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.11/dist-packages (from evaluate) (0.27.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.11/dist-packages (from evaluate) (24.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (3.17.0)
Requirement already satisfied: pyarrow>=15.0.0 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (17.0.0)
Requirement already satisfied: aiohttp in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (3.11.11)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.11/dist-packages (from datasets>=2.0.0->evaluate) (6.0.2)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.11/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.19.0->evaluate) (2024.12.14)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas->evaluate) (2025.1)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.3.2)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (24.3.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.11/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (1.18.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas->evaluate) (1.17.0)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.11/dist-packages (0.2.0)

Device set to use cuda:0

              type                                           question  \
3529  MULTI-SELECT             What algorithms are you familiar with?
3530  MULTI-SELECT             What algorithms are you familiar with?
3531  MULTI-SELECT             What algorithms are you familiar with?
3532  MULTI-SELECT             What algorithms are you familiar with?
3533  MULTI-SELECT             What algorithms are you familiar with?
...            ...                                                ...
4471  MULTI-SELECT  Which social media platforms do you use for ma...
4472  MULTI-SELECT  Which social media platforms do you use for ma...
4473  MULTI-SELECT  Which social media platforms do you use for ma...
4474  MULTI-SELECT  Which social media platforms do you use for ma...
4475  MULTI-SELECT  Which social media platforms do you use for ma...

                                                options  \
3529  [Sorting algorithms,  Searching algorithms,  G...
3530  [Sorting algorithms,  Searching algorithms,  G...
3531  [Sorting algorithms,  Searching algorithms,  G...
3532  [Sorting algorithms,  Searching algorithms,  G...
3533  [Sorting algorithms,  Searching algorithms,  G...
...                                                 ...
4471  [Facebook,  Instagram,  Twitter,  LinkedIn,  T...
4472  [Facebook,  Instagram,  Twitter,  LinkedIn,  T...
4473  [Facebook,  Instagram,  Twitter,  LinkedIn,  T...
4474  [Facebook,  Instagram,  Twitter,  LinkedIn,  T...
4475  [Facebook,  Instagram,  Twitter,  LinkedIn,  T...

                                                 answer  \
3529  I'm familiar with a wide range of algorithms, ...
3530          Sorting, searching, and graph algorithms.
3531  I know a bunch of those, like the sorting and ...
3532  My algorithm knowledge encompasses several cat...
3533  I know about sorting, searching, and divide an...
...                                                 ...
4471  We primarily utilize Facebook and Instagram fo...
4472                   Facebook, Instagram, and TikTok.
4473  We're all over Facebook and Insta, mostly.  Yo...
4474  Our marketing strategy uses a multi-platform a...
4475  We use Facebook, Instagram, and Twitter.  It's...

                                    answer_label_GEMINI answer_category
3529  [Sorting algorithms, Searching algorithms, Gra...         verbose
3530  [Sorting algorithms, Searching algorithms, Gra...         concise
3531  [Sorting algorithms, Searching algorithms, Gra...      colloquial
3532  [Sorting algorithms, Searching algorithms, Dyn...     explanatory
3533  [Sorting algorithms, Searching algorithms, Div...         annoyed
...                                                 ...             ...
4471                      Facebook, Instagram, LinkedIn         verbose
4472                        Facebook, Instagram, TikTok         concise
4473                       Facebook, Instagram, YouTube      colloquial
4474             Facebook, Instagram, YouTube, LinkedIn     explanatory
4475                       Facebook, Instagram, Twitter         annoyed

[947 rows x 6 columns]
              type                                           question  \
3529  MULTI-SELECT             What algorithms are you familiar with?
3530  MULTI-SELECT             What algorithms are you familiar with?
3531  MULTI-SELECT             What algorithms are you familiar with?
3532  MULTI-SELECT             What algorithms are you familiar with?
3533  MULTI-SELECT             What algorithms are you familiar with?
...            ...                                                ...
4471  MULTI-SELECT  Which social media platforms do you use for ma...
4472  MULTI-SELECT  Which social media platforms do you use for ma...
4473  MULTI-SELECT  Which social media platforms do you use for ma...
4474  MULTI-SELECT  Which social media platforms do you use for ma...
4475  MULTI-SELECT  Which social media platforms do you use for ma...

                                                options  \
3529  [Sorting algorithms,  Searching algorithms,  G...
3530  [Sorting algorithms,  Searching algorithms,  G...
3531  [Sorting algorithms,  Searching algorithms,  G...
3532  [Sorting algorithms,  Searching algorithms,  G...
3533  [Sorting algorithms,  Searching algorithms,  G...
...                                                 ...
4471  [Facebook,  Instagram,  Twitter,  LinkedIn,  T...
4472  [Facebook,  Instagram,  Twitter,  LinkedIn,  T...
4473  [Facebook,  Instagram,  Twitter,  LinkedIn,  T...
4474  [Facebook,  Instagram,  Twitter,  LinkedIn,  T...
4475  [Facebook,  Instagram,  Twitter,  LinkedIn,  T...

                                                 answer  \
3529  I'm familiar with a wide range of algorithms, ...
3530          Sorting, searching, and graph algorithms.
3531  I know a bunch of those, like the sorting and ...
3532  My algorithm knowledge encompasses several cat...
3533  I know about sorting, searching, and divide an...
...                                                 ...
4471  We primarily utilize Facebook and Instagram fo...
4472                   Facebook, Instagram, and TikTok.
4473  We're all over Facebook and Insta, mostly.  Yo...
4474  Our marketing strategy uses a multi-platform a...
4475  We use Facebook, Instagram, and Twitter.  It's...

                                    answer_label_GEMINI answer_category  \
3529  [Sorting algorithms, Searching algorithms, Gra...         verbose
3530  [Sorting algorithms, Searching algorithms, Gra...         concise
3531  [Sorting algorithms, Searching algorithms, Gra...      colloquial
3532  [Sorting algorithms, Searching algorithms, Dyn...     explanatory
3533  [Sorting algorithms, Searching algorithms, Div...         annoyed
...                                                 ...             ...
4471                      Facebook, Instagram, LinkedIn         verbose
4472                        Facebook, Instagram, TikTok         concise
4473                       Facebook, Instagram, YouTube      colloquial
4474             Facebook, Instagram, YouTube, LinkedIn     explanatory
4475                       Facebook, Instagram, Twitter         annoyed

                           answer_label_BART_large_mnli
3529  [ Searching algorithms,  Graph algorithms, Sor...
3530  [ Graph algorithms,  Searching algorithms, Sor...
3531  [ Dynamic programming,  Searching algorithms, ...
3532  [ Greedy algorithms,  Searching algorithms, So...
3533  [ Divide and conquer, Sorting algorithms,  Sea...
...                                                 ...
4471                             [Facebook,  Instagram]
4472                    [ TikTok, Facebook,  Instagram]
4473                   [Facebook,  YouTube,  Instagram]
4474        [ YouTube, Facebook,  Instagram,  LinkedIn]
4475                   [Facebook,  Twitter,  Instagram]

[947 rows x 7 columns]
               type                                    question  \
2791  SINGLE-SELECT  Are you currently using a similar product?
2792  SINGLE-SELECT  Are you currently using a similar product?
2793  SINGLE-SELECT  Are you currently using a similar product?
2794  SINGLE-SELECT  Are you currently using a similar product?
2795  SINGLE-SELECT  Are you currently using a similar product?
...             ...                                         ...
3524  SINGLE-SELECT         What is your preferred client type?
3525  SINGLE-SELECT         What is your preferred client type?
3526  SINGLE-SELECT         What is your preferred client type?
3527  SINGLE-SELECT         What is your preferred client type?
3528  SINGLE-SELECT         What is your preferred client type?

                                                options  \
2791                                         [Yes,  No]
2792                                         [Yes,  No]
2793                                         [Yes,  No]
2794                                         [Yes,  No]
2795                                         [Yes,  No]
...                                                 ...
3524  [Small Businesses,  Large Corporations,  Non-p...
3525  [Small Businesses,  Large Corporations,  Non-p...
3526  [Small Businesses,  Large Corporations,  Non-p...
3527  [Small Businesses,  Large Corporations,  Non-p...
3528  [Small Businesses,  Large Corporations,  Non-p...

                                                 answer  answer_label_GEMINI  \
2791   Yes, I'm currently utilizing a similar produc...                  Yes
2792                                                No.                   No
2793                      Nope, nothin' like that here.                   No
2794   No, I am not currently using a similar produc...                   No
2795    No, I already have a perfectly adequate syst...                   No
...                                                 ...                  ...
3524   I find working with small businesses the most...     Small Businesses
3525                                Large corporations.   Large Corporations
3526    Gotta go with non-profits, man.  Doing good ...          Non-profits
3527    Government agencies offer a unique set of ch...  Government Agencies
3528    Individuals are really my least favorite to ...          Individuals

     answer_category answer_label_BART_large_mnli
2791         verbose                          Yes
2792         concise                           No
2793      colloquial                           No
2794     explanatory                           No
2795         annoyed                           No
...              ...                          ...
3524         verbose             Small Businesses
3525         concise           Large Corporations
3526      colloquial                  Non-profits
3527     explanatory          Government Agencies
3528         annoyed                  Individuals

[738 rows x 7 columns]

In [4]:
df_full = df_full.fillna('NaN')
df_full.to_csv('all_answers_combined_reshaped_with_BART_large_mnli_MULTI_SINGLE_labels.csv', index=False, sep='>')
df_full

,type,question,options,answer,answer_label_GEMINI,answer_category,answer_label_BART_large_mnli
0,type,question,[options],answer,answer_label_GEMINI,answer_category,NaN
1,TEXT,Describe any areas where cost savings could be...,[Text],Significant cost savings could be realized by...,"Supplier negotiation, energy efficiency, proce...",verbose,NaN
2,TEXT,Describe any areas where cost savings could be...,[Text],"Reduce supplier costs, improve energy efficie...",Cost reduction strategies,concise,NaN
3,TEXT,Describe any areas where cost savings could be...,[Text],"Dude, we could totally save a ton of cash by...","Supplier negotiation, energy saving, waste red...",colloquial,NaN
4,TEXT,Describe any areas where cost savings could be...,[Text],Cost savings can be achieved through a multi-...,"Contract review, energy efficiency, workflow o...",explanatory,NaN
...,...,...,...,...,...,...,...
4471,MULTI-SELECT,Which social media platforms do you use for ma...,"[Facebook, Instagram, Twitter, LinkedIn, T...",We primarily utilize Facebook and Instagram fo...,"Facebook, Instagram, LinkedIn",verbose,"[Facebook, Instagram]"
4472,MULTI-SELECT,Which social media platforms do you use for ma...,"[Facebook, Instagram, Twitter, LinkedIn, T...","Facebook, Instagram, and TikTok.","Facebook, Instagram, TikTok",concise,"[ TikTok, Facebook, Instagram]"
4473,MULTI-SELECT,Which social media platforms do you use for ma...,"[Facebook, Instagram, Twitter, LinkedIn, T...","We're all over Facebook and Insta, mostly. Yo...","Facebook, Instagram, YouTube",colloquial,"[Facebook, YouTube, Instagram]"
4474,MULTI-SELECT,Which social media platforms do you use for ma...,"[Facebook, Instagram, Twitter, LinkedIn, T...",Our marketing strategy uses a multi-platform a...,"Facebook, Instagram, YouTube, LinkedIn",explanatory,"[ YouTube, Facebook, Instagram, LinkedIn]"
4475,MULTI-SELECT,Which social media platforms do you use for ma...,"[Facebook, Instagram, Twitter, LinkedIn, T...","We use Facebook, Instagram, and Twitter. It's...","Facebook, Instagram, Twitter",annoyed,"[Facebook, Twitter, Instagram]"

### TEXT

In [ ]:
import pandas as pd

url = 'https://raw.githubusercontent.com/Penguinbeanie/Capstone-Project/refs/heads/dev_branch/artificial_answers/all_answers_combined_reshaped_with_BART_large_mnli_MULTI_SINGLE_labels_fixed.txt'
df_full = pd.read_csv(url, sep='>', header=0, names=['type', 'question', 'options', 'answer', 'answer_label_GEMINI', 'answer_category', 'answer_label_BART_large_mnli'])
df_TEXT = df_full[df_full['type'] == 'TEXT']

In [ ]:
from transformers import (
    TokenClassificationPipeline,
    AutoModelForTokenClassification,
    AutoTokenizer,
)
from transformers.pipelines import AggregationStrategy
import numpy as np

# Define keyphrase extraction pipeline
class KeyphraseExtractionPipeline(TokenClassificationPipeline):
    def __init__(self, model, *args, **kwargs):
        super().__init__(
            model=AutoModelForTokenClassification.from_pretrained(model),
            tokenizer=AutoTokenizer.from_pretrained(model),
            *args,
            **kwargs
        )

    def postprocess(self, all_outputs):
        results = super().postprocess(
            all_outputs=all_outputs,
            aggregation_strategy=AggregationStrategy.SIMPLE,
        )
        return np.unique([result.get("word").strip() for result in results])

model_name = "ml6team/keyphrase-extraction-distilbert-inspec"
extractor = KeyphraseExtractionPipeline(model=model_name)

df_TEXT['keywords_distilbert'] = df_TEXT['answer'].apply(lambda x: extractor(x))
df_TEXT['keywords_distilbert'] = df_TEXT['keywords_distilbert'].apply(lambda x: ', '.join(x))

# drop all rows where type == TEXT
df_full = df_full.drop(df_full[df_full['type'] == 'TEXT'].index)

# append df_TEXT to df_full
df_full = pd.concat([df_full, df_TEXT])
df_full = df_full.sort_index()

df_TEXT

config.json:   0%|          | 0.00/697 [00:00<?, ?B/s]

c:\Users\carol\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py:140: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\carol\.cache\huggingface\hub\models--ml6team--keyphrase-extraction-distilbert-inspec. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

pytorch_model.bin:   0%|          | 0.00/266M [00:00<?, ?B/s]

c:\Users\carol\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()

tokenizer_config.json:   0%|          | 0.00/333 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/712k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/265M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Device set to use cpu
C:\Users\carol\AppData\Local\Temp\ipykernel_21152\3098476646.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_TEXT['keywords_distilbert'] = df_TEXT['answer'].apply(lambda x: extractor(x))
C:\Users\carol\AppData\Local\Temp\ipykernel_21152\3098476646.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_TEXT['keywords_distilbert'] = df_TEXT['keywords_distilbert'].apply(lambda x: ', '.join(x))

,type,question,options,answer,answer_label_GEMINI,answer_category,answer_label_BART_large_mnli,keywords_distilbert
0,TEXT,Describe any areas where cost savings could be...,['Text'],Significant cost savings could be realized by...,"Supplier negotiation, energy efficiency, proce...",verbose,NaN,"cost efficiency, energy consumption, redundanc..."
1,TEXT,Describe any areas where cost savings could be...,['Text'],"Reduce supplier costs, improve energy efficie...",Cost reduction strategies,concise,NaN,"energy efficiency, redundancies, supplier costs"
2,TEXT,Describe any areas where cost savings could be...,['Text'],"Dude, we could totally save a ton of cash by...","Supplier negotiation, energy saving, waste red...",colloquial,NaN,suppliers
3,TEXT,Describe any areas where cost savings could be...,['Text'],Cost savings can be achieved through a multi-...,"Contract review, energy efficiency, workflow o...",explanatory,NaN,"cost savings, negotiation, price reductions, s..."
4,TEXT,Describe any areas where cost savings could be...,['Text'],"Well, obviously we need to look at our spend...","Supplier negotiation, energy cost reduction",annoyed,NaN,"energy bills, spending, suppliers"
...,...,...,...,...,...,...,...,...
894,TEXT,Would you recommend our support to others? Why...,['Text'],"Yes, I would definitely recommend your suppor...","Positive recommendation, detailed explanation",verbose,NaN,
895,TEXT,Would you recommend our support to others? Why...,['Text'],Absolutely.,Positive recommendation,concise,NaN,
896,TEXT,Would you recommend our support to others? Why...,['Text'],"Yeah, for sure! They totally sorted me out.",Casual positive recommendation,colloquial,NaN,
897,TEXT,Would you recommend our support to others? Why...,['Text'],I would recommend your support based on my po...,"Positive recommendation, process explanation",explanatory,NaN,
898,TEXT,Would you recommend our support to others? Why...,['Text'],"Yes, it was fine, I guess. But it took long...","Slightly negative, but still recommending",annoyed,NaN,

In [ ]:
df_full = df_full.fillna('NaN')
df_full.to_csv('all_answers_combined_reshaped_with_BART_large_mnli_MULTI_SINGLE_TEXT_labels.csv', index=False, sep='>')
df_full

,type,question,options,answer,answer_label_GEMINI,answer_category,answer_label_BART_large_mnli,keywords_distilbert
0,TEXT,Describe any areas where cost savings could be...,['Text'],Significant cost savings could be realized by...,"Supplier negotiation, energy efficiency, proce...",verbose,NaN,"cost efficiency, energy consumption, redundanc..."
1,TEXT,Describe any areas where cost savings could be...,['Text'],"Reduce supplier costs, improve energy efficie...",Cost reduction strategies,concise,NaN,"energy efficiency, redundancies, supplier costs"
2,TEXT,Describe any areas where cost savings could be...,['Text'],"Dude, we could totally save a ton of cash by...","Supplier negotiation, energy saving, waste red...",colloquial,NaN,suppliers
3,TEXT,Describe any areas where cost savings could be...,['Text'],Cost savings can be achieved through a multi-...,"Contract review, energy efficiency, workflow o...",explanatory,NaN,"cost savings, negotiation, price reductions, s..."
4,TEXT,Describe any areas where cost savings could be...,['Text'],"Well, obviously we need to look at our spend...","Supplier negotiation, energy cost reduction",annoyed,NaN,"energy bills, spending, suppliers"
...,...,...,...,...,...,...,...,...
3742,MULTI-SELECT,Which social media platforms do you use for ma...,"['Facebook', ' Instagram', ' Twitter', ' Linke...",We primarily utilize Facebook and Instagram fo...,"Facebook, Instagram, LinkedIn",verbose,"['Facebook', ' Instagram']",NaN
3743,MULTI-SELECT,Which social media platforms do you use for ma...,"['Facebook', ' Instagram', ' Twitter', ' Linke...","Facebook, Instagram, and TikTok.","Facebook, Instagram, TikTok",concise,"[' TikTok', 'Facebook', ' Instagram']",NaN
3744,MULTI-SELECT,Which social media platforms do you use for ma...,"['Facebook', ' Instagram', ' Twitter', ' Linke...","We're all over Facebook and Insta, mostly. Yo...","Facebook, Instagram, YouTube",colloquial,"['Facebook', ' YouTube', ' Instagram']",NaN
3745,MULTI-SELECT,Which social media platforms do you use for ma...,"['Facebook', ' Instagram', ' Twitter', ' Linke...",Our marketing strategy uses a multi-platform a...,"Facebook, Instagram, YouTube, LinkedIn",explanatory,"[' YouTube', 'Facebook', ' Instagram', ' Linke...",NaN
3746,MULTI-SELECT,Which social media platforms do you use for ma...,"['Facebook', ' Instagram', ' Twitter', ' Linke...","We use Facebook, Instagram, and Twitter. It's...","Facebook, Instagram, Twitter",annoyed,"['Facebook', ' Twitter', ' Instagram']",NaN

# Generating more answers using T5

In [ ]:
# Cell for model setup with memory management
import torch
import os
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer
import gc
import psutil

def get_memory_usage():
    """Get current memory usage in MB"""
    process = psutil.Process()
    return process.memory_info().rss / 1024 / 1024

def clear_memory():
    """Clear unused memory"""
    gc.collect()
    torch.cuda.empty_cache() if torch.cuda.is_available() else None

def setup_optimized_model(model_name="google/flan-t5-base", max_memory_usage=0.8):
    """Setup model with memory optimizations"""
    try:
        # Clear memory before loading
        clear_memory()
        initial_memory = get_memory_usage()
        print(f"Initial memory usage: {initial_memory:.2f} MB")

        # Calculate available memory
        total_memory = psutil.virtual_memory().total / 1024 / 1024
        available_memory = total_memory * max_memory_usage
        print(f"Available memory for model: {available_memory:.2f} MB")

        # Enable CPU optimizations
        torch.set_num_threads(max(1, os.cpu_count() - 1))  # Leave one core free
        torch.set_grad_enabled(False)

        print("Setting up model...")
        tokenizer = AutoTokenizer.from_pretrained(
            model_name,
            cache_dir="./model_cache",
            local_files_only=True
        )

        model = AutoModelForSeq2SeqLM.from_pretrained(
            model_name,
            cache_dir="./model_cache",
            local_files_only=True,
            torch_dtype=torch.float32,
            low_cpu_mem_usage=True,
            max_memory={0: f"{int(available_memory * 0.8)}MB"}  # Use 80% of available memory
        )

        # Enable evaluation mode
        model.eval()

        # Check memory usage after loading
        final_memory = get_memory_usage()
        print(f"Final memory usage: {final_memory:.2f} MB")
        print(f"Model setup complete! Memory increase: {final_memory - initial_memory:.2f} MB")

        return model, tokenizer

    except Exception as e:
        print(f"Error setting up model: {str(e)}")
        return None, None

# Make model and tokenizer global with memory monitoring
global model, tokenizer

# Setup the model with memory management
clear_memory()  # Clear memory before setup
model, tokenizer = setup_optimized_model()

# Verify setup and memory usage
if model is not None and tokenizer is not None:
    print("\nModel information:")
    print(f"Model type: {type(model).__name__}")
    print(f"Tokenizer type: {type(tokenizer).__name__}")
    print(f"Model parameters: {sum(p.numel() for p in model.parameters()):,}")
    print(f"Current memory usage: {get_memory_usage():.2f} MB")
else:
    print("Failed to setup model and tokenizer")

# Add memory monitoring function for other cells
def monitor_memory():
    """Monitor memory usage"""
    memory_usage = get_memory_usage()
    print(f"Current memory usage: {memory_usage:.2f} MB")
    if memory_usage > psutil.virtual_memory().total * 0.9 / 1024 / 1024:
        print("Warning: High memory usage detected!")
        clear_memory()

c:\Users\carol\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\generic.py:441: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(

Initial memory usage: 399.68 MB
Available memory for model: 12776.08 MB
Setting up model...

c:\Users\carol\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
c:\Users\carol\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(

Final memory usage: 490.51 MB
Model setup complete! Memory increase: 90.83 MB

Model information:
Model type: T5ForConditionalGeneration
Tokenizer type: T5TokenizerFast
Model parameters: 247,577,856
Current memory usage: 490.52 MB

c:\Users\carol\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\utils\generic.py:309: FutureWarning: `torch.utils._pytree._register_pytree_node` is deprecated. Please use `torch.utils._pytree.register_pytree_node` instead.
  _torch_pytree._register_pytree_node(
c:\Users\carol\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

## NUMBER

In [ ]:
import torch
import os
import time
import psutil
import pandas as pd
from tqdm import tqdm
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

def generate_text_batch(prompts, model, tokenizer, max_length=1024):
    """Generate text for a batch of prompts with memory management"""
    try:
        with torch.no_grad():  # Ensure no gradients are computed
            # Tokenize with memory optimization
            inputs = tokenizer(
                prompts,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=512
            )

            # Generate text
            outputs = model.generate(
                **inputs,
                max_length=max_length,
                num_return_sequences=1,
                do_sample=True,
                temperature=0.8,
                top_p=0.92,
                top_k=50,
                num_beams=4,
                length_penalty=1.0,
                pad_token_id=tokenizer.eos_token_id
            )

            # Decode outputs
            responses = tokenizer.batch_decode(outputs, skip_special_tokens=True)

            # Clean up
            del inputs, outputs
            torch.cuda.empty_cache() if torch.cuda.is_available() else None

            return [r.strip() for r in responses]

    except Exception as e:
        print(f"Error in batch generation: {str(e)}")
        return [None] * len(prompts)

def generate_all_responses(checkpoint_frequency=25, start_from_checkpoint=True):
    try:
        # Monitor initial memory
        initial_memory = get_memory_usage()
        print(f"Initial memory usage: {initial_memory:.2f} MB")

        # Use global model and tokenizer
        global model, tokenizer
        if model is None or tokenizer is None:
            raise Exception("Model not initialized. Please run setup cell first.")

        # Load and prepare data in chunks
        chunk_size = 50  # Process data in smaller chunks
        checkpoint_file = 'NUMBER_answer_T5_checkpoint.csv'

        # Load checkpoint if exists
        processed_pairs = set()
        all_answers = []
        last_processed_index = 0

        if start_from_checkpoint and os.path.exists(checkpoint_file):
            try:
                checkpoint_df = pd.read_csv(checkpoint_file, sep='>')
                all_answers = checkpoint_df.to_dict('records')
                processed_pairs = {f"{row['question']}_{row['tone']}" for _, row in checkpoint_df.iterrows()}

                # Find last processed question
                if all_answers:
                    last_question = checkpoint_df.iloc[-1]['question']
                    print(f"Loaded {len(all_answers)} existing answers from checkpoint")
                    print(f"Last processed question: {last_question}")
            except Exception as e:
                print(f"Error loading checkpoint: {str(e)}")
                print("Starting from beginning")

        # Load and process data in chunks
        for chunk_idx, df_chunk in enumerate(pd.read_csv('artificial_answers/NUMBER/NUMBER_answer_combined_total_reshaped.csv',
                                                        sep='>', chunksize=chunk_size)):

            clear_memory()  # Clear memory before processing new chunk
            unique_questions = df_chunk.drop_duplicates(subset=['question'], keep='first')

            # Skip chunks that have been fully processed
            if all(f"{row['question']}_{tone}" in processed_pairs
                  for _, row in unique_questions.iterrows()
                  for tone in ['verbose', 'concise', 'colloquial', 'explanatory', 'annoyed']):
                continue

            batch_size = 2  # Reset batch size for each chunk
            batch_prompts = []
            batch_metadata = []

            # Process questions in current chunk
            for _, row in unique_questions.iterrows():
                for tone, tone_style in {
                    'verbose': 'provide a detailed and comprehensive answer',
                    'concise': 'provide a brief, direct and short answer',
                    'colloquial': 'provide a casual and informal answer',
                    'explanatory': 'provide a clear and professional answer',
                    'annoyed': 'provide a frustrated and dissatisfied answer'
                }.items():
                    pair_id = f"{row['question']}_{tone}"

                    if pair_id in processed_pairs:
                        continue

                    prompt = f"""You are tasked with analyzing the given question and answers to provide five more distinct open-ended answers with different tones.
                            Each answer should vary in style and tone (e.g., verbose, concise, colloquial, explanatory, annoyed).
                            Ensure the responses are meaningful, aligned with the question.
                            The answers must make sense in the given context for the type "NUMBER".

                            Question: {row['question']}
                            Available options: {row['options']}
                            Required tone: {tone_style}

                            Provide a single response in the specified tone, without any additional commentary or formatting."""

                    batch_prompts.append(prompt)
                    batch_metadata.append({
                        'type': 'NUMBER',
                        'question': row['question'],
                        'options': row['options'],
                        'tone': tone
                    })

                    # Process batch when it reaches batch_size
                    if len(batch_prompts) >= batch_size:
                        clear_memory()

                        responses = generate_text_batch(batch_prompts, model, tokenizer)

                        for metadata, response in zip(batch_metadata, responses):
                            if response:
                                answer_entry = {**metadata, 'answer': response}
                                all_answers.append(answer_entry)
                                processed_pairs.add(f"{metadata['question']}_{metadata['tone']}")

                        # Save checkpoint
                        if len(all_answers) % checkpoint_frequency == 0:
                            pd.DataFrame(all_answers).to_csv(checkpoint_file, index=False, sep='>')
                            print(f"\nCheckpoint saved. Processed {len(all_answers)} answers.")
                            print(f"Current memory usage: {get_memory_usage():.2f} MB")

                        batch_prompts = []
                        batch_metadata = []
                        time.sleep(0.5)

            # Process remaining prompts in chunk
            if batch_prompts:
                clear_memory()
                responses = generate_text_batch(batch_prompts, model, tokenizer)
                for metadata, response in zip(batch_metadata, responses):
                    if response:
                        answer_entry = {**metadata, 'answer': response}
                        all_answers.append(answer_entry)
                        processed_pairs.add(f"{metadata['question']}_{metadata['tone']}")

            print(f"\nCompleted chunk {chunk_idx + 1}")

        # Save final results
        clear_memory()
        df_output = pd.DataFrame(all_answers)
        df_output.to_csv('NUMBER_answer_T5_all.csv', index=False, sep='>')

        if os.path.exists(checkpoint_file):
            os.remove(checkpoint_file)

        final_memory = get_memory_usage()
        print(f"\nFinal memory usage: {final_memory:.2f} MB")
        print(f"Memory change: {final_memory - initial_memory:.2f} MB")

        return df_output

    except Exception as e:
        print(f"Error occurred: {str(e)}")
        if all_answers:
            emergency_file = f'NUMBER_answer_T5_emergency_{int(time.time())}.csv'
            pd.DataFrame(all_answers).to_csv(emergency_file, index=False, sep='>')
            print(f"Emergency checkpoint saved to {emergency_file}")
        return None

def main():
    # Monitor system resources
    print("\nSystem information:")
    print(f"Total memory: {psutil.virtual_memory().total / 1024 / 1024:.2f} MB")
    print(f"Available memory: {psutil.virtual_memory().available / 1024 / 1024:.2f} MB")
    print(f"CPU cores: {os.cpu_count()}")

    try:
        # Run generation with crash recovery
        result = generate_all_responses(
            checkpoint_frequency=50,  # Save more frequently
            start_from_checkpoint=True  # Continue from last checkpoint
        )

        if result is not None:
            print(f"\nSuccessfully generated {len(result)} responses")
        else:
            print("Generation failed")

    except KeyboardInterrupt:
        print("\nProcess interrupted by user. Progress has been saved to checkpoint.")
    except Exception as e:
        print(f"\nUnexpected error: {str(e)}")
        print("Progress has been saved to checkpoint.")

if __name__ == "__main__":
    main()

System information:
Total memory: 15970.10 MB
Available memory: 6901.24 MB
CPU cores: 8
Initial memory usage: 521.51 MB
Loaded 300 existing answers from checkpoint

Generating responses:  77%|███████▋  | 700/910 [02:43<03:40,  1.05s/it]

Checkpoint saved. Current memory usage: 2411.25 MB

Generating responses:  88%|████████▊ | 800/910 [09:03<02:25,  1.32s/it]

Checkpoint saved. Current memory usage: 2406.47 MB

Generating responses:  99%|█████████▉| 900/910 [23:11<02:18, 13.87s/it]

Checkpoint saved. Current memory usage: 3428.34 MB

Generating responses: 1208it [45:06,  2.98s/it]

Final memory usage: 2252.25 MB
Memory change: 1730.74 MB

Successfully generated 909 responses

## Text

In [ ]:
def generate_text(prompts, max_length=1024):
    try:
        with torch.no_grad():  # Ensure no gradients are computed
            # Tokenize with memory optimization
            inputs = tokenizer(
                prompts,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=512
            )

            # Generate text
            outputs = model.generate(
                **inputs,
                max_length=max_length,
                num_return_sequences=1,
                do_sample=True,
                temperature=0.8,
                top_p=0.92,
                top_k=50,
                num_beams=4,
                length_penalty=1.0,
                pad_token_id=tokenizer.eos_token_id
            )

            # Decode outputs
            responses = tokenizer.batch_decode(outputs, skip_special_tokens=True)

            # Clean up
            del inputs, outputs
            torch.cuda.empty_cache() if torch.cuda.is_available() else None

            return [r.strip() for r in responses]

    except Exception as e:
        print(f"Error in batch generation: {str(e)}")
        return [None] * len(prompts)

def generate_all_responses():
    try:
        # Load the full file
        df = pd.read_csv('artificial_answers/TEXT/TEXT_answer_combined_total_reshaped.csv', sep='>')

        # Get unique questions and their first occurrence of answer
        unique_questions = df.drop_duplicates(subset=['question'], keep='first')

        all_answers = []
        tones = {
            'verbose': 'provide a detailed and comprehensive answer',
            'concise': 'provide a brief, direct and short answer',
            'colloquial': 'provide a casual and informal answer',
            'explanatory': 'provide a clear and professional answer',
            'annoyed': 'provide a frustrated and dissatisfied answer'
        }

        # Track processed question-tone pairs
        processed_pairs = set()

        for _, row in unique_questions.iterrows():
            for tone, tone_style in tones.items():
                pair_id = f"{row['question']}_{tone}"

                if pair_id in processed_pairs:
                    continue

                prompts = f"""You are tasked with analyzing the given question and answers to provide five more distinct open-ended answers with different tones.
                        Each answer should vary in style and tone (e.g., verbose, concise, colloquial, explanatory, annoyed).
                        Ensure the responses are meaningful, aligned with the question.
                        The answers must make sense in the given context for the type "TEXT".

                        Question: {row['question']}
                        Available options: {row['options']}
                        Required tone: {tone_style}

                        Provide a single response in the specified tone, without any additional commentary or formatting."""

                response = generate_text(prompts)
                if response:
                    answer_entry = {
                        'type': 'TEXT',
                        'question': row['question'],
                        'options': row['options'],
                        'answer': response,
                        'tone': tone
                    }
                    all_answers.append(answer_entry)
                    processed_pairs.add(pair_id)
                time.sleep(1)

        df_output = pd.DataFrame(all_answers)
        df_output.to_csv('TEXT_answer_T5_all.csv', index=False, sep='>')

        return df_output

    except Exception as e:
        print(f"Error occurred: {str(e)}")
        return None
# Run the generation
result = generate_all_responses()

Processed question: Describe any areas where cost savings could be ach...
Processed question: Describe any areas where the company could improve...
Processed question: Describe any areas where the convention fell short...
Processed question: Describe any challenges in delivering the message....
Processed question: Describe any incidents or near misses that occurre...
Processed question: Describe any instances of unfairness you observed ...
Processed question: Describe the agent's demeanor....
Processed question: Describe the audience for the communication....
Processed question: Describe the challenges associated with maintainin...
Processed question: Describe the challenges associated with managing a...
Processed question: Describe the communication strategy....
Processed question: Describe the company's approach to data analytics ...
Processed question: Describe the company's approach to risk management...
Processed question: Describe the company's commitment to health and sa...
Processed question: Describe the company's efforts to foster a culture...
Processed question: Describe the environmental impact of the operation...
Processed question: Describe the feedback received on the communicatio...
Processed question: Describe the impact of automation on the workforce...
Processed question: Describe the impact of global economic conditions ...
Processed question: Describe the impact of recent technological advanc...
Processed question: Describe the overall effectiveness of the communic...
Processed question: Describe the process....
Processed question: Describe the quality control measures implemented....
Processed question: Describe the safety procedures followed during the...
Processed question: Describe your experience with the registration pro...
Processed question: Describe your experience with the support agent's ...
Processed question: Describe your experience with the technology used ...
Processed question: Describe your experience....
Processed question: Describe your favorite part of the convention....
Processed question: Describe your interaction with the convention staf...
Processed question: Describe your overall experience....
Processed question: Detail your experience with the new welding equipm...
Processed question: Did the agent follow up as promised?...
Processed question: Did the agent use appropriate language and termino...
Processed question: Did the support agent actively listen to your conc...
Processed question: Did you feel the agent understood your problem?...
Processed question: Did you feel the convention was worth the cost?...
Processed question: Did you feel valued as a customer?...
Processed question: Did you feel your issue was resolved efficiently?...
Processed question: Discuss the importance of continuous improvement i...
Processed question: Elaborate on the training provided to the operator...
Processed question: Elaborate on your response....
Processed question: Explain any challenges encountered during the proj...
Processed question: Explain the company's strategy for attracting and ...
Processed question: Explain the process for conducting regular equipme...
Processed question: Explain the process for handling customer complain...
Processed question: Explain the process for handling hazardous materia...
Processed question: Explain your approach....
Processed question: Explain your issue in detail....
Processed question: Explain your reasoning....
Processed question: Explain your role in the communication process....
Processed question: How accessible was the convention for participants...
Processed question: How can the company better engage with its stakeho...
Processed question: How can the company better utilize its resources?...
Processed question: How can the company enhance its reputation and bra...
Processed question: How can the company improve its response to emerge...
Processed question: How confident are you that your issue is truly res...
Processed question: How could communication be improved?...
Processed question: How could the company improve its sustainability i...
Processed question: How could the convention be made more inclusive?...
Processed question: How could the convention better promote a sense of...
Processed question: How could the convention better support participan...
Processed question: How could the fairness of the competition be enhan...
Processed question: How could this be improved?...
Processed question: How did the communication impact the intended audi...
Processed question: How did you ensure ethical communication practices...
Processed question: How did you overcome those challenges?...
Processed question: How easy was it to contact support?...
Processed question: How effective was the communication?...
Processed question: How effectively did the convention balance competi...
Processed question: How effectively did the convention meet its stated...
Processed question: How fair did you perceive the judging process to b...
Processed question: How long did it take to resolve your issue?...
Processed question: How satisfied were you with the networking opportu...
Processed question: How satisfied were you with the resolution?...
Processed question: How was the feedback used to improve future commun...
Processed question: How was the message received?...
Processed question: How would you apply this learning to future commun...
Processed question: How would you describe the atmosphere of the conve...
Processed question: How would you describe the overall tone of the int...
Processed question: How would you improve the clarity and accuracy of ...
Processed question: How would you improve the support agent's training...
Processed question: How would you rate the agent's communication skill...
Processed question: How would you rate the agent's patience and unders...
Processed question: How would you rate the agent's problem-solving ski...
Processed question: How would you rate the clarity of the agent's expl...
Processed question: How would you rate the overall organization of the...
Processed question: How would you rate the overall value of the conven...
Processed question: Is there anything else you would like to share abo...
Processed question: On a scale of 1-10, how likely are you to recommen...
Processed question: Please share any additional feedback you have for ...
Processed question: Provide feedback on the effectiveness of the commu...
Processed question: Provide further details....
Processed question: Rate the overall helpfulness of the support....
Processed question: Reflect on your personal contribution to the commu...
Processed question: Share any concerns you have about the convention....
Processed question: Share any unexpected positive experiences you had ...
Processed question: Share your feedback....
Processed question: Summarize the main points....
Processed question: Was the agent knowledgeable about the product/serv...
Processed question: Was the solution provided easy to understand and i...
Processed question: Were all your questions answered to your satisfact...
Processed question: Were there any delays in getting your issue resolv...
Processed question: Were there any logistical issues you encountered?...
Processed question: Were there any technical difficulties during the s...
Processed question: What are the key challenges facing the heavy indus...
Processed question: What are your observations regarding employee mora...
Processed question: What are your observations regarding the company's...
Processed question: What are your observations regarding the overall p...
Processed question: What are your recommendations for improving the ov...
Processed question: What are your recommendations for improving workpl...
Processed question: What are your suggestions for improving employee t...
Processed question: What are your suggestions for improving the commun...
Processed question: What are your suggestions for improving the overal...
Processed question: What are your suggestions for reducing downtime?...
Processed question: What are your suggestions?...
Processed question: What are your thoughts on the company's long-term ...
Processed question: What are your thoughts on the current level of tec...
Processed question: What are your thoughts on the current maintenance ...
Processed question: What are your thoughts on the current supply chain...
Processed question: What are your thoughts on the effectiveness of the...
Processed question: What are your thoughts on the effectiveness of the...
Processed question: What are your thoughts?...
Processed question: What aspects of the communication were most succes...
Processed question: What aspects of the convention could be improved f...
Processed question: What aspects of the convention did you find most e...
Processed question: What aspects of the convention exceeded your expec...
Processed question: What aspects of the convention fostered a sense of...
Processed question: What aspects of the convention were most impactful...
Processed question: What aspects of the support were particularly nega...
Processed question: What aspects of the support were particularly posi...
Processed question: What challenges did you encounter?...
Processed question: What could we have done better?...
Processed question: What did you learn from participating in the conve...
Processed question: What did you learn from this communication experie...
Processed question: What impact did the convention have on your profes...
Processed question: What improvements could be made to the convention?...
Processed question: What improvements could be made to the efficiency ...
Processed question: What improvements would you suggest for our suppor...
Processed question: What is your feedback on the overall design and la...
Processed question: What is your feedback on the quality of the presen...
Processed question: What is your feedback on the venue?...
Processed question: What is your overall impression of the convention'...
Processed question: What is your suggestion for improving the support ...
Processed question: What lessons were learned from the communication?...
Processed question: What metrics were used to evaluate the communicati...
Processed question: What recommendations would you make for future com...
Processed question: What resources or support did you find most helpfu...
Processed question: What specific actions did the agent take that you ...
Processed question: What specific actions did the agent take that you ...
Processed question: What specific changes would you recommend for the ...
Processed question: What steps did the agent take to resolve your issu...
Processed question: What suggestions do you have for future convention...
Processed question: What tools or resources could have helped the agen...
Processed question: What was the least helpful aspect of the support?...
Processed question: What was the message of the communication?...
Processed question: What was the most helpful aspect of the support?...
Processed question: What was the purpose of the communication?...
Processed question: What was the quality of the resources provided?...
Processed question: What was your favorite part of the support interac...
Processed question: What was your initial impression of the support ag...
Processed question: What was your least favorite part of the support i...
Processed question: What were the barriers to communication?...
Processed question: What were the communication channels used?...
Processed question: What were the ethical considerations involved in t...
Processed question: What were the intended and unintended consequences...
Processed question: What were the key factors contributing to success ...
Processed question: What were the key takeaways?...
Processed question: What were the outcomes of the communication?...
Processed question: What were the results?...
Processed question: What were the strengths and weaknesses of the conv...
Processed question: What were your biggest challenges during the conve...
Processed question: What were your expectations before attending the c...
Processed question: What were your observations?...
Processed question: What would you change about the schedule of events...
Processed question: What would you do differently next time?...
Processed question: Would you recommend our support to others? Why or ...

## DATE

In [ ]:
import torch
import os
import time
import psutil
import pandas as pd
from tqdm import tqdm
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

def generate_text_batch(prompts, model, tokenizer, max_length=1024):
    """Generate text for a batch of prompts with memory management"""
    try:
        with torch.no_grad():  # Ensure no gradients are computed
            # Tokenize with memory optimization
            inputs = tokenizer(
                prompts,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=512
            )

            # Generate text
            outputs = model.generate(
                **inputs,
                max_length=max_length,
                num_return_sequences=1,
                do_sample=True,
                temperature=0.7,  # Slightly lower for more precise date responses
                top_p=0.92,
                top_k=50,
                num_beams=4,
                length_penalty=1.0,
                pad_token_id=tokenizer.eos_token_id
            )

            # Decode outputs
            responses = tokenizer.batch_decode(outputs, skip_special_tokens=True)

            # Clean up
            del inputs, outputs
            torch.cuda.empty_cache() if torch.cuda.is_available() else None

            return [r.strip() for r in responses]

    except Exception as e:
        print(f"Error in batch generation: {str(e)}")
        return [None] * len(prompts)

def generate_all_responses(checkpoint_frequency=25, start_from_checkpoint=True):
    try:
        # Monitor initial memory
        initial_memory = get_memory_usage()
        print(f"Initial memory usage: {initial_memory:.2f} MB")

        # Use global model and tokenizer
        global model, tokenizer
        if model is None or tokenizer is None:
            raise Exception("Model not initialized. Please run setup cell first.")

        # Load and prepare data in chunks
        chunk_size = 50  # Process data in smaller chunks
        checkpoint_file = 'DATE_answer_T5_checkpoint.csv'

        # Load checkpoint if exists
        processed_pairs = set()
        all_answers = []

        if start_from_checkpoint and os.path.exists(checkpoint_file):
            try:
                checkpoint_df = pd.read_csv(checkpoint_file, sep='>')
                all_answers = checkpoint_df.to_dict('records')
                processed_pairs = {f"{row['question']}_{row['tone']}" for _, row in checkpoint_df.iterrows()}

                # Find last processed question
                if all_answers:
                    last_question = checkpoint_df.iloc[-1]['question']
                    print(f"Loaded {len(all_answers)} existing answers from checkpoint")
                    print(f"Last processed question: {last_question}")
            except Exception as e:
                print(f"Error loading checkpoint: {str(e)}")
                print("Starting from beginning")

        # Load and process data in chunks
        for chunk_idx, df_chunk in enumerate(pd.read_csv('artificial_answers/DATE/DATE_answer_combined_total_reshaped.csv',
                                                        sep='>', chunksize=chunk_size)):

            clear_memory()  # Clear memory before processing new chunk
            unique_questions = df_chunk.drop_duplicates(subset=['question'], keep='first')

            # Skip chunks that have been fully processed
            if all(f"{row['question']}_{tone}" in processed_pairs
                  for _, row in unique_questions.iterrows()
                  for tone in ['verbose', 'concise', 'colloquial', 'explanatory', 'annoyed']):
                continue

            batch_size = 2  # Reset batch size for each chunk
            batch_prompts = []
            batch_metadata = []

            # Process questions in current chunk
            for _, row in unique_questions.iterrows():
                for tone, tone_style in {
                    'verbose': 'provide a detailed and comprehensive answer with specific dates',
                    'concise': 'provide a brief answer with the exact date',
                    'colloquial': 'provide a casual answer while including the specific date',
                    'explanatory': 'provide a clear answer explaining the date and its context',
                    'annoyed': 'provide a frustrated answer but still include the exact date'
                }.items():
                    pair_id = f"{row['question']}_{tone}"

                    if pair_id in processed_pairs:
                        continue

                    prompt = f"""You are tasked with analyzing the given question and providing a date-specific answer.
                            The answer should be in the specified tone while ensuring the date information is clear and accurate.
                            The response must make sense in the context of a DATE type question.

                            Question: {row['question']}
                            Available options: {row['options']}
                            Required tone: {tone_style}

                            Provide a single response in the specified tone, including specific dates without any additional commentary."""

                    batch_prompts.append(prompt)
                    batch_metadata.append({
                        'type': 'DATE',
                        'question': row['question'],
                        'options': row['options'],
                        'tone': tone
                    })

                    # Process batch when it reaches batch_size
                    if len(batch_prompts) >= batch_size:
                        clear_memory()

                        responses = generate_text_batch(batch_prompts, model, tokenizer)

                        for metadata, response in zip(batch_metadata, responses):
                            if response:
                                answer_entry = {**metadata, 'answer': response}
                                all_answers.append(answer_entry)
                                processed_pairs.add(f"{metadata['question']}_{metadata['tone']}")

                        # Save checkpoint
                        if len(all_answers) % checkpoint_frequency == 0:
                            pd.DataFrame(all_answers).to_csv(checkpoint_file, index=False, sep='>')
                            print(f"\nCheckpoint saved. Processed {len(all_answers)} answers.")
                            print(f"Current memory usage: {get_memory_usage():.2f} MB")

                        batch_prompts = []
                        batch_metadata = []
                        time.sleep(0.5)

            # Process remaining prompts in chunk
            if batch_prompts:
                clear_memory()
                responses = generate_text_batch(batch_prompts, model, tokenizer)
                for metadata, response in zip(batch_metadata, responses):
                    if response:
                        answer_entry = {**metadata, 'answer': response}
                        all_answers.append(answer_entry)
                        processed_pairs.add(f"{metadata['question']}_{metadata['tone']}")

            print(f"\nCompleted chunk {chunk_idx + 1}")

        # Save final results
        clear_memory()
        df_output = pd.DataFrame(all_answers)
        df_output.to_csv('DATE_answer_T5_all.csv', index=False, sep='>')

        if os.path.exists(checkpoint_file):
            os.remove(checkpoint_file)

        final_memory = get_memory_usage()
        print(f"\nFinal memory usage: {final_memory:.2f} MB")
        print(f"Memory change: {final_memory - initial_memory:.2f} MB")

        return df_output

    except Exception as e:
        print(f"Error occurred: {str(e)}")
        if all_answers:
            emergency_file = f'DATE_answer_T5_emergency_{int(time.time())}.csv'
            pd.DataFrame(all_answers).to_csv(emergency_file, index=False, sep='>')
            print(f"Emergency checkpoint saved to {emergency_file}")
        return None

def main():
    # Monitor system resources
    print("\nSystem information:")
    print(f"Total memory: {psutil.virtual_memory().total / 1024 / 1024:.2f} MB")
    print(f"Available memory: {psutil.virtual_memory().available / 1024 / 1024:.2f} MB")
    print(f"CPU cores: {os.cpu_count()}")

    try:
        # Run generation with crash recovery
        result = generate_all_responses(
            checkpoint_frequency=25,  # Save more frequently
            start_from_checkpoint=True  # Continue from last checkpoint
        )

        if result is not None:
            print(f"\nSuccessfully generated {len(result)} responses")
        else:
            print("Generation failed")

    except KeyboardInterrupt:
        print("\nProcess interrupted by user. Progress has been saved to checkpoint.")
    except Exception as e:
        print(f"\nUnexpected error: {str(e)}")
        print("Progress has been saved to checkpoint.")

if __name__ == "__main__":
    main()

System information:
Total memory: 15970.10 MB
Available memory: 5450.36 MB
CPU cores: 8
Initial memory usage: 2253.17 MB

Checkpoint saved. Processed 50 answers.
Current memory usage: 2256.18 MB

Completed chunk 1

Completed chunk 2

Checkpoint saved. Processed 125 answers.
Current memory usage: 2256.86 MB

Completed chunk 3

Checkpoint saved. Processed 175 answers.
Current memory usage: 2255.36 MB

Completed chunk 4

Checkpoint saved. Processed 225 answers.
Current memory usage: 2255.72 MB

Completed chunk 5

Checkpoint saved. Processed 275 answers.
Current memory usage: 2259.25 MB

Completed chunk 6

Checkpoint saved. Processed 325 answers.
Current memory usage: 3273.41 MB

Completed chunk 7

Completed chunk 8

Checkpoint saved. Processed 400 answers.
Current memory usage: 2741.75 MB

Completed chunk 9

Checkpoint saved. Processed 450 answers.
Current memory usage: 2260.34 MB

Completed chunk 10

Checkpoint saved. Processed 500 answers.
Current memory usage: 2260.67 MB

Completed chunk 11

Checkpoint saved. Processed 550 answers.
Current memory usage: 2261.10 MB

Completed chunk 12

Checkpoint saved. Processed 600 answers.
Current memory usage: 2260.59 MB

Completed chunk 13

Checkpoint saved. Processed 650 answers.
Current memory usage: 2260.79 MB

Completed chunk 14

Checkpoint saved. Processed 700 answers.
Current memory usage: 2261.37 MB

Completed chunk 15

Checkpoint saved. Processed 750 answers.
Current memory usage: 3280.55 MB

Completed chunk 16

Checkpoint saved. Processed 800 answers.
Current memory usage: 2261.80 MB

Completed chunk 17

Checkpoint saved. Processed 850 answers.
Current memory usage: 2262.06 MB

Completed chunk 18

Checkpoint saved. Processed 900 answers.
Current memory usage: 2262.41 MB

Completed chunk 19

Completed chunk 20

Final memory usage: 2262.60 MB
Memory change: 9.43 MB

Successfully generated 930 responses

## MULTI-SELECT

In [ ]:
import torch
import os
import time
import psutil
import pandas as pd
from tqdm import tqdm
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

def generate_text_batch(prompts, model, tokenizer, max_length=1024):
    """Generate text for a batch of prompts with memory management"""
    try:
        with torch.no_grad():
            inputs = tokenizer(
                prompts,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=512
            )

            outputs = model.generate(
                **inputs,
                max_length=max_length,
                num_return_sequences=1,
                do_sample=True,
                temperature=0.8,
                top_p=0.92,
                top_k=50,
                num_beams=5,
                length_penalty=1.0,
                pad_token_id=tokenizer.eos_token_id
            )

            responses = tokenizer.batch_decode(outputs, skip_special_tokens=True)

            # Clean up
            del inputs, outputs
            torch.cuda.empty_cache() if torch.cuda.is_available() else None

            return [r.strip() for r in responses]

    except Exception as e:
        print(f"Error in batch generation: {str(e)}")
        return [None] * len(prompts)

def generate_all_responses(checkpoint_frequency=25, start_from_checkpoint=True):
    try:
        # Monitor initial memory
        initial_memory = get_memory_usage()
        print(f"Initial memory usage: {initial_memory:.2f} MB")

        # Use global model and tokenizer
        global model, tokenizer
        if model is None or tokenizer is None:
            raise Exception("Model not initialized. Please run setup cell first.")

        # Load and prepare data in chunks
        chunk_size = 50
        checkpoint_file = 'MULTI_answer_T5_checkpoint.csv'

        # Load checkpoint if exists
        processed_pairs = set()
        all_answers = []

        if start_from_checkpoint and os.path.exists(checkpoint_file):
            try:
                checkpoint_df = pd.read_csv(checkpoint_file, sep='>')
                all_answers = checkpoint_df.to_dict('records')
                processed_pairs = {f"{row['question']}_{row['tone']}" for _, row in checkpoint_df.iterrows()}

                if all_answers:
                    last_question = checkpoint_df.iloc[-1]['question']
                    print(f"Loaded {len(all_answers)} existing answers from checkpoint")
                    print(f"Last processed question: {last_question}")
            except Exception as e:
                print(f"Error loading checkpoint: {str(e)}")
                print("Starting from beginning")

        # Process data in chunks
        for chunk_idx, df_chunk in enumerate(pd.read_csv('artificial_answers/MULTI/MULTI_answer_combined_total_reshaped.csv',
                                                        sep='>', chunksize=chunk_size)):

            clear_memory()
            unique_questions = df_chunk.drop_duplicates(subset=['question'], keep='first')

            # Skip fully processed chunks
            if all(f"{row['question']}_{tone}" in processed_pairs
                  for _, row in unique_questions.iterrows()
                  for tone in ['verbose', 'concise', 'colloquial', 'explanatory', 'annoyed']):
                continue

            batch_size = 2
            batch_prompts = []
            batch_metadata = []

            for _, row in unique_questions.iterrows():
                for tone, tone_style in {
                    'verbose': 'provide a detailed and comprehensive answer listing multiple selections',
                    'concise': 'provide a brief answer with multiple choices',
                    'colloquial': 'provide a casual answer selecting multiple options',
                    'explanatory': 'provide a clear answer explaining multiple selections',
                    'annoyed': 'provide a frustrated answer while still selecting multiple options'
                }.items():
                    pair_id = f"{row['question']}_{tone}"

                    if pair_id in processed_pairs:
                        continue

                    prompt = f"""You are tasked with analyzing the given question and providing a multi-select answer.
                            The answer should select multiple relevant options in the specified tone.
                            Ensure the response includes multiple selections and matches the MULTI-SELECT format.

                            Question: {row['question']}
                            Available options: {row['options']}
                            Required tone: {tone_style}

                            Provide a single response in the specified tone, selecting multiple options without any additional commentary."""

                    batch_prompts.append(prompt)
                    batch_metadata.append({
                        'type': 'MULTI-SELECT',
                        'question': row['question'],
                        'options': row['options'],
                        'tone': tone
                    })

                    if len(batch_prompts) >= batch_size:
                        clear_memory()

                        responses = generate_text_batch(batch_prompts, model, tokenizer)

                        for metadata, response in zip(batch_metadata, responses):
                            if response:
                                answer_entry = {**metadata, 'answer': response}
                                all_answers.append(answer_entry)
                                processed_pairs.add(f"{metadata['question']}_{metadata['tone']}")

                        if len(all_answers) % checkpoint_frequency == 0:
                            pd.DataFrame(all_answers).to_csv(checkpoint_file, index=False, sep='>')
                            print(f"\nCheckpoint saved. Processed {len(all_answers)} answers.")
                            print(f"Current memory usage: {get_memory_usage():.2f} MB")

                        batch_prompts = []
                        batch_metadata = []

            # Process remaining prompts in chunk
            if batch_prompts:
                clear_memory()
                responses = generate_text_batch(batch_prompts, model, tokenizer)
                for metadata, response in zip(batch_metadata, responses):
                    if response:
                        answer_entry = {**metadata, 'answer': response}
                        all_answers.append(answer_entry)
                        processed_pairs.add(f"{metadata['question']}_{metadata['tone']}")

            print(f"\nCompleted chunk {chunk_idx + 1}")

        # Save final results
        clear_memory()
        df_output = pd.DataFrame(all_answers)
        df_output.to_csv('MULTI_answer_T5_all.csv', index=False, sep='>')

        if os.path.exists(checkpoint_file):
            os.remove(checkpoint_file)

        final_memory = get_memory_usage()
        print(f"\nFinal memory usage: {final_memory:.2f} MB")
        print(f"Memory change: {final_memory - initial_memory:.2f} MB")

        return df_output

    except Exception as e:
        print(f"Error occurred: {str(e)}")
        if all_answers:
            emergency_file = f'MULTI_answer_T5_emergency_{int(time.time())}.csv'
            pd.DataFrame(all_answers).to_csv(emergency_file, index=False, sep='>')
            print(f"Emergency checkpoint saved to {emergency_file}")
        return None

def main():
    print("\nSystem information:")
    print(f"Total memory: {psutil.virtual_memory().total / 1024 / 1024:.2f} MB")
    print(f"Available memory: {psutil.virtual_memory().available / 1024 / 1024:.2f} MB")
    print(f"CPU cores: {os.cpu_count()}")

    try:
        result = generate_all_responses(
            checkpoint_frequency=25,
            start_from_checkpoint=True
        )

        if result is not None:
            print(f"\nSuccessfully generated {len(result)} responses")
        else:
            print("Generation failed")

    except KeyboardInterrupt:
        print("\nProcess interrupted by user. Progress has been saved to checkpoint.")
    except Exception as e:
        print(f"\nUnexpected error: {str(e)}")
        print("Progress has been saved to checkpoint.")

if __name__ == "__main__":
    main()

System information:
Total memory: 15970.10 MB
Available memory: 5559.00 MB
CPU cores: 8
Initial memory usage: 2261.93 MB

Checkpoint saved. Processed 50 answers.
Current memory usage: 2266.15 MB

Completed chunk 1

Checkpoint saved. Processed 100 answers.
Current memory usage: 2264.57 MB

Completed chunk 2

Completed chunk 3

Checkpoint saved. Processed 175 answers.
Current memory usage: 2269.80 MB

Completed chunk 4

Checkpoint saved. Processed 225 answers.
Current memory usage: 2265.43 MB

Completed chunk 5

Checkpoint saved. Processed 275 answers.
Current memory usage: 2271.97 MB

Completed chunk 6

Checkpoint saved. Processed 325 answers.
Current memory usage: 2272.33 MB

Completed chunk 7

Checkpoint saved. Processed 375 answers.
Current memory usage: 2272.76 MB

Completed chunk 8

Checkpoint saved. Processed 425 answers.
Current memory usage: 2273.06 MB

Completed chunk 9

Checkpoint saved. Processed 450 answers.
Current memory usage: 2274.45 MB

Completed chunk 10

Checkpoint saved. Processed 500 answers.
Current memory usage: 2274.95 MB

Completed chunk 11

Checkpoint saved. Processed 550 answers.
Current memory usage: 2271.07 MB

Completed chunk 12

Checkpoint saved. Processed 600 answers.
Current memory usage: 2276.84 MB

Completed chunk 13

Checkpoint saved. Processed 650 answers.
Current memory usage: 2277.20 MB

Completed chunk 14

Checkpoint saved. Processed 700 answers.
Current memory usage: 2275.00 MB

Completed chunk 15

Checkpoint saved. Processed 750 answers.
Current memory usage: 2277.81 MB

Completed chunk 16

Checkpoint saved. Processed 800 answers.
Current memory usage: 2278.70 MB

Completed chunk 17

Checkpoint saved. Processed 850 answers.
Current memory usage: 2278.69 MB

Completed chunk 18

Checkpoint saved. Processed 900 answers.
Current memory usage: 2271.78 MB

Completed chunk 19

Final memory usage: 2279.77 MB
Memory change: 17.84 MB

Successfully generated 940 responses

## SINGLE-SELECT

In [ ]:
import torch
import os
import time
import psutil
import pandas as pd
from transformers import AutoModelForSeq2SeqLM, AutoTokenizer

def generate_text_batch(prompts, model, tokenizer, max_length=1024):
    """Generate text for a batch of prompts with memory management"""
    try:
        with torch.no_grad():
            inputs = tokenizer(
                prompts,
                return_tensors="pt",
                padding=True,
                truncation=True,
                max_length=512
            )

            outputs = model.generate(
                **inputs,
                max_length=max_length,
                num_return_sequences=1,
                do_sample=True,
                temperature=0.8,
                top_p=0.92,
                top_k=50,
                num_beams=5,
                length_penalty=1.0,
                pad_token_id=tokenizer.eos_token_id
            )

            responses = tokenizer.batch_decode(outputs, skip_special_tokens=True)

            # Clean up
            del inputs, outputs
            torch.cuda.empty_cache() if torch.cuda.is_available() else None

            return [r.strip() for r in responses]

    except Exception as e:
        print(f"Error in batch generation: {str(e)}")
        return [None] * len(prompts)

def generate_all_responses(checkpoint_frequency=25, start_from_checkpoint=True):
    try:
        # Monitor initial memory
        initial_memory = get_memory_usage()
        print(f"Initial memory usage: {initial_memory:.2f} MB")

        # Use global model and tokenizer
        global model, tokenizer
        if model is None or tokenizer is None:
            raise Exception("Model not initialized. Please run setup cell first.")

        # Load and prepare data in chunks
        chunk_size = 50
        checkpoint_file = 'SINGLE_answer_T5_checkpoint.csv'

        # Load checkpoint if exists
        processed_pairs = set()
        all_answers = []

        if start_from_checkpoint and os.path.exists(checkpoint_file):
            try:
                checkpoint_df = pd.read_csv(checkpoint_file, sep='>')
                all_answers = checkpoint_df.to_dict('records')
                processed_pairs = {f"{row['question']}_{row['tone']}" for _, row in checkpoint_df.iterrows()}

                if all_answers:
                    last_question = checkpoint_df.iloc[-1]['question']
                    print(f"Loaded {len(all_answers)} existing answers from checkpoint")
                    print(f"Last processed question: {last_question}")
            except Exception as e:
                print(f"Error loading checkpoint: {str(e)}")
                print("Starting from beginning")

        # Process data in chunks
        for chunk_idx, df_chunk in enumerate(pd.read_csv('artificial_answers/SINGLE/SINGLE_answer_combined_total_reshaped.csv',
                                                        sep='>', chunksize=chunk_size)):

            clear_memory()
            unique_questions = df_chunk.drop_duplicates(subset=['question'], keep='first')

            # Skip fully processed chunks
            if all(f"{row['question']}_{tone}" in processed_pairs
                  for _, row in unique_questions.iterrows()
                  for tone in ['verbose', 'concise', 'colloquial', 'explanatory', 'annoyed']):
                continue

            batch_size = 2
            batch_prompts = []
            batch_metadata = []

            for _, row in unique_questions.iterrows():
                for tone, tone_style in {
                    'verbose': 'provide a detailed answer selecting and explaining one option',
                    'concise': 'provide a brief answer with a single clear choice',
                    'colloquial': 'provide a casual answer picking one option',
                    'explanatory': 'provide a clear answer explaining your single selection',
                    'annoyed': 'provide a frustrated answer while still selecting one option'
                }.items():
                    pair_id = f"{row['question']}_{tone}"

                    if pair_id in processed_pairs:
                        continue

                    prompt = f"""You are tasked with analyzing the given question and providing a single-select answer.
                            The answer should select exactly one option in the specified tone.
                            Ensure the response includes only one selection and matches the SINGLE-SELECT format.

                            Question: {row['question']}
                            Available options: {row['options']}
                            Required tone: {tone_style}

                            Provide a single response in the specified tone, selecting only one option without any additional commentary."""

                    batch_prompts.append(prompt)
                    batch_metadata.append({
                        'type': 'SINGLE-SELECT',
                        'question': row['question'],
                        'options': row['options'],
                        'tone': tone
                    })

                    if len(batch_prompts) >= batch_size:
                        clear_memory()

                        responses = generate_text_batch(batch_prompts, model, tokenizer)

                        for metadata, response in zip(batch_metadata, responses):
                            if response:
                                answer_entry = {**metadata, 'answer': response}
                                all_answers.append(answer_entry)
                                processed_pairs.add(f"{metadata['question']}_{metadata['tone']}")

                        if len(all_answers) % checkpoint_frequency == 0:
                            pd.DataFrame(all_answers).to_csv(checkpoint_file, index=False, sep='>')
                            print(f"\nCheckpoint saved. Processed {len(all_answers)} answers.")
                            print(f"Current memory usage: {get_memory_usage():.2f} MB")

                        batch_prompts = []
                        batch_metadata = []
                        time.sleep(0.5)

            # Process remaining prompts in chunk
            if batch_prompts:
                clear_memory()
                responses = generate_text_batch(batch_prompts, model, tokenizer)
                for metadata, response in zip(batch_metadata, responses):
                    if response:
                        answer_entry = {**metadata, 'answer': response}
                        all_answers.append(answer_entry)
                        processed_pairs.add(f"{metadata['question']}_{metadata['tone']}")

            print(f"\nCompleted chunk {chunk_idx + 1}")

        # Save final results
        clear_memory()
        df_output = pd.DataFrame(all_answers)
        df_output.to_csv('SINGLE_answer_T5_all.csv', index=False, sep='>')

        if os.path.exists(checkpoint_file):
            os.remove(checkpoint_file)

        final_memory = get_memory_usage()
        print(f"\nFinal memory usage: {final_memory:.2f} MB")
        print(f"Memory change: {final_memory - initial_memory:.2f} MB")

        return df_output

    except Exception as e:
        print(f"Error occurred: {str(e)}")
        if all_answers:
            emergency_file = f'SINGLE_answer_T5_emergency_{int(time.time())}.csv'
            pd.DataFrame(all_answers).to_csv(emergency_file, index=False, sep='>')
            print(f"Emergency checkpoint saved to {emergency_file}")
        return None

def main():
    print("\nSystem information:")
    print(f"Total memory: {psutil.virtual_memory().total / 1024 / 1024:.2f} MB")
    print(f"Available memory: {psutil.virtual_memory().available / 1024 / 1024:.2f} MB")
    print(f"CPU cores: {os.cpu_count()}")

    try:
        result = generate_all_responses(
            checkpoint_frequency=25,
            start_from_checkpoint=True
        )

        if result is not None:
            print(f"\nSuccessfully generated {len(result)} responses")
        else:
            print("Generation failed")

    except KeyboardInterrupt:
        print("\nProcess interrupted by user. Progress has been saved to checkpoint.")
    except Exception as e:
        print(f"\nUnexpected error: {str(e)}")
        print("Progress has been saved to checkpoint.")

if __name__ == "__main__":
    main()

System information:
Total memory: 15970.10 MB
Available memory: 4881.48 MB
CPU cores: 8
Initial memory usage: 2279.56 MB

Checkpoint saved. Processed 50 answers.
Current memory usage: 2278.40 MB

Completed chunk 1

Checkpoint saved. Processed 100 answers.
Current memory usage: 2277.79 MB

Completed chunk 2

Checkpoint saved. Processed 150 answers.
Current memory usage: 2277.60 MB

Completed chunk 3

Checkpoint saved. Processed 200 answers.
Current memory usage: 2278.18 MB

Completed chunk 4

Checkpoint saved. Processed 250 answers.
Current memory usage: 2282.14 MB

Completed chunk 5

Checkpoint saved. Processed 300 answers.
Current memory usage: 2281.05 MB

Completed chunk 6

Checkpoint saved. Processed 350 answers.
Current memory usage: 2280.67 MB

Completed chunk 7

Checkpoint saved. Processed 400 answers.
Current memory usage: 2278.37 MB

Completed chunk 8

Checkpoint saved. Processed 450 answers.
Current memory usage: 2282.07 MB

Completed chunk 9

Checkpoint saved. Processed 500 answers.
Current memory usage: 2274.55 MB

Completed chunk 10

Checkpoint saved. Processed 550 answers.
Current memory usage: 2282.09 MB

Completed chunk 11

Checkpoint saved. Processed 600 answers.
Current memory usage: 2281.46 MB

Completed chunk 12

Checkpoint saved. Processed 650 answers.
Current memory usage: 2279.11 MB

Completed chunk 13

Completed chunk 14

Checkpoint saved. Processed 725 answers.
Current memory usage: 2279.63 MB

Completed chunk 15

Final memory usage: 2275.34 MB
Memory change: -4.21 MB

Successfully generated 740 responses

## Combine all files into one

In [6]:
import pandas as pd
import os

def combine_t5_datasets():
    try:
        # Define the directory and files
        t5_dir = 'T5_datasets'
        output_file = os.path.join(t5_dir, 'test_all_T5_answers_combined.csv')

        # List all T5 answer files
        t5_files = [
            'SINGLE_answer_T5_all.csv',
            'MULTI_answer_T5_all.csv',
            'DATE_answer_T5_all.csv',
            'TEXT_answer_T5_all.csv',
            'NUMBER_answer_T5_all.csv'
        ]

        # Initialize empty list to store all dataframes
        all_data = []

        # Read and combine each file
        for file in t5_files:
            file_path = os.path.join(t5_dir, file)
            if os.path.exists(file_path):
                try:
                    # Read file with '>' separator
                    df = pd.read_csv(file_path, sep='>')

                    # Ensure type is correctly set for NUMBER files
                    if 'NUMBER' in file:
                        df['type'] = 'NUMBER'

                    print(f"Loaded {file}: {len(df)} rows")
                    all_data.append(df)
                except Exception as e:
                    print(f"Error reading {file}: {str(e)}")
            else:
                print(f"File not found: {file}")

        # Combine all dataframes
        if all_data:
            combined_df = pd.concat(all_data, ignore_index=True)

            # Ensure consistent column order
            columns = ['type', 'question', 'options', 'answer', 'tone']
            combined_df = combined_df[columns]

            # Save combined dataset
            combined_df.to_csv(output_file, sep='>', index=False)

            print("\nCombination complete:")
            print(f"Total rows: {len(combined_df)}")
            print(f"File saved as: {output_file}")

            # Print distribution of question types
            print("\nDistribution of question types:")
            print(combined_df['type'].value_counts())

            # Verify all types are present
            types_present = combined_df['type'].unique()
            print("\nTypes present in combined data:")
            print(types_present)

            # Check for any missing types
            expected_types = {'SINGLE-SELECT', 'MULTI-SELECT', 'DATE', 'TEXT', 'NUMBER'}
            missing_types = expected_types - set(types_present)
            if missing_types:
                print("\nWarning: Missing question types:", missing_types)

            return combined_df
        else:
            print("No data to combine")
            return None

    except Exception as e:
        print(f"Error combining datasets: {str(e)}")
        return None

# Run the combination
print("Starting dataset combination...")
combined_data = combine_t5_datasets()

# Display sample and statistics if successful
if combined_data is not None:
    print("\nSample of combined data:")
    print(combined_data.head())

    print("\nSummary statistics:")
    print("Number of unique questions:", combined_data['question'].nunique())
    print("Number of NaN values:", combined_data['answer'].isna().sum())
    print("Number of unique tones:", combined_data['tone'].nunique())
    for qtype in combined_data['type'].unique():
        type_count = len(combined_data[combined_data['type'] == qtype])
        print(f"{qtype} questions: {type_count}")

Starting dataset combination...
Loaded SINGLE_answer_T5_all.csv: 740 rows
Loaded MULTI_answer_T5_all.csv: 940 rows
Loaded DATE_answer_T5_all.csv: 930 rows
Loaded TEXT_answer_T5_all.csv: 878 rows
Loaded NUMBER_answer_T5_all.csv: 909 rows

Combination complete:
Total rows: 4397
File saved as: T5_datasets\test_all_T5_answers_combined.csv

Distribution of question types:
type
MULTI-SELECT     940
DATE             930
NUMBER           909
TEXT             878
SINGLE-SELECT    740
Name: count, dtype: int64

Types present in combined data:
['SINGLE-SELECT' 'MULTI-SELECT' 'DATE' 'TEXT' 'NUMBER']

Sample of combined data:
            type                                    question  options answer
0  SINGLE-SELECT  Are you currently using a similar product?  Yes; No    Yes  \
1  SINGLE-SELECT  Are you currently using a similar product?  Yes; No   Yes.
2  SINGLE-SELECT  Are you currently using a similar product?  Yes; No   Yes.
3  SINGLE-SELECT  Are you currently using a similar product?  Yes; No   Yes.
4  SINGLE-SELECT  Are you currently using a similar product?  Yes; No   Yes.

          tone
0      verbose
1      concise
2   colloquial
3  explanatory
4      annoyed

Summary statistics:
Number of unique questions: 881
Number of NaN values: 0
Number of unique tones: 5
SINGLE-SELECT questions: 740
MULTI-SELECT questions: 940
DATE questions: 930
TEXT questions: 878
NUMBER questions: 909

# Evaluating Q&A Datasets:

## 1. Preprocessing
Clean and format the dataset for the selected QA models. Ensuring that each entry in the dataset includes the following:
1. Question: The original question.
2. Type: The question type (DATE, MULTI_SELECT, etc.).
2. Options: The available options for the question.
3. Answers: All generated answers (from Gemini and FLAN-T5) in the 5 tones.
4. Labels: Gemini and Bart labels.
5. Assign Difficulty Levels: Label answer based on its length with a difficulty level (short, moderate, or long)

## 2. Fine-Tuning
For this task we are using the model "roberta-base"

The goal is:

1. to evaluate how well a fine-tuned QA model performs. Use the tone labels and difficulty levels to analyze their effect on fine-tuning performance. Analyze whether the model struggles with certain tones or difficulty levels. This helps assess the model's ability to generalize across tones and measures how well the generated answers align with the tone labels (compare model outputs with Gemini and FLAN-T5 tones).

2. Compare the performance of Gemini and T5 models when generating the dataset. Break down performance across DATE, MULTI_SELECT, etc. using standard QA evaluation metrics

## 1. Preprocessing

In [ ]:
import pandas as pd
import re

def remove_repeated_phrases(text):
    # Normalize whitespace and remove all punctuation including apostrophes
    text = re.sub(r'\s+', ' ', text)  # Replace multiple spaces with a single space
    text = re.sub(r"[^\w\s]", '', text)  # Remove all punctuation including apostrophes

    # Define the pattern to match repeated sequences of up to 10 words
    pattern = r"(\b\w+\b(?:\s+\b\w+\b){0,9})\s*(?:\1\s*){1,}"

    # Apply the pattern to remove repeated sequences
    result = re.sub(pattern, r'\1', text)

    return result

# Load the CSV file
t5_data = pd.read_csv('all_T5_answers_combined.csv', sep='>')

# Assuming the column to clean is named 'answer'
# Apply the cleaning function to the 'answer' column
t5_data['answer'] = t5_data['answer'].apply(remove_repeated_phrases)

# Save the cleaned data to a new CSV file
t5_data.to_csv('cleaned_all_T5_answers_combined.csv', index=False, encoding='utf-8')

print(f"Cleaned data saved")

Cleaned data saved

In [ ]:
import pandas as pd
import numpy as np

def load_datasets():
    try:
        # Load Gemini answers with labels
        gemini_df = pd.read_csv('artificial_answers/all_answers_combined_reshaped_with_BART_large_mnli_MULTI_SINGLE_TEXT_actuallyfixedlabels.csv',
                               sep='>')
        print("Gemini DataFrame columns:", gemini_df.columns.tolist())

        # Load T5 answers
        t5_df = pd.read_csv('T5_datasets/cleaned_all_T5_answers_combined.csv',
                           sep='>')
        print("T5 DataFrame columns:", t5_df.columns.tolist())

        return gemini_df, t5_df

    except Exception as e:
        print(f"Error loading datasets: {str(e)}")
        return None, None

def merge_and_format_datasets():
    gemini_df, t5_df = load_datasets()
    if gemini_df is None or t5_df is None:
        return None

    # Skip the first row which contains column names
    gemini_df = gemini_df.iloc[1:]
    t5_df = t5_df.iloc[1:]

    # Create base DataFrame with unique questions and type
    questions = pd.concat([gemini_df['question'], t5_df['question']]).unique()
    base_data = []

    for q in questions:
        # Try to get data from Gemini first, then T5
        q_data = gemini_df[gemini_df['question'] == q].iloc[0] if not gemini_df[gemini_df['question'] == q].empty else \
                t5_df[t5_df['question'] == q].iloc[0]

        base_data.append({
            'question': q,
            'type': q_data['type'],
            'options': q_data['options']
        })

    merged_df = pd.DataFrame(base_data)

    # Add T5 answers for each tone
    for tone in ['verbose', 'concise', 'colloquial', 'explanatory', 'annoyed']:
        for q in questions:
            tone_data = t5_df[(t5_df['question'] == q) & (t5_df['tone'] == tone)]
            if not tone_data.empty:
                merged_df.loc[merged_df['question'] == q, f't5_answer_{tone}'] = tone_data['answer'].iloc[0]

    # Add Gemini answers and labels for each tone
    for tone in ['verbose', 'concise', 'colloquial', 'explanatory', 'annoyed']:
        for q in questions:
            tone_data = gemini_df[(gemini_df['question'] == q) &
                                (gemini_df['answer_category'] == tone)]
            if not tone_data.empty:
                merged_df.loc[merged_df['question'] == q, f'gemini_answer_{tone}'] = tone_data['answer'].iloc[0]
                merged_df.loc[merged_df['question'] == q, f'gemini_label_{tone}'] = tone_data['answer_label_GEMINI'].iloc[0]

    # Remove specified columns
    columns_to_remove = [
        'gemini_label_verbose',
        'gemini_label_concise',
        'gemini_label_colloquial',
        'gemini_label_explanatory',
        'gemini_label_annoyed'
    ]
    merged_df.drop(columns=columns_to_remove, inplace=True, errors='ignore')

    return merged_df

def main():
    # Debug: Print file contents
    print("\nChecking T5 dataset...")
    try:
        t5_df = pd.read_csv('T5_datasets/cleaned_all_T5_answers_combined.csv', sep='>')
        print("T5 columns:", t5_df.columns.tolist())
        print("T5 sample row:", t5_df.iloc[0].to_dict())
    except Exception as e:
        print("Error reading T5 file:", str(e))

    print("\nChecking Gemini dataset...")
    try:
        gemini_df = pd.read_csv('artificial_answers/all_answers_combined_reshaped_with_BART_large_mnli_MULTI_SINGLE_labels.csv', sep='>')
        print("Gemini columns:", gemini_df.columns.tolist())
        print("Gemini sample row:", gemini_df.iloc[0].to_dict())
    except Exception as e:
        print("Error reading Gemini file:", str(e))

    merged_df = merge_and_format_datasets()
    if merged_df is not None:
        # Save with utf-8 encoding to handle special characters
        merged_df.to_csv('preprocessed_all_dataset.csv', index=False, encoding='utf-8')
        print("Successfully created preprocessed_dataset.csv")

        # Print some statistics about the merged dataset
        print("\nMerged Dataset Statistics:")
        print(f"Total number of questions: {len(merged_df)}")
        print("\nColumns in merged dataset:")
        print(merged_df.columns.tolist())
        print("\nSample of merged dataset:")
        print(merged_df.head())
    else:
        print("Failed to create dataset")

if __name__ == "__main__":
    main()

Checking T5 dataset...
T5 columns: ['type,question,options,answer,tone']
T5 sample row: {'type,question,options,answer,tone': 'SINGLE-SELECT,Are you currently using a similar product?,Yes; No,Yes,verbose'}

Checking Gemini dataset...
Gemini columns: ['type', 'question', 'options', 'answer', 'answer_label_GEMINI', 'answer_category', 'answer_label_BART_large_mnli']
Gemini sample row: {'type': 'type', 'question': 'question', 'options': "['options']", 'answer': 'answer', 'answer_label_GEMINI': 'answer_label_GEMINI', 'answer_category': 'answer_category', 'answer_label_BART_large_mnli': nan}
Gemini DataFrame columns: ['type', 'question', 'options', 'answer', 'answer_label_GEMINI', 'answer_category', 'answer_label_BART_large_mnli']
T5 DataFrame columns: ['type,question,options,answer,tone']

KeyError: 'question'

## Fine-Tuning:

In [1]:
pip install transformers datasets evaluate scikit-learn

Requirement already satisfied: transformers in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (4.48.1)
Requirement already satisfied: datasets in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (3.2.0)
Requirement already satisfied: evaluate in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (0.4.3)
Requirement already satisfied: scikit-learn in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (1.6.1)
Requirement already satisfied: filelock in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from transformers) (3.11.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.24.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from transformers) (0.27.1)
Requirement already satisfied: numpy>=1.17 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from transformers) (1.26.2)
Requirement already satisfied: packaging>=20.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from transformers) (23.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from transformers) (6.0)
Requirement already satisfied: regex!=2019.12.17 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from transformers) (2024.11.6)
Requirement already satisfied: requests in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from transformers) (0.5.2)
Requirement already satisfied: tqdm>=4.27 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: pyarrow>=15.0.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from datasets) (19.0.0)
Requirement already satisfied: dill<0.3.9,>=0.3.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from datasets) (0.3.8)
Requirement already satisfied: pandas in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from datasets) (2.0.1)
Requirement already satisfied: xxhash in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from datasets) (3.5.0)
Requirement already satisfied: multiprocess<0.70.17 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from datasets) (0.70.16)
Requirement already satisfied: fsspec<=2024.9.0,>=2023.1.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from fsspec[http]<=2024.9.0,>=2023.1.0->datasets) (2023.12.0)
Requirement already satisfied: aiohttp in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from datasets) (3.11.11)
Requirement already satisfied: scipy>=1.6.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->datasets) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->datasets) (1.3.2)
Requirement already satisfied: async-timeout<6.0,>=4.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->datasets) (5.0.1)
Requirement already satisfied: attrs>=17.3.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->datasets) (23.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->datasets) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->datasets) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->datasets) (0.2.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from aiohttp->datasets) (1.18.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub<1.0,>=0.24.0->transformers) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from requests->transformers) (2022.12.7)
Requirement already satisfied: colorama in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from pandas->datasets) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from pandas->datasets) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from pandas->datasets) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.2->pandas->datasets) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
# Run these installations first in separate cells
!pip install sentence-transformers
!pip install nltk

Requirement already satisfied: sentence-transformers in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (3.4.0)
Requirement already satisfied: transformers<5.0.0,>=4.41.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (4.48.1)
Requirement already satisfied: tqdm in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (4.67.1)
Requirement already satisfied: torch>=1.11.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (2.5.1+cu118)
Requirement already satisfied: scikit-learn in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (1.10.1)
Requirement already satisfied: huggingface-hub>=0.20.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (0.27.1)
Requirement already satisfied: Pillow in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from sentence-transformers) (10.0.1)
Requirement already satisfied: filelock in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (3.11.0)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2023.12.0)
Requirement already satisfied: packaging>=20.9 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (23.1)
Requirement already satisfied: pyyaml>=5.1 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (6.0)
Requirement already satisfied: requests in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (2.32.3)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from huggingface-hub>=0.20.0->sentence-transformers) (4.12.2)
Requirement already satisfied: networkx in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.1)
Requirement already satisfied: jinja2 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: sympy==1.13.1 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from torch>=1.11.0->sentence-transformers) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from sympy==1.13.1->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: colorama in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from tqdm->sentence-transformers) (0.4.6)
Requirement already satisfied: numpy>=1.17 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (1.26.2)
Requirement already satisfied: regex!=2019.12.17 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (2024.11.6)
Requirement already satisfied: tokenizers<0.22,>=0.21 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.21.0)
Requirement already satisfied: safetensors>=0.4.1 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from transformers<5.0.0,>=4.41.0->sentence-transformers) (0.5.2)
Requirement already satisfied: joblib>=1.2.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn->sentence-transformers) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn->sentence-transformers) (3.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from jinja2->torch>=1.11.0->sentence-transformers) (2.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from requests->huggingface-hub>=0.20.0->sentence-transformers) (2022.12.7)

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: nltk in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (3.9.1)
Requirement already satisfied: click in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: joblib in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from nltk) (1.4.2)
Requirement already satisfied: regex>=2021.8.3 in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from nltk) (2024.11.6)
Requirement already satisfied: tqdm in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from nltk) (4.67.1)
Requirement already satisfied: colorama in c:\users\carol\appdata\local\programs\python\python310\lib\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from datasets import Dataset, DatasetDict
from transformers import RobertaTokenizer, RobertaForSequenceClassification, TrainingArguments, Trainer, RobertaConfig
from transformers import DataCollatorWithPadding
import pandas as pd
import numpy as np
import torch
from sentence_transformers import SentenceTransformer, util
import gc
from evaluate import load
import re
from tqdm import tqdm
import logging

class CustomRobertaModel(RobertaForSequenceClassification):
    def forward(self, input_ids=None, attention_mask=None, labels=None):
        # Pass inputs through the base model
        outputs = self.roberta(
            input_ids=input_ids,
            attention_mask=attention_mask,
        )
        # Get the `[CLS]` token embedding
        cls_embedding = outputs.last_hidden_state[:, 0, :]  # Shape: [batch_size, hidden_size]

        # Apply the classifier head
        logits = self.classifier(cls_embedding)  # Shape: [batch_size, num_labels]

        loss = None
        if labels is not None:
            loss = cosine_similarity_loss(logits, labels)

        return {"loss": loss, "logits": logits} if loss is not None else {"logits": logits}


# Initialize evaluation metrics
rouge = load('rouge')
meteor = load('meteor')
bleu = load('bleu')
semantic_model = SentenceTransformer('all-MiniLM-L6-v2')  # For semantic similarity

# Enable garbage collection and set memory limits
gc.enable()
torch.cuda.empty_cache() if torch.cuda.is_available() else None

# Load data for Gemini answers
train_data_path = "fine tuning datasets\preprocessed_dataset_only_gemini_concise.csv"
test_data_path = "fine tuning datasets\preprocessed_dataset_only_gemini_verbose.csv"

train_data = pd.read_csv(train_data_path)
test_data = pd.read_csv(test_data_path)

print("Train Data Columns:", train_data.columns)
print("Test Data Columns:", test_data.columns)

# Modify the format_data function to handle NaN values more gracefully
def format_data(df, answer_column):
    formatted_data = []
    for _, row in df.iterrows():
        question = str(row.get("question", "")).strip()
        options = str(row.get("options", "")).strip()
        answer = str(row.get(answer_column, "")).strip() if pd.notna(row.get(answer_column)) else "[NO ANSWER]"

        if question and options:  # Keep rows even if the answer is missing
            formatted_data.append({"question": question, "options": options, "answer": answer})
        else:
            logging.warning(f"Dropping row due to missing question or options: {row}")
    return Dataset.from_pandas(pd.DataFrame(formatted_data))

# Preprocess and format the datasets
train_dataset = format_data(train_data, answer_column="gemini_answer_concise")
test_dataset = format_data(test_data, answer_column="gemini_answer_verbose")

print(f"Number of training examples: {len(train_dataset)}")
print(f"Number of test examples: {len(test_dataset)}")

dataset = DatasetDict({
    'train': train_dataset,
    'test': test_dataset
})

# Load RoBERTa tokenizer and model
model_name = "roberta-base"  # Replace with "roberta-large" for a larger model
tokenizer = RobertaTokenizer.from_pretrained(model_name)
config = RobertaConfig.from_pretrained(model_name)

config.num_labels = 384  # Set this to the size of your embeddings
model = CustomRobertaModel.from_pretrained(model_name, config=config)
model.classifier = torch.nn.Linear(model.config.hidden_size, 384)

def preprocess_function(examples, split="train"):
    # Handle both single and batched inputs
    questions = examples["question"]
    options = examples["options"]
    answers = examples["answer"]

    # Ensure no None values exist
    assert all(isinstance(q, str) for q in questions), "Questions contain non-string values"
    assert all(isinstance(o, str) for o in options), "Options contain non-string values"
    assert all(isinstance(a, str) for a in answers), "Answers contain non-string values"

    tokenized_inputs = tokenizer(
        questions,
        options,
        truncation=True,
        max_length=256,
        padding="max_length",
    )
    assert all(tokenized_inputs["input_ids"]), "Found None in tokenized input_ids!"

    # Convert answers to embeddings
    embeddings = semantic_model.encode(answers, convert_to_tensor=True).cpu().numpy()

    if embeddings is None or len(embeddings) == 0:
        raise ValueError(f"Semantic model returned empty embeddings for {split} data.")

    # Debug: Print shapes of input_ids, attention_mask, and labels
    print(f"Split: {split}")
    print(f"input_ids shape: {np.array(tokenized_inputs['input_ids']).shape}")
    print(f"attention_mask shape: {np.array(tokenized_inputs['attention_mask']).shape}")
    print(f"labels shape: {embeddings.shape}")

    # Ensure the function returns a dictionary with consistent lengths
    return {
        "input_ids": tokenized_inputs["input_ids"],
        "attention_mask": tokenized_inputs["attention_mask"],
        "labels": embeddings  # Ensure each embedding is a separate element
    }


# Tokenize datasets with labels
tokenized_datasets = DatasetDict()

# Process each split in the dataset
for split in ["train", "test"]:
    # Apply the preprocessing function to each example in the dataset
    tokenized_datasets[split] = dataset[split].map(
        lambda examples: preprocess_function(examples, split=split),
        batched=True,
        remove_columns=["question", "options", "answer"],  # Specify columns to remove
    )

# Data collator for padding
data_collator = DataCollatorWithPadding(tokenizer)

# EM and F1 Score calculations
def normalize_text(text):
    """Normalize text by lowercasing, removing articles, punctuation, and extra whitespace."""
    text = text.lower()
    text = re.sub(r'\b(a|an|the)\b', ' ', text)
    text = re.sub(r'[^\w\s]', '', text)
    return ' '.join(text.split())

def cosine_similarity_loss(pred, target):
    # Calculate cosine similarity loss
    return 1 - torch.nn.functional.cosine_similarity(pred, target).mean()

def compute_metrics(eval_pred):
    predictions, labels = eval_pred

    # Ensure predictions and labels are tensors
    if predictions is None or labels is None:
        logging.error("Predictions or labels are None!")
        return {}

    # Convert predictions and labels to tensors if they aren't already
    predictions = torch.tensor(predictions) if not isinstance(predictions, torch.Tensor) else predictions
    labels = torch.tensor(labels) if not isinstance(labels, torch.Tensor) else labels

    # Compute cosine similarity
    cosine_similarities = torch.nn.functional.cosine_similarity(predictions, labels, dim=-1)
    mean_cosine_similarity = torch.mean(cosine_similarities).item()

    # Compute Euclidean distance
    euclidean_distances = torch.norm(predictions - labels, dim=-1)
    mean_euclidean_distance = torch.mean(euclidean_distances).item()

    # Compute Pearson correlation
    predictions_flat = predictions.flatten()
    labels_flat = labels.flatten()
    pearson_correlation = np.corrcoef(predictions_flat.cpu().numpy(), labels_flat.cpu().numpy())[0, 1]

    # Compute Mean Squared Error (MSE)
    mse = torch.nn.functional.mse_loss(predictions, labels).item()

    # Print metrics for debugging
    print(f"Mean Cosine Similarity: {mean_cosine_similarity}")
    print(f"Mean Euclidean Distance: {mean_euclidean_distance}")
    print(f"Pearson Correlation: {pearson_correlation}")
    print(f"Mean Squared Error: {mse}")

    return {
        "mean_cosine_similarity": mean_cosine_similarity,
        "mean_euclidean_distance": mean_euclidean_distance,
        "pearson_correlation": pearson_correlation,
        "mse": mse,
    }

# Training arguments
training_args = TrainingArguments(
    output_dir="./roberta_results_gemini_concise_verbose",
    evaluation_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    num_train_epochs=3,
    weight_decay=0.01,
    save_strategy="epoch",
    save_total_limit=1,
    logging_dir="./roberta_logs_gemini",
    load_best_model_at_end=True,
    report_to="none",
    remove_unused_columns=False,  # Add this line
    fp16=True,  # Enable mixed precision
    gradient_accumulation_steps=4,  # Accumulate gradients over 4 steps
)

from transformers import Trainer

class CustomTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        # Forward pass
        outputs = model(**inputs)
        logits = outputs.get("logits")

        # Get the labels
        labels = inputs.get("labels")

        # Compute custom loss
        loss = cosine_similarity_loss(logits, labels)

        return (loss, outputs) if return_outputs else loss


# Use the custom trainer
trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

# Train and evaluate
trainer.train()

Format the data set to remove all other types of answers and only keep the concise and verbose answers

In [ ]:
import pandas as pd

def keep_only_gemini_concise(file_path, output_path):
    try:
        # Load the dataset
        df = pd.read_csv(file_path)

        # Define columns to remove
        columns_to_remove = [
            't5_answer_colloquial', 't5_answer_explanatory', 't5_answer_annoyed',
            'gemini_answer_colloquial', 'gemini_answer_explanatory', 'gemini_answer_annoyed',
            't5_answer_verbose','gemini_answer_verbose', 't5_answer_concise'
        ]

        # Remove the specified columns
        df.drop(columns=columns_to_remove, inplace=True, errors='ignore')

        # Save the updated dataset
        df.to_csv(output_path, index=False, encoding='utf-8')
        print(f"Successfully updated the dataset and saved to {output_path}")

    except Exception as e:
        print(f"An error occurred: {str(e)}")

def keep_only_gemini_verbose(file_path, output_path):
    try:
        # Load the dataset
        df = pd.read_csv(file_path)

        # Define columns to remove
        columns_to_remove = [
            't5_answer_colloquial', 't5_answer_explanatory', 't5_answer_annoyed',
            'gemini_answer_colloquial', 'gemini_answer_explanatory', 'gemini_answer_annoyed',
            't5_answer_verbose','gemini_answer_concise', 't5_answer_concise'
        ]

        # Remove the specified columns
        df.drop(columns=columns_to_remove, inplace=True, errors='ignore')

        # Save the updated dataset
        df.to_csv(output_path, index=False, encoding='utf-8')
        print(f"Successfully updated the dataset and saved to {output_path}")

    except Exception as e:
        print(f"An error occurred: {str(e)}")

def keep_only_t5_concise(file_path, output_path):
    try:
        # Load the dataset
        df = pd.read_csv(file_path)

        # Define columns to remove
        columns_to_remove = [
            't5_answer_colloquial', 't5_answer_explanatory', 't5_answer_annoyed',
            'gemini_answer_colloquial', 'gemini_answer_explanatory', 'gemini_answer_annoyed',
            't5_answer_verbose','gemini_answer_verbose', 'gemini_answer_concise'
        ]

        # Remove the specified columns
        df.drop(columns=columns_to_remove, inplace=True, errors='ignore')

        # Save the updated dataset
        df.to_csv(output_path, index=False, encoding='utf-8')
        print(f"Successfully updated the dataset and saved to {output_path}")

    except Exception as e:
        print(f"An error occurred: {str(e)}")

def keep_only_t5_verbose(file_path, output_path):
    try:
        # Load the dataset
        df = pd.read_csv(file_path)

        # Define columns to remove
        columns_to_remove = [
            't5_answer_colloquial', 't5_answer_explanatory', 't5_answer_annoyed',
            'gemini_answer_colloquial', 'gemini_answer_explanatory', 'gemini_answer_annoyed',
            't5_answer_concise','gemini_answer_verbose', 'gemini_answer_concise'
        ]

        # Remove the specified columns
        df.drop(columns=columns_to_remove, inplace=True, errors='ignore')

        # Save the updated dataset
        df.to_csv(output_path, index=False, encoding='utf-8')
        print(f"Successfully updated the dataset and saved to {output_path}")

    except Exception as e:
        print(f"An error occurred: {str(e)}")

# File paths
input_file = 'preprocessed_dataset.csv'
output_file1 = 'fine tuning datasets\preprocessed_dataset_only_gemini_concise.csv'
output_file2 = 'fine tuning datasets\preprocessed_dataset_only_gemini_verbose.csv'
output_file3 = 'fine tuning datasets\preprocessed_dataset_only_t5_concise.csv'
output_file4 = 'fine tuning datasets\preprocessed_dataset_only_t5_verbose.csv'

# Run the function
keep_only_gemini_concise(input_file, output_file1)
keep_only_gemini_verbose(input_file, output_file2)
keep_only_t5_concise(input_file, output_file3)
keep_only_t5_verbose(input_file, output_file4)

Successfully updated the dataset and saved to preprocessed_dataset_concise.csv
Successfully updated the dataset and saved to preprocessed_dataset_verbose.csv

In [2]:
from datasets import Dataset, DatasetDict
from transformers import RobertaTokenizer, RobertaForSequenceClassification, TrainingArguments, Trainer, RobertaConfig
from transformers import DataCollatorWithPadding
import pandas as pd
import numpy as np
import torch
from sentence_transformers import SentenceTransformer, util
import gc
from evaluate import load
import re
from tqdm import tqdm
import logging


class CustomRobertaModel(RobertaForSequenceClassification):
    def forward(self, input_ids=None, attention_mask=None, labels=None):
        # Pass inputs through the base model
        outputs = self.roberta(
            input_ids=input_ids,
            attention_mask=attention_mask,
        )
        # Get the `[CLS]` token embedding
        cls_embedding = outputs.last_hidden_state[:, 0, :]  # Shape: [batch_size, hidden_size]

        # Apply the classifier head
        logits = self.classifier(cls_embedding)  # Shape: [batch_size, num_labels]

        loss = None
        if labels is not None:
            loss = cosine_similarity_loss(logits, labels)

        return {"loss": loss, "logits": logits} if loss is not None else {"logits": logits}
    
semantic_model = SentenceTransformer('all-MiniLM-L6-v2')  # For semantic similarity

# Enable garbage collection and set memory limits
gc.enable()
torch.cuda.empty_cache() if torch.cuda.is_available() else None

# Load data for Gemini answers
train_data_path = "fine tuning datasets\preprocessed_dataset_only_gemini_concise.csv"  # Gemini concise training data
test_data_path = "fine tuning datasets\preprocessed_dataset_only_gemini_verbose.csv"   # Gemini verbose evaluation data

train_data = pd.read_csv(train_data_path)
test_data = pd.read_csv(test_data_path)

print("Train Data Columns:", train_data.columns)
print("Test Data Columns:", test_data.columns)

# Define formatting function for dataset
def format_data(df, answer_column):
    formatted_data = []
    for _, row in df.iterrows():
        # Ensure each field is a string before stripping
        question = str(row.get('question', '')).strip() if pd.notna(row.get('question')) else ''
        options = str(row.get('options', '')).strip() if pd.notna(row.get('options')) else ''
        answer = str(row.get(answer_column, '')).strip() if pd.notna(row.get(answer_column)) else ''

        if question and options and answer:  # Ensure all fields are non-empty
            formatted_data.append({
                'question': question,
                'options': options,
                'answer': answer,
            })
        else:
            logging.warning(f"Dropping row due to missing or empty fields: {row}")
    return Dataset.from_pandas(pd.DataFrame(formatted_data))

# Format datasets
train_dataset = format_data(train_data, answer_column='gemini_answer_concise')  # Training on Gemini concise
test_dataset = format_data(test_data, answer_column='gemini_answer_verbose')   # Evaluate on Gemini verbose


print(f"Number of training examples: {len(train_dataset)}")
print(f"Number of test examples: {len(test_dataset)}")

dataset = DatasetDict({
    'train': train_dataset,
    'test': test_dataset
})

# Load RoBERTa tokenizer and model
model_name = "roberta-base"  # Replace with "roberta-large" for a larger model
tokenizer = RobertaTokenizer.from_pretrained(model_name)
config = RobertaConfig.from_pretrained(model_name)

config.num_labels = 384  # Set this to the size of your embeddings
model = CustomRobertaModel.from_pretrained(model_name, config=config)
model.classifier = torch.nn.Linear(model.config.hidden_size, 384)

def preprocess_function(examples, split="train"):
    # Handle both single and batched inputs
    questions = examples["question"]
    options = examples["options"]
    answers = examples["answer"]

    # Ensure no None values exist
    assert all(isinstance(q, str) for q in questions), "Questions contain non-string values"
    assert all(isinstance(o, str) for o in options), "Options contain non-string values"
    assert all(isinstance(a, str) for a in answers), "Answers contain non-string values"

    tokenized_inputs = tokenizer(
        questions,
        options,
        truncation=True,
        max_length=256,
        padding="max_length",
    )

    # Convert answers to embeddings
    embeddings = semantic_model.encode(answers, convert_to_tensor=True).cpu().numpy()

    if embeddings is None or len(embeddings) == 0:
        raise ValueError(f"Semantic model returned empty embeddings for {split} data.")


    # Ensure the function returns a dictionary with consistent lengths
    return {
        "input_ids": tokenized_inputs["input_ids"],
        "attention_mask": tokenized_inputs["attention_mask"],
        "labels": embeddings  # Ensure each embedding is a separate element
    }


# Tokenize datasets with labels
tokenized_datasets = DatasetDict()

# Process each split in the dataset
for split in ["train", "test"]:
    # Apply the preprocessing function to each example in the dataset
    tokenized_datasets[split] = dataset[split].map(
        lambda examples: preprocess_function(examples, split=split),
        batched=True,
        remove_columns=["question", "options", "answer"],  # Specify columns to remove
    )
tokenized_train = tokenized_datasets["train"][4]

tokenized_test = tokenized_datasets["test"][4]
print(tokenized_train)  # Show the first 5 examples
print(tokenized_test)


# Data collator for padding
data_collator = DataCollatorWithPadding(tokenizer)

def cosine_similarity_loss(pred, target):
    # Calculate cosine similarity loss
    return 1 - torch.nn.functional.cosine_similarity(pred, target).mean()

def compute_metrics(eval_pred):
    predictions, labels = eval_pred

    # Ensure predictions and labels are tensors
    if predictions is None or labels is None:
        logging.error("Predictions or labels are None!")
        return {}

    # Convert predictions and labels to tensors if they aren't already
    predictions = torch.tensor(predictions) if not isinstance(predictions, torch.Tensor) else predictions
    labels = torch.tensor(labels) if not isinstance(labels, torch.Tensor) else labels

    # Compute cosine similarity
    cosine_similarities = torch.nn.functional.cosine_similarity(predictions, labels, dim=-1)
    mean_cosine_similarity = torch.mean(cosine_similarities).item()

    # Compute Euclidean distance
    euclidean_distances = torch.norm(predictions - labels, dim=-1)
    mean_euclidean_distance = torch.mean(euclidean_distances).item()

    # Compute Pearson correlation
    predictions_flat = predictions.flatten()
    labels_flat = labels.flatten()
    pearson_correlation = np.corrcoef(predictions_flat.cpu().numpy(), labels_flat.cpu().numpy())[0, 1]

    # Compute Mean Squared Error (MSE)
    mse = torch.nn.functional.mse_loss(predictions, labels).item()

    # Print metrics for debugging
    print(f"Mean Cosine Similarity: {mean_cosine_similarity}")
    print(f"Mean Euclidean Distance: {mean_euclidean_distance}")
    print(f"Pearson Correlation: {pearson_correlation}")
    print(f"Mean Squared Error: {mse}")

    return {
        "mean_cosine_similarity": mean_cosine_similarity,
        "mean_euclidean_distance": mean_euclidean_distance,
        "pearson_correlation": pearson_correlation,
        "mse": mse,
    }


# Training arguments
training_args = TrainingArguments(
    output_dir="./roberta_results_gemini_concise_verbose",
    evaluation_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    num_train_epochs=3,
    weight_decay=0.01,
    save_strategy="epoch",
    save_total_limit=1,
    logging_dir="./roberta_logs_gemini",
    load_best_model_at_end=True,
    report_to="none",
    remove_unused_columns=False,  # Add this line
    fp16=True,  # Enable mixed precision
    gradient_accumulation_steps=4,  # Accumulate gradients over 4 steps
)

from transformers import Trainer

class CustomTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        # Forward pass
        outputs = model(**inputs)
        logits = outputs.get("logits")

        # Get the labels
        labels = inputs.get("labels")

        # Compute custom loss
        loss = cosine_similarity_loss(logits, labels)

        return (loss, outputs) if return_outputs else loss

# Use the custom trainer
trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

# Train and evaluate
trainer.train()

WARNING:root:Dropping row due to missing or empty fields: question                 Describe any areas where cost savings could be...
type                                                                  TEXT
options                                                               Text
gemini_answer_verbose                                                  NaN
Name: 0, dtype: object
WARNING:root:Dropping row due to missing or empty fields: question                 Elaborate on your response.
type                                            TEXT
options                                         Text
gemini_answer_verbose                            NaN
Name: 41, dtype: object
WARNING:root:Dropping row due to missing or empty fields: question                 How many languages do you speak?
type                                               NUMBER
options                                  languages spoken
gemini_answer_verbose                                 NaN
Name: 384, dtype: object
WARNING:root:Dropping row due to missing or empty fields: question                 What are your preferred methods for gathering ...
type                                                         SINGLE-SELECT
options                  User Interviews; Surveys; Usability Testing; A...
gemini_answer_verbose                                                  NaN
Name: 583, dtype: object
WARNING:root:Dropping row due to missing or empty fields: question                            What is your company's annual revenue?
type                                                         SINGLE-SELECT
options                  Under $1 million; $1 million - $10 million; $1...
gemini_answer_verbose                                                  NaN
Name: 602, dtype: object

Train Data Columns: Index(['question', 'type', 'options', 'gemini_answer_concise'], dtype='object')
Test Data Columns: Index(['question', 'type', 'options', 'gemini_answer_verbose'], dtype='object')
Number of training examples: 881
Number of test examples: 876

Some weights of CustomRobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/881 [00:00<?, ? examples/s]

Map:   0%|          | 0/876 [00:00<?, ? examples/s]

{'input_ids': [0, 47066, 21700, 143, 4495, 50, 583, 16857, 14, 2756, 4, 2, 2, 39645, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], 'labels': [-0.031181856989860535, -0.0037500157486647367, 0.037759896367788315, 0.02599082887172699, 0.024689776822924614, -0.09262647479772568, -0.1057235598564148, 0.012790847569704056, -0.03441647067666054, 0.07593363523483276, -0.014488144777715206, 0.17748838663101196, 0.05161619558930397, -0.030411317944526672, -0.026692096143960953, 0.016686059534549713, -0.014570926316082478, -0.03713717684149742, -0.07327727228403091, 0.046053387224674225, -0.08664724975824356, 0.0012373237404972315, -0.07901471853256226, 0.03085227683186531, 0.03170798346400261, 0.027522701770067215, -0.05120977386832237, 0.00879379641264677, 0.018116937950253487, -0.06547130644321442, -0.019870588555932045, -0.025626391172409058, -0.05697309598326683, 0.02458743378520012, 0.018739847466349602, 0.05267534404993057, 0.034282322973012924, -0.08818541467189789, -0.0021085103508085012, -0.047298066318035126, 0.010003113187849522, 0.039433423429727554, -0.0475173182785511, 0.10872893780469894, -0.08433371782302856, 0.03189739212393761, 0.019164837896823883, -0.060450371354818344, 0.004800986964255571, -0.025966254994273186, -0.0316261425614357, 0.02068604715168476, 0.030094457790255547, 0.0563213936984539, -0.00019230160978622735, -0.01416997890919447, -0.027371767908334732, 0.008150272071361542, -0.05990489572286606, 0.07307708263397217, 0.030533939599990845, 0.0039169760420918465, -0.009754438884556293, 0.0460871160030365, 0.11345499008893967, 0.059633076190948486, 0.07003355771303177, -0.05917159840464592, 0.010313012637197971, 0.006596332415938377, -0.011918989010155201, -0.017571253702044487, -0.0570281520485878, 0.06427587568759918, -0.034936897456645966, 0.044839803129434586, 0.02790844812989235, -0.07116725295782089, 0.006851410958915949, 0.04591948539018631, 0.006576769519597292, 0.013850554823875427, -0.07409434020519257, 0.014467746019363403, 0.030185671523213387, -0.028686828911304474, 0.0041513158939778805, -0.051294658333063126, 0.023547671735286713, -0.025122078135609627, 0.02737494558095932, 0.0808076485991478, 0.128372922539711, 0.07256197929382324, -0.03805096819996834, 0.02244982309639454, 0.024288510903716087, -0.002458452945575118, 0.0033710175193846226, 0.0408354327082634, 0.010120757855474949, 0.08163828402757645, 0.04771097004413605, 0.016902338713407516, -0.04792269319295883, -0.09670202434062958, 0.05505618080496788, 0.051226820796728134, -0.036437079310417175, -0.02529323287308216, -0.028960730880498886, 0.03160171955823898, -0.03126867860555649, 0.036811791360378265, -0.0067956214770674706, -0.03860880061984062, -0.12036989629268646, -0.013013101182878017, -0.0794447511434555, 0.001598421367816627, -0.018319077789783478, 0.021106647327542305, -0.04240070655941963, -0.017529357224702835, -0.006492535583674908, 0.0376150980591774, -0.005360560026019812, -2.1390173154905614e-33, 0.02530462108552456, -0.01698167435824871, 0.018147699534893036, 0.03578934073448181, 0.035866156220436096, -0.005149346776306629, -0.06976336240768433, -0.01869134046137333, -0.07366125285625458, -0.007691692560911179, 0.09019391983747482, -0.03914957866072655, 0.02429673634469509, -0.04610574617981911, 0.07467122375965118, -0.11881100386381149, 0.034733422100543976, 0.10029170662164688, 0.09819032996892929, -0.0678764209151268, 0.023128902539610863, -0.05477404594421387, -0.015112005174160004, -0.02326112985610962, 0.0691109374165535, 0.08794000744819641, -0.015523278154432774, 0.013295268639922142, 0.08131147921085358, 0.01957187056541443, -0.027416422963142395, 0.00820824597030878, -0.05684341862797737, 0.00751437759026885, -0.009729856625199318, -0.009701358154416084, -0.022961188107728958, -0.04489055648446083, -0.06617195904254913, 0.0032770701218396425, -0.03426007926464081, 0.06724389642477036, -0.04717044159770012, 0.009817470796406269, -0.008945414796471596, -0.0970190241932869, 0.005610599182546139, -0.03286886215209961, -0.056609977036714554, 0.00488197710365057, -0.02790331467986107, -0.01795171946287155, -0.0072121210396289825, 0.051168642938137054, -0.04066267982125282, 0.061088744550943375, 0.06599871069192886, -0.041234564036130905, -0.0022200611419975758, 0.1203627958893776, 0.03377559408545494, -0.07372377067804337, -0.024966059252619743, -0.10082647204399109, 0.0043516140431165695, -0.05368560180068016, 0.03455314412713051, -0.05569390580058098, -0.07904110848903656, 0.06037023290991783, -0.031514815986156464, -0.04631858691573143, 0.06824047118425369, 0.008574729785323143, 0.014813938178122044, -0.014549750834703445, -0.11196660250425339, -0.06919047236442566, -0.03362242877483368, -0.06822998076677322, -0.0056731742806732655, -0.07623589038848877, 0.012480764649808407, -0.012814972549676895, 0.008473399095237255, 0.012599767185747623, 0.020264800637960434, -0.029027093201875687, -0.06731978058815002, -0.019305234774947166, -0.07711941003799438, -0.0061369710601866245, 0.027461685240268707, -0.021747855469584465, -0.015170245431363583, 1.3837788173120463e-33, -0.11019793897867203, -0.03284556046128273, -0.09926080703735352, 0.11007519066333771, 0.02688450738787651, -0.05169364809989929, -0.018915558233857155, 0.08486340939998627, -0.09089290350675583, -0.015434598550200462, 0.023217417299747467, -0.023853849619627, -0.018794994801282883, 0.02712918631732464, -0.03571590781211853, 0.040400855243206024, 0.034993771463632584, -0.08782763034105301, 0.02358405478298664, 0.013381409458816051, -1.986310599022545e-05, 0.10344374179840088, -0.013831913471221924, 0.058384623378515244, 0.0440795011818409, 0.08948565274477005, -0.05656758323311806, 0.051591936498880386, 0.05108121410012245, 0.0027685670647770166, 0.05771282687783241, -0.07883007079362869, 0.015023954212665558, 0.015168942511081696, 0.046299904584884644, 0.07054125517606735, 0.04560910910367966, -0.008961000479757786, -0.04942968115210533, -0.02372566983103752, 0.111186683177948, 0.06994638592004776, -0.04188602417707443, 0.06255585700273514, 0.032278649508953094, -0.008552192710340023, 0.004364874679595232, 0.009887642227113247, 0.026904523372650146, 0.025890272110700607, -0.016790330410003662, -0.06996750831604004, 0.04372258111834526, 0.05247516185045242, 0.04165591672062874, 0.006136493757367134, 0.09706494212150574, 0.03262609615921974, -0.010333199054002762, -0.02392740733921528, -0.05275454744696617, -0.016064437106251717, -0.00012424525630194694, 0.0005550805944949389, 0.03492048755288124, 0.04486217349767685, 0.07577472925186157, -0.02611350081861019, -0.04991218447685242, 0.006833425723016262, 0.07374241948127747, 0.07963130623102188, -0.023862123489379883, 0.03106330707669258, 0.04655466228723526, -0.007651946973055601, -0.06881462782621384, -0.018182072788476944, -0.025065699592232704, 0.07777442783117294, -0.03707442805171013, 0.037142883986234665, -0.030392389744520187, 0.03176560625433922, 0.04183128848671913, 0.029094373807311058, -0.005835742689669132, -0.002450130181387067, -0.03784589096903801, -0.04404398426413536, -0.09791412204504013, -0.038156360387802124, -0.040957577526569366, 0.05979985371232033, 0.005162636749446392, -2.431663581603516e-08, -0.05386504903435707, 0.057672545313835144, 0.020159665495157242, 0.08547452837228775, 0.11920896917581558, -0.10503245145082474, 0.039692651480436325, 0.07286718487739563, 0.07355109602212906, 0.0318404920399189, -0.033127445727586746, -0.06340004503726959, -0.04960807412862778, 0.01656036265194416, 0.011291423812508583, -0.05100511759519577, 0.006640947889536619, 0.07008050382137299, -0.03154541552066803, -0.00045308616245165467, 0.01043474767357111, 0.025424975901842117, 0.004120715893805027, -0.03320073336362839, 0.06536082923412323, -0.023836269974708557, 0.08531828969717026, 0.062380075454711914, -0.04382745176553726, -0.05952153354883194, -0.07790760695934296, -0.04689984396100044, 0.055386342108249664, -0.039397019892930984, -0.038362063467502594, 0.06616959720849991, -0.017452077940106392, -0.008196019567549229, 0.024614037945866585, -0.00803845189511776, -0.027814511209726334, 0.08732973039150238, 0.03346983715891838, 0.03237907215952873, 0.10440235584974289, 0.061891406774520874, -0.08577994257211685, 0.044905297458171844, -0.004363944288343191, -0.08686959743499756, -0.0377047173678875, -0.03391055390238762, -0.009149888530373573, 0.10414744913578033, 0.07174277305603027, -0.11464215070009232, -0.014022808521986008, 0.029647691175341606, -0.012475255876779556, 0.03196806460618973, 0.028147291392087936, -0.04183309152722359, -0.0828697681427002, -0.015333633869886398]}

c:\Users\carol\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\carol\AppData\Local\Temp\ipykernel_16244\355253018.py:228: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `CustomTrainer.__init__`. Use `processing_class` instead.
  trainer = CustomTrainer(

Mean Cosine Similarity: 0.29020634293556213
Mean Euclidean Distance: 11.273887634277344
Pearson Correlation: 0.28818127438836594
Mean Squared Error: 0.3328837752342224
Mean Cosine Similarity: 0.3255634307861328
Mean Euclidean Distance: 11.333002090454102
Pearson Correlation: 0.31957497376091704
Mean Squared Error: 0.3392489552497864
Mean Cosine Similarity: 0.3377823829650879
Mean Euclidean Distance: 11.156314849853516
Pearson Correlation: 0.3291794478997597
Mean Squared Error: 0.33041632175445557

TrainOutput(global_step=330, training_loss=0.45508755770596593, metrics={'train_runtime': 3786.5133, 'train_samples_per_second': 0.698, 'train_steps_per_second': 0.087, 'total_flos': 344267525062656.0, 'train_loss': 0.45508755770596593, 'epoch': 2.979591836734694})

T5 concise verbose

In [3]:
from datasets import Dataset, DatasetDict
from transformers import RobertaTokenizer, RobertaForSequenceClassification, TrainingArguments, Trainer, RobertaConfig
from transformers import DataCollatorWithPadding
import pandas as pd
import numpy as np
import torch
from sentence_transformers import SentenceTransformer, util
import gc
from evaluate import load
import re
from tqdm import tqdm
import logging

class CustomRobertaModel(RobertaForSequenceClassification):
    def forward(self, input_ids=None, attention_mask=None, labels=None):
        # Pass inputs through the base model
        outputs = self.roberta(
            input_ids=input_ids,
            attention_mask=attention_mask,
        )
        # Get the `[CLS]` token embedding
        cls_embedding = outputs.last_hidden_state[:, 0, :]  # Shape: [batch_size, hidden_size]

        # Apply the classifier head
        logits = self.classifier(cls_embedding)  # Shape: [batch_size, num_labels]

        loss = None
        if labels is not None:
            loss = cosine_similarity_loss(logits, labels)

        return {"loss": loss, "logits": logits} if loss is not None else {"logits": logits}

semantic_model = SentenceTransformer('all-MiniLM-L6-v2')  # For semantic similarity

# Enable garbage collection and set memory limits
gc.enable()
torch.cuda.empty_cache() if torch.cuda.is_available() else None

# Load data for Gemini answers
train_data_path = "fine tuning datasets\preprocessed_dataset_only_t5_concise.csv"
test_data_path = "fine tuning datasets\preprocessed_dataset_only_t5_verbose.csv"

train_data = pd.read_csv(train_data_path)
test_data = pd.read_csv(test_data_path)

print("Train Data Columns:", train_data.columns)
print("Test Data Columns:", test_data.columns)

# Modify the format_data function to handle NaN values more gracefully
def format_data(df, answer_column):
    formatted_data = []
    for _, row in df.iterrows():
        question = str(row.get("question", "")).strip()
        options = str(row.get("options", "")).strip()
        answer = str(row.get(answer_column, "")).strip() if pd.notna(row.get(answer_column)) else "[NO ANSWER]"

        if question and options:  # Keep rows even if the answer is missing
            formatted_data.append({"question": question, "options": options, "answer": answer})
        else:
            logging.warning(f"Dropping row due to missing question or options: {row}")
    return Dataset.from_pandas(pd.DataFrame(formatted_data))

# Preprocess and format the datasets
train_dataset = format_data(train_data, answer_column="t5_answer_concise")
test_dataset = format_data(test_data, answer_column="t5_answer_verbose")

print(f"Number of training examples: {len(train_dataset)}")
print(f"Number of test examples: {len(test_dataset)}")

dataset = DatasetDict({
    'train': train_dataset,
    'test': test_dataset
})

# Load RoBERTa tokenizer and model
model_name = "roberta-base"  # Replace with "roberta-large" for a larger model
tokenizer = RobertaTokenizer.from_pretrained(model_name)
config = RobertaConfig.from_pretrained(model_name)

config.num_labels = 384  # Set this to the size of your embeddings
model = CustomRobertaModel.from_pretrained(model_name, config=config)
model.classifier = torch.nn.Linear(model.config.hidden_size, 384)

def preprocess_function(examples, split="train"):
    # Handle both single and batched inputs
    questions = examples["question"]
    options = examples["options"]
    answers = examples["answer"]

    # Ensure no None values exist
    assert all(isinstance(q, str) for q in questions), "Questions contain non-string values"
    assert all(isinstance(o, str) for o in options), "Options contain non-string values"
    assert all(isinstance(a, str) for a in answers), "Answers contain non-string values"

    tokenized_inputs = tokenizer(
        questions,
        options,
        truncation=True,
        max_length=256,
        padding="max_length",
    )
    assert all(tokenized_inputs["input_ids"]), "Found None in tokenized input_ids!"

    # Convert answers to embeddings
    embeddings = semantic_model.encode(answers, convert_to_tensor=True).cpu().numpy()

    if embeddings is None or len(embeddings) == 0:
        raise ValueError(f"Semantic model returned empty embeddings for {split} data.")

    # Debug: Print shapes of input_ids, attention_mask, and labels
    print(f"Split: {split}")
    print(f"input_ids shape: {np.array(tokenized_inputs['input_ids']).shape}")
    print(f"attention_mask shape: {np.array(tokenized_inputs['attention_mask']).shape}")
    print(f"labels shape: {embeddings.shape}")

    # Ensure the function returns a dictionary with consistent lengths
    return {
        "input_ids": tokenized_inputs["input_ids"],
        "attention_mask": tokenized_inputs["attention_mask"],
        "labels": embeddings  # Ensure each embedding is a separate element
    }


# Tokenize datasets with labels
tokenized_datasets = DatasetDict()

# Process each split in the dataset
for split in ["train", "test"]:
    # Apply the preprocessing function to each example in the dataset
    tokenized_datasets[split] = dataset[split].map(
        lambda examples: preprocess_function(examples, split=split),
        batched=True,
        remove_columns=["question", "options", "answer"],  # Specify columns to remove
    )

# Data collator for padding
data_collator = DataCollatorWithPadding(tokenizer)

# EM and F1 Score calculations
def normalize_text(text):
    """Normalize text by lowercasing, removing articles, punctuation, and extra whitespace."""
    text = text.lower()
    text = re.sub(r'\b(a|an|the)\b', ' ', text)
    text = re.sub(r'[^\w\s]', '', text)
    return ' '.join(text.split())

def calculate_em(prediction, reference):
    """Calculate Exact Match (EM) between prediction and reference."""
    return int(normalize_text(prediction) == normalize_text(reference))

def calculate_f1(prediction, reference):
    """Calculate F1 Score between prediction and reference."""
    pred_tokens = normalize_text(prediction).split()
    ref_tokens = normalize_text(reference).split()
    common_tokens = set(pred_tokens) & set(ref_tokens)
    if len(common_tokens) == 0:
        return 0
    precision = len(common_tokens) / len(pred_tokens)
    recall = len(common_tokens) / len(ref_tokens)
    f1 = 2 * (precision * recall) / (precision + recall)
    return f1

def cosine_similarity_loss(pred, target):
    # Calculate cosine similarity loss
    return 1 - torch.nn.functional.cosine_similarity(pred, target).mean()

def compute_metrics(eval_pred):
    predictions, labels = eval_pred

    # Ensure predictions and labels are tensors
    if predictions is None or labels is None:
        logging.error("Predictions or labels are None!")
        return {}

    # Convert predictions and labels to tensors if they aren't already
    predictions = torch.tensor(predictions) if not isinstance(predictions, torch.Tensor) else predictions
    labels = torch.tensor(labels) if not isinstance(labels, torch.Tensor) else labels

    # Compute cosine similarity
    cosine_similarities = torch.nn.functional.cosine_similarity(predictions, labels, dim=-1)
    mean_cosine_similarity = torch.mean(cosine_similarities).item()

    # Compute Euclidean distance
    euclidean_distances = torch.norm(predictions - labels, dim=-1)
    mean_euclidean_distance = torch.mean(euclidean_distances).item()

    # Compute Pearson correlation
    predictions_flat = predictions.flatten()
    labels_flat = labels.flatten()
    pearson_correlation = np.corrcoef(predictions_flat.cpu().numpy(), labels_flat.cpu().numpy())[0, 1]

    # Compute Mean Squared Error (MSE)
    mse = torch.nn.functional.mse_loss(predictions, labels).item()

    # Print metrics for debugging
    print(f"Mean Cosine Similarity: {mean_cosine_similarity}")
    print(f"Mean Euclidean Distance: {mean_euclidean_distance}")
    print(f"Pearson Correlation: {pearson_correlation}")
    print(f"Mean Squared Error: {mse}")

    return {
        "mean_cosine_similarity": mean_cosine_similarity,
        "mean_euclidean_distance": mean_euclidean_distance,
        "pearson_correlation": pearson_correlation,
        "mse": mse,
    }

# Training arguments
training_args = TrainingArguments(
    output_dir="./roberta_results_t5_concise_verbose",
    evaluation_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    num_train_epochs=3,
    weight_decay=0.01,
    save_strategy="epoch",
    save_total_limit=1,
    logging_dir="./roberta_logs_t5",
    load_best_model_at_end=True,
    report_to="none",
    remove_unused_columns=False,  # Add this line
    fp16=True,  # Enable mixed precision
    gradient_accumulation_steps=4,  # Accumulate gradients over 4 steps
)

from transformers import Trainer

class CustomTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        # Forward pass
        outputs = model(**inputs)
        logits = outputs.get("logits")

        # Get the labels
        labels = inputs.get("labels")

        # Compute custom loss
        loss = cosine_similarity_loss(logits, labels)

        return (loss, outputs) if return_outputs else loss


# Use the custom trainer
trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

# Train and evaluate
trainer.train()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\carol\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\carol\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\carol\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

Train Data Columns: Index(['question', 'type', 'options', 't5_answer_concise'], dtype='object')
Test Data Columns: Index(['question', 'type', 'options', 't5_answer_verbose'], dtype='object')
Number of training examples: 881
Number of test examples: 881

Some weights of CustomRobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/881 [00:00<?, ? examples/s]

Split: train
input_ids shape: (881, 256)
attention_mask shape: (881, 256)
labels shape: (881, 384)

Map:   0%|          | 0/881 [00:00<?, ? examples/s]

Split: test
input_ids shape: (881, 256)
attention_mask shape: (881, 256)
labels shape: (881, 384)

c:\Users\carol\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\carol\AppData\Local\Temp\ipykernel_16244\1473537338.py:250: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `CustomTrainer.__init__`. Use `processing_class` instead.
  trainer = CustomTrainer(

Mean Cosine Similarity: 0.4237176179885864
Mean Euclidean Distance: 11.72000789642334
Pearson Correlation: 0.42420631543962534
Mean Squared Error: 0.35985952615737915
Mean Cosine Similarity: 0.49553829431533813
Mean Euclidean Distance: 11.260412216186523
Pearson Correlation: 0.495421757530641
Mean Squared Error: 0.3317019045352936
Mean Cosine Similarity: 0.5257748365402222
Mean Euclidean Distance: 10.535690307617188
Pearson Correlation: 0.5260928304668868
Mean Squared Error: 0.2905827760696411

TrainOutput(global_step=330, training_loss=0.5776736635150331, metrics={'train_runtime': 4214.191, 'train_samples_per_second': 0.627, 'train_steps_per_second': 0.078, 'total_flos': 344267525062656.0, 'train_loss': 0.5776736635150331, 'epoch': 2.979591836734694})

assign different difficulty levels

In [51]:
import pandas as pd
import numpy as np

def load_datasets():
    """Loads the T5 dataset."""
    try:
        # Load T5 answers
        t5_df = pd.read_csv('T5_datasets/cleaned_all_T5_answers_combined.csv')
        print("T5 DataFrame columns:", t5_df.columns.tolist())
        return t5_df  # Return only t5_df
    except Exception as e:
        print(f"Error loading dataset: {str(e)}")
        return None

def assign_difficulty_level(text):
    """Assigns difficulty level based on text length."""
    if pd.isna(text) or text is None:
        return 'unknown'
    text = str(text).strip()  # Remove unnecessary spaces
    if len(text) < 50:
        return 'short'
    elif len(text) > 150:
        return 'long'
    else:
        return 'moderate'

def create_difficulty_dataset():
    """Creates a dataset categorizing answers by difficulty."""
    t5_df = load_datasets()
    if t5_df is None:
        return None

    # Ensure 'question' column exists and drop NaN values
    if 'question' not in t5_df.columns:
        print("Error: 'question' column not found in dataset.")
        return None

    t5_df = t5_df.dropna(subset=['question'])

    # Convert questions to a unique set for efficient processing
    questions = t5_df['question'].dropna()
    print("numer questions", questions.count())
    def process_questions(questions_set):
        answers_data = []
        for q in questions_set:
            # Get question metadata safely
            q_data = t5_df[t5_df['question'] == q]
            if q_data.empty:
                continue  # Skip if no data is found for the question

            q_row = q_data.iloc[0]  # Take the first occurrence

            # Process T5 answers for different tones
            for tone in ['verbose', 'concise', 'colloquial', 'explanatory', 'annoyed']:
                tone_data = q_data[q_data['tone'] == tone]  # Ensure correct column
                
                if not tone_data.empty:
                    answer = tone_data['answer'].iloc[0]
                    answers_data.append({
                        'question': q,
                        'type': q_row['type'] if 'type' in q_row else 'unknown',
                        'options': q_row['options'] if 'options' in q_row else 'none',
                        'answer': answer,
                        'model': 'T5',  # Ensuring the 'model' column exists
                        'tone': tone,
                        'difficulty': assign_difficulty_level(answer)
                    })
        return answers_data

    # Process unique questions
    all_answers_data = process_questions(questions)

    # Create DataFrame with all answers and difficulties
    difficulty_df = pd.DataFrame(all_answers_data)

    return difficulty_df

def save_difficulty_files(difficulty_df):
    """Saves the dataset into separate CSV files based on difficulty level."""
    if difficulty_df.empty:
        print("Error: No data found in difficulty_df. Skipping file saving.")
        return

    # Ensure 'model' column exists
    if 'model' not in difficulty_df.columns:
        print("Error: 'model' column missing in difficulty_df.")
        return

    # Filter for T5 model only
    model_df = difficulty_df[difficulty_df["model"] == "T5"]

    if model_df.empty:
        print("Warning: No data found for T5. Skipping file saving.")
        return

    # Save short answers
    short_df = model_df[model_df['difficulty'] == 'short']
    short_df.to_csv('T5_short_answers.csv', index=False, encoding='utf-8')

    # Save long answers
    long_df = model_df[model_df['difficulty'] == 'long']
    long_df.to_csv('T5_long_answers.csv', index=False, encoding='utf-8')

def main():
    """Main execution function."""
    difficulty_df = create_difficulty_dataset()

    if difficulty_df is not None:
        # Save difficulty files
        save_difficulty_files(difficulty_df)
        print("Successfully created difficulty files for T5.")

        # Print dataset statistics
        print("\nDataset Statistics:")
        print(f"Total number of answers: {len(difficulty_df)}")
        print(f"Number of unique questions: {difficulty_df['question'].nunique()}")

        print("\nDifficulty distribution:")
        print(difficulty_df['difficulty'].value_counts())

        print("\nSample of dataset:")
        print(difficulty_df.head())

        # Print distribution by model and tone
        print("\nDistribution by model and tone:")
        print(pd.crosstab(difficulty_df['model'], difficulty_df['tone']))

        # Print difficulty distribution by model
        print("\nDifficulty distribution by model:")
        print(pd.crosstab(difficulty_df['model'], difficulty_df['difficulty']))

    else:
        print("Failed to create dataset")

if __name__ == "__main__":
    main()

T5 DataFrame columns: ['type', 'question', 'options', 'answer', 'tone']
numer questions 4397
Successfully created difficulty files for T5.

Dataset Statistics:
Total number of answers: 21955
Number of unique questions: 881

Difficulty distribution:
difficulty
short       15489
moderate     6306
long          155
unknown         5
Name: count, dtype: int64

Sample of dataset:
                                     question           type  options answer
0  Are you currently using a similar product?  SINGLE-SELECT  Yes; No    Yes  \
1  Are you currently using a similar product?  SINGLE-SELECT  Yes; No    Yes
2  Are you currently using a similar product?  SINGLE-SELECT  Yes; No    Yes
3  Are you currently using a similar product?  SINGLE-SELECT  Yes; No    Yes
4  Are you currently using a similar product?  SINGLE-SELECT  Yes; No    Yes

  model         tone difficulty
0    T5      verbose      short
1    T5      concise      short
2    T5   colloquial      short
3    T5  explanatory      short
4    T5      annoyed      short

Distribution by model and tone:
tone   annoyed  colloquial  concise  explanatory  verbose
model
T5        4397        4394     4390         4393     4381

Difficulty distribution by model:
difficulty  long  moderate  short  unknown
model
T5           155      6306  15489        5

In [42]:
import pandas as pd
import numpy as np

def load_datasets():
    try:
        # Load T5 answers
        t5_df = pd.read_csv('T5_datasets/cleaned_all_T5_answers_combined.csv')
        print("T5 DataFrame columns:", t5_df.columns.tolist())

        return t5_df  # Return only t5_df

    except Exception as e:
        print(f"Error loading datasets: {str(e)}")
        return None

def assign_difficulty_level(text):
    """Assigns difficulty level based on text length."""
    if pd.isna(text) or text is None:
        return 'unknown'
    text = str(text).strip()  # Remove unnecessary spaces
    if len(text) < 50:
        return 'short'
    elif len(text) > 150:
        return 'long'
    else:
        return 'moderate'

def create_difficulty_dataset():
    """Creates a dataset categorizing answers by difficulty."""
    t5_df = load_datasets()
    if t5_df is None:
        return None

    # Ensure 'question' column exists and drop NaN values
    if 'question' not in t5_df.columns:
        print("Error: 'question' column not found in dataset.")
        return None

    t5_df = t5_df.dropna(subset=['question'])

    # Convert questions to a unique set for efficient processing
    unique_questions = set(t5_df['question'].dropna())

    def process_questions(questions_set, t5_df):
        answers_data = []
        for q in questions_set:
            # Get question metadata
            q_data = t5_df[t5_df['question'] == q]
            if q_data.empty:
                continue  # Skip if no data found for the question

            q_row = q_data.iloc[0]  # Take the first occurrence

            # Process T5 answers
            for tone in ['verbose', 'concise', 'colloquial', 'explanatory', 'annoyed']:
                tone_data = q_data[q_data['answer'] == tone]  # Ensure correct column
                if not tone_data.empty:
                    answer = tone_data['answer'].iloc[0]
                    difficulty = assign_difficulty_level(answer)  # Ensure difficulty is assigned
                    answers_data.append({
                        'question': q,
                        'type': q_row['type'] if 'type' in q_row else 'unknown',
                        'options': q_row['options'] if 'options' in q_row else 'none',
                        'answer': answer,
                        'model': 'T5',
                        'tone': tone,
                        'difficulty': difficulty  # Ensure 'difficulty' column exists
                    })

        return answers_data


    # Process unique questions
    all_answers_data = process_questions(unique_questions, t5_df)

    # Create DataFrame with all answers and difficulties
    difficulty_df = pd.DataFrame(all_answers_data)

    return difficulty_df

def save_difficulty_files(difficulty_df):
    """Saves the dataset into separate CSV files based on difficulty level."""
    if difficulty_df.empty:
        print("Error: No data found in difficulty_df. Skipping file saving.")
        return
    
    # Ensure 'model' exists
    if 'model' not in difficulty_df.columns:
        print("Error: 'model' column missing in difficulty_df.")
        return

    # Filter for T5 model only
    model_df = difficulty_df[difficulty_df["model"] == "T5"]
    
    if model_df.empty:
        print("Warning: No data found for T5. Skipping file saving.")
        return

    # Save short answers
    short_df = model_df[model_df['difficulty'] == 'short']
    short_df.to_csv('T5_short_answers.csv', index=False, encoding='utf-8')

    # Save long answers
    long_df = model_df[model_df['difficulty'] == 'long']
    long_df.to_csv('T5_long_answers.csv', index=False, encoding='utf-8')

def main():
    """Main execution function."""
    difficulty_df = create_difficulty_dataset()

    if difficulty_df is not None:
        # Save difficulty files
        save_difficulty_files(difficulty_df)
        print("Successfully created difficulty files for T5.")

        # Print dataset statistics
        print("\nDataset Statistics:")
        print(f"Total number of answers: {len(difficulty_df)}")

        print("\nDifficulty distribution:")
        print(difficulty_df['difficulty'].value_counts())

        print("\nSample of dataset:")
        print(difficulty_df.head())

        # Print distribution by model and tone
        print("\nDistribution by model and tone:")
        print(pd.crosstab(difficulty_df['model'], difficulty_df['tone']))  # Fixed

        # Print difficulty distribution by model
        print("\nDifficulty distribution by model:")
        print(pd.crosstab(difficulty_df['model'], difficulty_df['difficulty']))  # Fixed

    else:
        print("Failed to create dataset")

if __name__ == "__main__":
    main()

T5 DataFrame columns: ['type', 'question', 'options', 'answer', 'tone']
Error: No data found in difficulty_df. Skipping file saving.
Successfully created difficulty files for T5.

Dataset Statistics:
Total number of answers: 0

Difficulty distribution:

KeyError: 'difficulty'

Train on Gemini short answers and evaluate on Gemini long answers

In [ ]:
from datasets import Dataset, DatasetDict
from transformers import RobertaTokenizer, RobertaForSequenceClassification, TrainingArguments, Trainer, RobertaConfig
from transformers import DataCollatorWithPadding
import pandas as pd
import numpy as np
import torch
from sentence_transformers import SentenceTransformer, util
import gc
from evaluate import load
from tqdm import tqdm
import logging

class CustomRobertaModel(RobertaForSequenceClassification):
    def forward(self, input_ids=None, attention_mask=None, labels=None):
        # Pass inputs through the base model
        outputs = self.roberta(
            input_ids=input_ids,
            attention_mask=attention_mask,
        )
        # Get the `[CLS]` token embedding
        cls_embedding = outputs.last_hidden_state[:, 0, :]  # Shape: [batch_size, hidden_size]

        # Apply the classifier head
        logits = self.classifier(cls_embedding)  # Shape: [batch_size, num_labels]

        loss = None
        if labels is not None:
            loss = cosine_similarity_loss(logits, labels)

        return {"loss": loss, "logits": logits} if loss is not None else {"logits": logits}


# Initialize evaluation metrics
rouge = load('rouge')
meteor = load('meteor')
bleu = load('bleu')
semantic_model = SentenceTransformer('all-MiniLM-L6-v2')  # For semantic similarity


# Enable garbage collection and set device
gc.enable()
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# Load data for Gemini short answers and T5 long answers
gemini_short_path = "fine tuning datasets/Gemini_short_answers.csv"
gemini_long_path = "fine tuning datasets/Gemini_long_answers.csv"

gemini_short_data = pd.read_csv(gemini_short_path)
gemini_long_data = pd.read_csv(gemini_long_path)

print("Gemini Short Data Columns:", gemini_short_data.columns)
print("Gemini Long Data Columns:", gemini_long_data.columns)

# Select a subset of the data
train_subset_size = 881  # Number of samples to use from the training dataset
test_subset_size = 881    # Number of samples to use from the test dataset

gemini_short_data = gemini_short_data.sample(n=train_subset_size, random_state=42)
gemini_long_data = gemini_long_data.sample(n=test_subset_size, random_state=42)

# Format datasets
def format_data(df, answer_column):
    formatted_data = []
    for _, row in df.iterrows():
        question = str(row.get("question", "")).strip()
        options = str(row.get("options", "")).strip()
        answer = str(row.get(answer_column, "")).strip() if pd.notna(row.get(answer_column)) else "[NO ANSWER]"

        if question and options:  # Keep rows even if the answer is missing
            formatted_data.append({"question": question, "options": options, "answer": answer})
        else:
            logging.warning(f"Dropping row due to missing question or options: {row}")
    return Dataset.from_pandas(pd.DataFrame(formatted_data))

# Preprocess and format the datasets
train_dataset = format_data(gemini_short_data, answer_column="answer")
test_dataset = format_data(gemini_long_data, answer_column="answer")

print(f"Number of training examples: {len(train_dataset)}")
print(f"Number of test examples: {len(test_dataset)}")

dataset = DatasetDict({
    'train': train_dataset,
    'test': test_dataset
})

# Load RoBERTa tokenizer and model
model_name = "roberta-base"  # Replace with "roberta-large" for a larger model
tokenizer = RobertaTokenizer.from_pretrained(model_name)
config = RobertaConfig.from_pretrained(model_name)

config.num_labels = 384  # Set this to the size of your embeddings
model = CustomRobertaModel.from_pretrained(model_name, config=config)
model.classifier = torch.nn.Linear(model.config.hidden_size, 384)

def preprocess_function(examples, split="train"):
    questions = examples["question"]
    options = examples["options"]
    answers = examples["answer"]

    # Ensure no None values exist
    assert all(isinstance(q, str) for q in questions), "Questions contain non-string values"
    assert all(isinstance(o, str) for o in options), "Options contain non-string values"
    assert all(isinstance(a, str) for a in answers), "Answers contain non-string values"

    tokenized_inputs = tokenizer(
        questions,
        options,
        truncation=True,
        max_length=256,
        padding="max_length",
    )
    assert all(tokenized_inputs["input_ids"]), "Found None in tokenized input_ids!"

    # Convert answers to embeddings
    semantic_model = SentenceTransformer('all-MiniLM-L6-v2')
    embeddings = semantic_model.encode(answers, convert_to_tensor=True).cpu().numpy()

    if embeddings is None or len(embeddings) == 0:
        raise ValueError(f"Semantic model returned empty embeddings for {split} data.")

    return {
        "input_ids": tokenized_inputs["input_ids"],
        "attention_mask": tokenized_inputs["attention_mask"],
        "labels": embeddings
    }

# Tokenize datasets with labels
tokenized_datasets = DatasetDict()

# Process each split in the dataset
for split in ["train", "test"]:
    tokenized_datasets[split] = dataset[split].map(
        lambda examples: preprocess_function(examples, split=split),
        batched=True,
        remove_columns=["question", "options", "answer"],
    )

# Data collator for padding
data_collator = DataCollatorWithPadding(tokenizer)

def cosine_similarity_loss(pred, target):
    # Calculate cosine similarity loss
    return 1 - torch.nn.functional.cosine_similarity(pred, target).mean()

def compute_metrics(eval_pred):
    predictions, labels = eval_pred

    # Ensure predictions and labels are tensors
    if predictions is None or labels is None:
        logging.error("Predictions or labels are None!")
        return {}

    # Convert predictions and labels to tensors if they aren't already
    predictions = torch.tensor(predictions) if not isinstance(predictions, torch.Tensor) else predictions
    labels = torch.tensor(labels) if not isinstance(labels, torch.Tensor) else labels

    # Compute cosine similarity
    cosine_similarities = torch.nn.functional.cosine_similarity(predictions, labels, dim=-1)
    mean_cosine_similarity = torch.mean(cosine_similarities).item()

    # Compute Euclidean distance
    euclidean_distances = torch.norm(predictions - labels, dim=-1)
    mean_euclidean_distance = torch.mean(euclidean_distances).item()

    # Compute Pearson correlation
    predictions_flat = predictions.flatten()
    labels_flat = labels.flatten()
    pearson_correlation = np.corrcoef(predictions_flat.cpu().numpy(), labels_flat.cpu().numpy())[0, 1]

    # Compute Mean Squared Error (MSE)
    mse = torch.nn.functional.mse_loss(predictions, labels).item()

    # Print metrics for debugging
    print(f"Mean Cosine Similarity: {mean_cosine_similarity}")
    print(f"Mean Euclidean Distance: {mean_euclidean_distance}")
    print(f"Pearson Correlation: {pearson_correlation}")
    print(f"Mean Squared Error: {mse}")

    return {
        "mean_cosine_similarity": mean_cosine_similarity,
        "mean_euclidean_distance": mean_euclidean_distance,
        "pearson_correlation": pearson_correlation,
        "mse": mse,
    }

# Training arguments
training_args = TrainingArguments(
    output_dir="./roberta_results_gemini_short_to_long",
    evaluation_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=4,  # Increase batch size if possible
    per_device_eval_batch_size=4,   # Increase batch size if possible
    num_train_epochs=3,
    weight_decay=0.01,
    save_strategy="epoch",
    save_total_limit=1,
    logging_dir="./roberta_logs_gemini_short_to_long",
    load_best_model_at_end=True,
    report_to="none",
    remove_unused_columns=False,
    fp16=True,
    gradient_accumulation_steps=2,  # Adjust based on batch size
)

class CustomTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        # Forward pass
        outputs = model(**inputs)
        logits = outputs.get("logits")

        # Get the labels
        labels = inputs.get("labels")

        # Compute custom loss
        loss = cosine_similarity_loss(logits, labels)

        return (loss, outputs) if return_outputs else loss

# Use the custom trainer
trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

# Train and evaluate
trainer.train()

WARNING:tensorflow:From c:\Users\carol\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\carol\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\carol\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\carol\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

Using device: cpu
Gemini Short Data Columns: Index(['question', 'type', 'options', 'answer', 'model', 'tone', 'difficulty'], dtype='object')
Gemini Long Data Columns: Index(['question', 'type', 'options', 'answer', 'model', 'tone', 'difficulty'], dtype='object')
Number of training examples: 100
Number of test examples: 50

Some weights of CustomRobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/100 [00:00<?, ? examples/s]

Map:   0%|          | 0/50 [00:00<?, ? examples/s]

c:\Users\carol\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\carol\AppData\Local\Temp\ipykernel_4244\2410539267.py:222: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `CustomTrainer.__init__`. Use `processing_class` instead.
  trainer = CustomTrainer(

Mean Cosine Similarity: 0.16187211871147156
Mean Euclidean Distance: 8.131562232971191
Pearson Correlation: 0.16241023725396408
Mean Squared Error: 0.17229591310024261
Mean Cosine Similarity: 0.20022223889827728
Mean Euclidean Distance: 8.081315040588379
Pearson Correlation: 0.20064099482046632
Mean Squared Error: 0.1701873540878296
Mean Cosine Similarity: 0.20404884219169617
Mean Euclidean Distance: 7.892219066619873
Pearson Correlation: 0.20456512816006878
Mean Squared Error: 0.1623663604259491

TrainOutput(global_step=36, training_loss=0.7081734339396158, metrics={'train_runtime': 384.2896, 'train_samples_per_second': 0.781, 'train_steps_per_second': 0.094, 'total_flos': 36707885383680.0, 'train_loss': 0.7081734339396158, 'epoch': 2.8})

Train on T5 short answers and evaluate on T5 long answers

In [6]:
from datasets import Dataset, DatasetDict
from transformers import RobertaTokenizer, RobertaForSequenceClassification, TrainingArguments, Trainer, RobertaConfig
from transformers import DataCollatorWithPadding
import pandas as pd
import numpy as np
import torch
from sentence_transformers import SentenceTransformer, util
import gc
from evaluate import load
from tqdm import tqdm
import logging

class CustomRobertaModel(RobertaForSequenceClassification):
    def forward(self, input_ids=None, attention_mask=None, labels=None):
        # Pass inputs through the base model
        outputs = self.roberta(
            input_ids=input_ids,
            attention_mask=attention_mask,
        )
        # Get the `[CLS]` token embedding
        cls_embedding = outputs.last_hidden_state[:, 0, :]  # Shape: [batch_size, hidden_size]

        # Apply the classifier head
        logits = self.classifier(cls_embedding)  # Shape: [batch_size, num_labels]

        loss = None
        if labels is not None:
            loss = cosine_similarity_loss(logits, labels)

        return {"loss": loss, "logits": logits} if loss is not None else {"logits": logits}


# Initialize evaluation metrics
rouge = load('rouge')
meteor = load('meteor')
bleu = load('bleu')
semantic_model = SentenceTransformer('all-MiniLM-L6-v2')  # For semantic similarity


# Enable garbage collection and set device
gc.enable()
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(f"Using device: {device}")

# Load data for T5 short and long answers
t5_short_path = "fine tuning datasets\T5_short_answers.csv"
t5_long_path = "fine tuning datasets\T5_long_answers.csv"

t5_short_data = pd.read_csv(t5_short_path)
t5_long_data = pd.read_csv(t5_long_path)

print("T5 Short Data Columns:", t5_short_data.columns)
print("T5 Long Data Columns:", t5_long_data.columns)

# Select a subset of the data
train_subset_size = 300  # Number of samples to use from the training dataset
test_subset_size = 300    # Number of samples to use from the test dataset

t5_short_data = t5_short_data.sample(n=train_subset_size, random_state=42)
t5_long_data = t5_long_data.sample(n=test_subset_size, random_state=42)

# Format datasets
def format_data(df, answer_column):
    formatted_data = []
    for _, row in df.iterrows():
        question = str(row.get("question", "")).strip()
        options = str(row.get("options", "")).strip()
        answer = str(row.get(answer_column, "")).strip() if pd.notna(row.get(answer_column)) else "[NO ANSWER]"

        if question and options:  # Keep rows even if the answer is missing
            formatted_data.append({"question": question, "options": options, "answer": answer})
        else:
            logging.warning(f"Dropping row due to missing question or options: {row}")
    return Dataset.from_pandas(pd.DataFrame(formatted_data))

# Preprocess and format the datasets
train_dataset = format_data(t5_short_data, answer_column="answer")
test_dataset = format_data(t5_long_data, answer_column="answer")

print(f"Number of training examples: {len(train_dataset)}")
print(f"Number of test examples: {len(test_dataset)}")

dataset = DatasetDict({
    'train': train_dataset,
    'test': test_dataset
})

# Load RoBERTa tokenizer and model
model_name = "roberta-base"  # Replace with "roberta-large" for a larger model
tokenizer = RobertaTokenizer.from_pretrained(model_name)
config = RobertaConfig.from_pretrained(model_name)

config.num_labels = 384  # Set this to the size of your embeddings
model = CustomRobertaModel.from_pretrained(model_name, config=config)
model.classifier = torch.nn.Linear(model.config.hidden_size, 384)

def preprocess_function(examples, split="train"):
    questions = examples["question"]
    options = examples["options"]
    answers = examples["answer"]

    # Ensure no None values exist
    assert all(isinstance(q, str) for q in questions), "Questions contain non-string values"
    assert all(isinstance(o, str) for o in options), "Options contain non-string values"
    assert all(isinstance(a, str) for a in answers), "Answers contain non-string values"

    tokenized_inputs = tokenizer(
        questions,
        options,
        truncation=True,
        max_length=256,
        padding="max_length",
    )
    assert all(tokenized_inputs["input_ids"]), "Found None in tokenized input_ids!"

    # Convert answers to embeddings
    semantic_model = SentenceTransformer('all-MiniLM-L6-v2')
    embeddings = semantic_model.encode(answers, convert_to_tensor=True).cpu().numpy()

    if embeddings is None or len(embeddings) == 0:
        raise ValueError(f"Semantic model returned empty embeddings for {split} data.")

    return {
        "input_ids": tokenized_inputs["input_ids"],
        "attention_mask": tokenized_inputs["attention_mask"],
        "labels": embeddings
    }

# Tokenize datasets with labels
tokenized_datasets = DatasetDict()

# Process each split in the dataset
for split in ["train", "test"]:
    tokenized_datasets[split] = dataset[split].map(
        lambda examples: preprocess_function(examples, split=split),
        batched=True,
        remove_columns=["question", "options", "answer"],
    )

# Data collator for padding
data_collator = DataCollatorWithPadding(tokenizer)

def cosine_similarity_loss(pred, target):
    # Calculate cosine similarity loss
    return 1 - torch.nn.functional.cosine_similarity(pred, target).mean()

def compute_metrics(eval_pred):
    predictions, labels = eval_pred

    # Ensure predictions and labels are tensors
    if predictions is None or labels is None:
        logging.error("Predictions or labels are None!")
        return {}

    # Convert predictions and labels to tensors if they aren't already
    predictions = torch.tensor(predictions) if not isinstance(predictions, torch.Tensor) else predictions
    labels = torch.tensor(labels) if not isinstance(labels, torch.Tensor) else labels

    # Compute cosine similarity
    cosine_similarities = torch.nn.functional.cosine_similarity(predictions, labels, dim=-1)
    mean_cosine_similarity = torch.mean(cosine_similarities).item()

    # Compute Euclidean distance
    euclidean_distances = torch.norm(predictions - labels, dim=-1)
    mean_euclidean_distance = torch.mean(euclidean_distances).item()

    # Compute Pearson correlation
    predictions_flat = predictions.flatten()
    labels_flat = labels.flatten()
    pearson_correlation = np.corrcoef(predictions_flat.cpu().numpy(), labels_flat.cpu().numpy())[0, 1]

    # Compute Mean Squared Error (MSE)
    mse = torch.nn.functional.mse_loss(predictions, labels).item()

    # Print metrics for debugging
    print(f"Mean Cosine Similarity: {mean_cosine_similarity}")
    print(f"Mean Euclidean Distance: {mean_euclidean_distance}")
    print(f"Pearson Correlation: {pearson_correlation}")
    print(f"Mean Squared Error: {mse}")

    return {
        "mean_cosine_similarity": mean_cosine_similarity,
        "mean_euclidean_distance": mean_euclidean_distance,
        "pearson_correlation": pearson_correlation,
        "mse": mse,
    }

# Training arguments
training_args = TrainingArguments(
    output_dir="./roberta_results_t5_short_to_long",
    evaluation_strategy="epoch",
    learning_rate=5e-5,
    per_device_train_batch_size=4,  # Increase batch size if possible
    per_device_eval_batch_size=4,   # Increase batch size if possible
    num_train_epochs=3,
    weight_decay=0.01,
    save_strategy="epoch",
    save_total_limit=1,
    logging_dir="./roberta_logs_t5_short_to_long",
    load_best_model_at_end=True,
    report_to="none",
    remove_unused_columns=False,
    fp16=True,
    gradient_accumulation_steps=2,  # Adjust based on batch size
)

class CustomTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        # Forward pass
        outputs = model(**inputs)
        logits = outputs.get("logits")

        # Get the labels
        labels = inputs.get("labels")

        # Compute custom loss
        loss = cosine_similarity_loss(logits, labels)

        return (loss, outputs) if return_outputs else loss

# Use the custom trainer
trainer = CustomTrainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["test"],
    tokenizer=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_metrics
)

# Train and evaluate
trainer.train()

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\carol\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\carol\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\carol\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!

Using device: cpu
T5 Short Data Columns: Index(['question', 'type', 'options', 'answer', 'model', 'tone', 'difficulty'], dtype='object')
T5 Long Data Columns: Index(['question', 'type', 'options', 'answer', 'model', 'tone', 'difficulty'], dtype='object')
Number of training examples: 300
Number of test examples: 300

Some weights of CustomRobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['classifier.dense.bias', 'classifier.dense.weight', 'classifier.out_proj.bias', 'classifier.out_proj.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Map:   0%|          | 0/300 [00:00<?, ? examples/s]

Map:   0%|          | 0/300 [00:00<?, ? examples/s]

C:\Users\carol\AppData\Local\Programs\Python\Python310\lib\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
C:\Users\carol\AppData\Local\Temp\ipykernel_1344\2148648418.py:222: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `CustomTrainer.__init__`. Use `processing_class` instead.
  trainer = CustomTrainer(

Mean Cosine Similarity: 0.18083062767982483
Mean Euclidean Distance: 9.145554542541504
Pearson Correlation: 0.18232518168460934
Mean Squared Error: 0.21808096766471863
Mean Cosine Similarity: 0.2212919145822525
Mean Euclidean Distance: 9.12304401397705
Pearson Correlation: 0.2241618745425988
Mean Squared Error: 0.2186872959136963
Mean Cosine Similarity: 0.23441055417060852
Mean Euclidean Distance: 9.214330673217773
Pearson Correlation: 0.23654823425914623
Mean Squared Error: 0.22344465553760529

TrainOutput(global_step=111, training_loss=0.6704551078177787, metrics={'train_runtime': 1181.9077, 'train_samples_per_second': 0.761, 'train_steps_per_second': 0.094, 'total_flos': 115367639777280.0, 'train_loss': 0.6704551078177787, 'epoch': 2.9333333333333336})

Plots

In [12]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Load the CSV file
file_path = "all_answers_combined_reshaped_with_BART_large_mnli_MULTI_SINGLE_TEXT_actuallyfixedlabels.csv"
df = pd.read_csv(file_path, sep='>')

# Create the directory if it doesn't exist
output_folder = "plots"
os.makedirs(output_folder, exist_ok=True)

# Count occurrences of each answer type
answer_counts = df["type"].value_counts()

# Bar Plot
plt.figure(figsize=(10, 6))
sns.barplot(x=answer_counts.index, y=answer_counts.values, palette="viridis")
plt.xlabel("Answer Category")
plt.ylabel("Count")
plt.title("Distribution of Gemini Answer Types")
plt.xticks(rotation=45)
plt.tight_layout()  # Adjust layout to fit labels

# Save bar plot
bar_plot_path = os.path.join(output_folder, "gemini_answer_type_distribution.png")
plt.savefig(bar_plot_path, dpi=300)
plt.close()  # Close the plot to free memory

print(f"Bar plot saved at: {bar_plot_path}")

# Pie Chart
plt.figure(figsize=(8, 8))
plt.pie(answer_counts, labels=answer_counts.index, autopct="%1.1f%%", colors=sns.color_palette("viridis"))
plt.title("Distribution of Gemini Answer Types")

# Save pie chart
pie_chart_path = os.path.join(output_folder, "gemini_answer_types_pie_chart.png")
plt.savefig(pie_chart_path, dpi=300)
plt.close()

print(f"Pie chart saved at: {pie_chart_path}")

Bar plot saved at: plots\gemini_answer_type_distribution.png
Pie chart saved at: plots\gemini_answer_types_pie_chart.png

In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Load the CSV file
file_path = "T5_datasets/cleaned_all_T5_answers_combined.csv"
df = pd.read_csv(file_path)

# Create the directory if it doesn't exist
output_folder = "plots"
os.makedirs(output_folder, exist_ok=True)

# Count occurrences of each answer type
answer_counts = df["type"].value_counts()

# Bar Plot
plt.figure(figsize=(10, 6))
sns.barplot(x=answer_counts.index, y=answer_counts.values, palette="viridis")
plt.xlabel("Answer Category")
plt.ylabel("Count")
plt.title("Distribution of T5 Answer Types")
plt.xticks(rotation=45)
plt.tight_layout()  # Adjust layout to fit labels

# Save bar plot
bar_plot_path = os.path.join(output_folder, "t5_answer_type_distribution.png")
plt.savefig(bar_plot_path, dpi=300)
plt.close()  # Close the plot to free memory

print(f"Bar plot saved at: {bar_plot_path}")

# Pie Chart
plt.figure(figsize=(8, 8))
plt.pie(answer_counts, labels=answer_counts.index, autopct="%1.1f%%", colors=sns.color_palette("viridis"))
plt.title("Distribution of T5 Answer Types")

# Save pie chart
pie_chart_path = os.path.join(output_folder, "t5_answer_types_pie_chart.png")
plt.savefig(pie_chart_path, dpi=300)
plt.close()

print(f"Pie chart saved at: {pie_chart_path}")

Bar plot saved at: plots\t5_answer_type_distribution.png
Pie chart saved at: plots\t5_answer_types_pie_chart.png

plotting distribution of different tones

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Load the CSV file
file_path = "artificial_answers/all_answers_combined_reshaped.csv"
df = pd.read_csv(file_path,   sep='>')

# Create a folder to save plots
output_folder = "plots"
os.makedirs(output_folder, exist_ok=True)

# Count occurrences of each answer category
answer_counts = df["answer_category"].value_counts()

# --- Bar Plot ---
plt.figure(figsize=(10, 6))
sns.barplot(x=answer_counts.index, y=answer_counts.values, palette="viridis")
plt.xlabel("Answer Category")
plt.ylabel("Count")
plt.title("Distribution of Gemini Answer Categories")
plt.xticks(rotation=45)  # Rotate labels for better readability
plt.tight_layout()

# Save bar plot
bar_plot_path = os.path.join(output_folder, "gemini_answer_category_distribution.png")
plt.savefig(bar_plot_path, dpi=300)
plt.close()  # Close to free memory

print(f"Bar plot saved at: {bar_plot_path}")

# --- Pie Chart ---
plt.figure(figsize=(8, 8))
plt.pie(answer_counts, labels=answer_counts.index, autopct="%1.1f%%", colors=sns.color_palette("viridis"))
plt.title("Gemini Answer Category Distribution")

# Save pie chart
pie_chart_path = os.path.join(output_folder, "gemini_answer_category_pie_chart.png")
plt.savefig(pie_chart_path, dpi=300)
plt.close()

print(f"Pie chart saved at: {pie_chart_path}")

Bar plot saved at: plots\gemini_answer_category_distribution.png
Pie chart saved at: plots\gemini_answer_category_pie_chart.png

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

# Load the CSV file
file_path = "fine tuning datasets/cleaned_all_T5_answers_combined.csv"
df = pd.read_csv(file_path,   sep='>')

# Create a folder to save plots
output_folder = "plots"
os.makedirs(output_folder, exist_ok=True)

# Count occurrences of each answer category
answer_counts = df["tone"].value_counts()

# --- Bar Plot ---
plt.figure(figsize=(10, 6))
sns.barplot(x=answer_counts.index, y=answer_counts.values, palette="viridis")
plt.xlabel("Answer Category")
plt.ylabel("Count")
plt.title("Distribution of T5 Answer Categories")
plt.xticks(rotation=45)  # Rotate labels for better readability
plt.tight_layout()

# Save bar plot
bar_plot_path = os.path.join(output_folder, "t5_answer_category_distribution.png")
plt.savefig(bar_plot_path, dpi=300)
plt.close()  # Close to free memory

print(f"Bar plot saved at: {bar_plot_path}")

# --- Pie Chart ---
plt.figure(figsize=(8, 8))
plt.pie(answer_counts, labels=answer_counts.index, autopct="%1.1f%%", colors=sns.color_palette("viridis"))
plt.title("T5 Answer Category Distribution")

# Save pie chart
pie_chart_path = os.path.join(output_folder, "t5_answer_category_pie_chart.png")
plt.savefig(pie_chart_path, dpi=300)
plt.close()

print(f"Pie chart saved at: {pie_chart_path}")

Bar plot saved at: plots\t5_answer_category_distribution.png
Pie chart saved at: plots\t5_answer_category_pie_chart.png

In [8]:
import pandas as pd
import matplotlib.pyplot as plt
import os

# Define file paths
concise_data = "fine tuning datasets/preprocessed_dataset_only_gemini_concise.csv"
verbose_data = "fine tuning datasets/preprocessed_dataset_only_gemini_verbose.csv"

# Load datasets
df_concise = pd.read_csv(concise_data)
df_verbose = pd.read_csv(verbose_data)

# Count the number of rows in each file
row_counts = {
    "Verbose Answers": len(df_verbose),
    "Concise Answers": len(df_concise),
}

# Create output folder for saving plots
output_folder = "plots"
os.makedirs(output_folder, exist_ok=True)

# Plot bar chart
plt.figure(figsize=(6, 5))
bars = plt.bar(row_counts.keys(), row_counts.values(), color=["blue", "green"])

# Add text annotations (exact row counts)
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height, f"{height:,}", ha="center", va="bottom", fontsize=12, fontweight="bold")

# Labels and title
plt.xlabel("Answer Type")
plt.ylabel("Number of instances")
plt.title("Gemini Verbose vs Concise Answers")
plt.ylim(0, max(row_counts.values()) * 1.1)  # Adjust y-axis limit for better visibility

# Save plot
plot_path = os.path.join(output_folder, "gemini_concise_verbose_comparison.png")
plt.savefig(plot_path, dpi=300)
plt.close()

print(f"Plot saved at: {plot_path}")

Plot saved at: plots\gemini_concise_verbose_comparison.png

In [9]:
import pandas as pd
import matplotlib.pyplot as plt
import os

# Define file paths
concise_data = "fine tuning datasets/preprocessed_dataset_only_t5_concise.csv"
verbose_data = "fine tuning datasets/preprocessed_dataset_only_t5_verbose.csv"

# Load datasets
df_concise = pd.read_csv(concise_data)
df_verbose = pd.read_csv(verbose_data)

# Count the number of rows in each file
row_counts = {
    "Verbose Answers": len(df_verbose),
    "Concise Answers": len(df_concise),
}

# Create output folder for saving plots
output_folder = "plots"
os.makedirs(output_folder, exist_ok=True)

# Plot bar chart
plt.figure(figsize=(6, 5))
bars = plt.bar(row_counts.keys(), row_counts.values(), color=["blue", "green"])

# Add text annotations (exact row counts)
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height, f"{height:,}", ha="center", va="bottom", fontsize=12, fontweight="bold")

# Labels and title
plt.xlabel("Answer Type")
plt.ylabel("Number of instances")
plt.title("T5 Verbose vs Concise Answers")
plt.ylim(0, max(row_counts.values()) * 1.1)  # Adjust y-axis limit for better visibility

# Save plot
plot_path = os.path.join(output_folder, "t5_concise_verbose_comparison.png")
plt.savefig(plot_path, dpi=300)
plt.close()

print(f"Plot saved at: {plot_path}")

Plot saved at: plots\t5_concise_verbose_comparison.png

In [10]:
import pandas as pd
import matplotlib.pyplot as plt
import os

# Define file paths
short_data = "fine tuning datasets/Gemini_short_answers.csv"
long_data = "fine tuning datasets/Gemini_long_answers.csv"

# Load datasets
df_short = pd.read_csv(short_data)
df_long = pd.read_csv(long_data)

# Count the number of rows in each file
row_counts = {
    "Short Answers": len(df_short),
    "Long Answers": len(df_long),
}

# Create output folder for saving plots
output_folder = "plots"
os.makedirs(output_folder, exist_ok=True)

# Plot bar chart
plt.figure(figsize=(6, 5))
bars = plt.bar(row_counts.keys(), row_counts.values(), color=["blue", "green"])

# Add text annotations (exact row counts)
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height, f"{height:,}", ha="center", va="bottom", fontsize=12, fontweight="bold")

# Labels and title
plt.xlabel("Answer's length")
plt.ylabel("Number of instances")
plt.title("Gemini Short vs Long Answers")
plt.ylim(0, max(row_counts.values()) * 1.1)

# Save plot
plot_path = os.path.join(output_folder, "gemini_short_long_comparison.png")
plt.savefig(plot_path, dpi=300)
plt.close()

print(f"Plot saved at: {plot_path}")

Plot saved at: plots\gemini_short_long_comparison.png

In [11]:
import pandas as pd
import matplotlib.pyplot as plt
import os

# Define file paths
short_data = "fine tuning datasets/T5_short_answers.csv"
long_data = "fine tuning datasets/T5_long_answers.csv"

# Load datasets
df_short = pd.read_csv(short_data)
df_long = pd.read_csv(long_data)

# Count the number of rows in each file
row_counts = {
    "Short Answers": len(df_short),
    "Long Answers": len(df_long),
}

# Create output folder for saving plots
output_folder = "plots"
os.makedirs(output_folder, exist_ok=True)

# Plot bar chart
plt.figure(figsize=(6, 5))
bars = plt.bar(row_counts.keys(), row_counts.values(), color=["blue", "green"])

# Add text annotations (exact row counts)
for bar in bars:
    height = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, height, f"{height:,}", ha="center", va="bottom", fontsize=12, fontweight="bold")

# Labels and title
plt.xlabel("Answer's length")
plt.ylabel("Number of instances")
plt.title("T5 Short vs Long Answers")
plt.ylim(0, max(row_counts.values()) * 1.1)
# Save plot
plot_path = os.path.join(output_folder, "t5_short_long_comparison.png")
plt.savefig(plot_path, dpi=300)
plt.close()

print(f"Plot saved at: {plot_path}")

Plot saved at: plots\t5_short_long_comparison.png

Evalution metrics

In [10]:
import json
import pandas as pd
import matplotlib.pyplot as plt
import os

# Dictionary with simplified model names and corresponding result file paths
model_files = {
    "Gemini": "roberta_results_gemini_short_to_long/checkpoint-36/trainer_state.json",
    "T5": "roberta_results_t5_short_to_long/checkpoint-111/trainer_state.json"
}

# Create a folder for saving plots
output_folder = "plots"
os.makedirs(output_folder, exist_ok=True)

# Extract key metrics from each file
results = []
for model_name, file_path in model_files.items():
    try:
        with open(file_path, "r") as f:
            data = json.load(f)

        # Get the last evaluation metrics (best performance)
        last_eval = data["log_history"][-1]

        results.append({
            "Model": model_name,
            "Eval Loss": last_eval["eval_loss"],
            "Cosine Similarity": last_eval["eval_mean_cosine_similarity"],
            "Euclidean Distance": last_eval["eval_mean_euclidean_distance"],
            "MSE": last_eval["eval_mse"],
            "Pearson Correlation": last_eval["eval_pearson_correlation"]
        })

    except Exception as e:
        print(f"Error processing {file_path}: {e}")

# Convert to DataFrame
df = pd.DataFrame(results)
print("\nComparison Table:\n", df)

# Metrics to plot
metrics = ["Eval Loss", "Cosine Similarity", "Euclidean Distance", "MSE", "Pearson Correlation"]
colors = ['blue', 'green', 'red', 'purple', 'orange']

# Plot and save each metric
for metric, color in zip(metrics, colors):
    plt.figure(figsize=(8, 7))

    # Extract values for plotting
    models = df["Model"]
    values = df[metric]

    bars = plt.bar(models, values, color=color)

    # Add text labels on bars
    for bar in bars:
        plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.001, 
                 f"{bar.get_height():.4f}", ha="center", fontsize=12, fontweight="bold")

    # Labels and title
    plt.xlabel("Model")
    plt.ylabel(metric)
    plt.title(f"Comparison of {metric} Across Models")
    plt.xticks(rotation=0)  # No rotation needed for short labels

    # Save plot
    plot_path = os.path.join(output_folder, f"{metric.replace(' ', '_').lower()}_comparison.png")
    plt.savefig(plot_path, dpi=300)
    plt.close()

    print(f"Saved plot: {plot_path}")

Comparison Table:
     Model  Eval Loss  Cosine Similarity  Euclidean Distance       MSE
0  Gemini   0.795951           0.204049            7.892219  0.162366  \
1      T5   0.765589           0.234411            9.214331  0.223445

   Pearson Correlation
0             0.204565
1             0.236548
Saved plot: plots\eval_loss_comparison.png
Saved plot: plots\cosine_similarity_comparison.png
Saved plot: plots\euclidean_distance_comparison.png
Saved plot: plots\mse_comparison.png
Saved plot: plots\pearson_correlation_comparison.png

In [ ]:
import json
import pandas as pd
import matplotlib.pyplot as plt
import os

# Dictionary with simplified model names and corresponding result file paths
model_files = {
    "Gemini": "roberta_results_gemini_short_to_long/checkpoint-36/trainer_state.json",
    "T5": "roberta_results_t5_short_to_long/checkpoint-111/trainer_state.json"
}

# Create a folder for saving plots
output_folder = "plots"
os.makedirs(output_folder, exist_ok=True)

# Extract key metrics from each file
results = []
for model_name, file_path in model_files.items():
    try:
        with open(file_path, "r") as f:
            data = json.load(f)

        # Get the last evaluation metrics (best performance)
        last_eval = data["log_history"][-1]

        results.append({
            "Model": model_name,
            "Eval Loss": last_eval["eval_loss"],
            "Cosine Similarity": last_eval["eval_mean_cosine_similarity"],
            "Euclidean Distance": last_eval["eval_mean_euclidean_distance"],
            "MSE": last_eval["eval_mse"],
            "Pearson Correlation": last_eval["eval_pearson_correlation"]
        })

    except Exception as e:
        print(f"Error processing {file_path}: {e}")

# Convert to DataFrame
df = pd.DataFrame(results)
print("\nComparison Table:\n", df)

# Metrics to plot
metrics = ["Eval Loss", "Cosine Similarity", "Euclidean Distance", "MSE", "Pearson Correlation"]
colors = ['blue', 'green', 'red', 'purple', 'orange']

# Plot and save each metric
for metric, color in zip(metrics, colors):
    plt.figure(figsize=(8, 7))

    # Extract values for plotting
    models = df["Model"]
    values = df[metric]

    bars = plt.bar(models, values, color=color)

    # Add text labels on bars
    for bar in bars:
        plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.001, 
                 f"{bar.get_height():.4f}", ha="center", fontsize=12, fontweight="bold")

    # Labels and title
    plt.xlabel("Model")
    plt.ylabel(metric)
    plt.title(f"Comparison of {metric} Across Models")
    plt.xticks(rotation=0)  # No rotation needed for short labels

    # Save plot
    plot_path = os.path.join(output_folder, f"{metric.replace(' ', '_').lower()}_comparison.png")
    plt.savefig(plot_path, dpi=300)
    plt.close()

    print(f"Saved plot: {plot_path}")

In [5]:
import json
import pandas as pd
import matplotlib.pyplot as plt
import os

# Dictionary with simplified model names and corresponding result file paths
model_files = {
    "Gemini": "roberta_results_gemini_concise_verbose/checkpoint-330/trainer_state.json",
    "T5": "roberta_results_t5_concise_verbose/checkpoint-330/trainer_state.json"
}

# Create a folder for saving plots
output_folder = "plots"
os.makedirs(output_folder, exist_ok=True)

# Extract key metrics from each file
results = []
for model_name, file_path in model_files.items():
    try:
        with open(file_path, "r") as f:
            data = json.load(f)

        # Get the last evaluation metrics (best performance)
        last_eval = data["log_history"][-1]

        results.append({
            "Model": model_name,
            "Eval Loss": last_eval["eval_loss"],
            "Cosine Similarity": last_eval["eval_mean_cosine_similarity"],
            "Euclidean Distance": last_eval["eval_mean_euclidean_distance"],
            "MSE": last_eval["eval_mse"],
            "Pearson Correlation": last_eval["eval_pearson_correlation"]
        })

    except Exception as e:
        print(f"Error processing {file_path}: {e}")

# Convert to DataFrame
df = pd.DataFrame(results)
print("\nComparison Table:\n", df)

# Metrics to plot
metrics = ["Eval Loss", "Cosine Similarity", "Euclidean Distance", "MSE", "Pearson Correlation"]
colors = ['blue', 'green', 'red', 'purple', 'orange']

# Plot and save each metric
for metric, color in zip(metrics, colors):
    plt.figure(figsize=(8, 7))

    # Extract values for plotting
    models = df["Model"]
    values = df[metric]

    bars = plt.bar(models, values, color=color)

    # Add text labels on bars
    for bar in bars:
        plt.text(bar.get_x() + bar.get_width()/2, bar.get_height() + 0.001, 
                 f"{bar.get_height():.4f}", ha="center", fontsize=12, fontweight="bold")

    # Labels and title
    plt.xlabel("Model")
    plt.ylabel(metric)
    plt.title(f"Comparison of {metric} Across Models")
    plt.xticks(rotation=0)  # No rotation needed for short labels

    # Save plot
    plot_path = os.path.join(output_folder, f"{metric.replace(' ', '_').lower()}_comparison.png")
    plt.savefig(plot_path, dpi=300)
    plt.close()

    print(f"Saved plot: {plot_path}")

Comparison Table:
     Model  Eval Loss  Cosine Similarity  Euclidean Distance       MSE
0  Gemini   0.662218           0.337782           11.156315  0.330416  \
1      T5   0.474225           0.525775           10.535690  0.290583

   Pearson Correlation
0             0.329179
1             0.526093
Saved plot: plots\eval_loss_comparison.png
Saved plot: plots\cosine_similarity_comparison.png
Saved plot: plots\euclidean_distance_comparison.png
Saved plot: plots\mse_comparison.png
Saved plot: plots\pearson_correlation_comparison.png

In [19]:
import pandas as pd
from collections import Counter

# Load the dataset
file_path = "T5_datasets/cleaned_all_T5_answers_combined.csv"
df = pd.read_csv(file_path)

# Display basic information
print(df.info())
print(df.head())


answer_distribution = df['tone'].value_counts()
print("Answer Type Distribution:")
print(answer_distribution)


short = df['']
# Lexical and Syntactic Diversity

# Tokenize and count unique words
all_words = " ".join(df['answer'].astype(str)).split()
unique_words = set(all_words)

# Compute Type-Token Ratio (TTR)
ttr = len(unique_words) / len(all_words)
print(f"Lexical Diversity (TTR): {ttr:.4f}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4397 entries, 0 to 4396
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   type      4397 non-null   object
 1   question  4397 non-null   object
 2   options   4397 non-null   object
 3   answer    4396 non-null   object
 4   tone      4397 non-null   object
dtypes: object(5)
memory usage: 171.9+ KB
None
            type                                    question  options answer
0  SINGLE-SELECT  Are you currently using a similar product?  Yes; No    Yes  \
1  SINGLE-SELECT  Are you currently using a similar product?  Yes; No    Yes
2  SINGLE-SELECT  Are you currently using a similar product?  Yes; No    Yes
3  SINGLE-SELECT  Are you currently using a similar product?  Yes; No    Yes
4  SINGLE-SELECT  Are you currently using a similar product?  Yes; No    Yes

          tone
0      verbose
1      concise
2   colloquial
3  explanatory
4      annoyed
Answer Type Distribution:
tone
annoyed        881
colloquial     880
explanatory    880
concise        879
verbose        877
Name: count, dtype: int64
Lexical Diversity (TTR): 0.0586

In [18]:
import pandas as pd
from collections import Counter

# Load the dataset
file_path = "artificial_answers/all_answers_combined_reshaped_with_BART_large_mnli_MULTI_SINGLE_TEXT_actuallyfixedlabels.csv"
df = pd.read_csv(file_path, sep=">")

# Display basic information
print(df.info())
print(df.head())

# Assuming 'question_type' is the relevant column
question_distribution = df['type'].value_counts()
print("Question Type Distribution:")
print(question_distribution)

answer_distribution = df['answer_category'].value_counts()
print("Answer Type Distribution:")
print(answer_distribution)
# Lexical and Syntactic Diversity

# Tokenize and count unique words
all_words = " ".join(df['answer'].astype(str)).split()
unique_words = set(all_words)

# Compute Type-Token Ratio (TTR)
ttr = len(unique_words) / len(all_words)
print(f"Lexical Diversity (TTR): {ttr:.4f}")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4485 entries, 0 to 4484
Data columns (total 8 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   type                          4485 non-null   object
 1   question                      4485 non-null   object
 2   options                       4485 non-null   object
 3   answer                        4485 non-null   object
 4   answer_label_GEMINI           4484 non-null   object
 5   answer_category               4485 non-null   object
 6   answer_label_BART_large_mnli  1695 non-null   object
 7   keywords_distilbert           482 non-null    object
dtypes: object(8)
memory usage: 280.4+ KB
None
   type                                           question   options
0  TEXT  Describe any areas where cost savings could be...  ['Text']  \
1  TEXT  Describe any areas where cost savings could be...  ['Text']
2  TEXT  Describe any areas where cost savings could be...  ['Text']
3  TEXT  Describe any areas where cost savings could be...  ['Text']
4  TEXT  Describe any areas where cost savings could be...  ['Text']

                                              answer
0   Significant cost savings could be realized by...  \
1   Reduce supplier costs, improve energy efficie...
2    Dude, we could totally save a ton of cash by...
3   Cost savings can be achieved through a multi-...
4    Well, obviously we need to look at our spend...

                                 answer_label_GEMINI answer_category
0  Supplier negotiation, energy efficiency, proce...         verbose  \
1                          Cost reduction strategies         concise
2  Supplier negotiation, energy saving, waste red...      colloquial
3  Contract review, energy efficiency, workflow o...     explanatory
4        Supplier negotiation, energy cost reduction         annoyed

  answer_label_BART_large_mnli
0                          NaN  \
1                          NaN
2                          NaN
3                          NaN
4                          NaN

                                 keywords_distilbert
0  cost efficiency, energy consumption, redundanc...
1    energy efficiency, redundancies, supplier costs
2                                          suppliers
3  cost savings, negotiation, price reductions, s...
4                  energy bills, spending, suppliers
Question Type Distribution:
type
DATE             958
MULTI-SELECT     947
NUMBER           933
TEXT             899
SINGLE-SELECT    748
Name: count, dtype: int64
Answer Type Distribution:
answer_category
concise        900
colloquial     897
verbose        896
explanatory    896
annoyed        896
Name: count, dtype: int64
Lexical Diversity (TTR): 0.1238